### ISSUE TITLE
Matching input to datalist values

### ISSUE THREAD

**Issue by r12a** [w3c/html#1011]
4.10.8. The datalist element
https://www.w3.org/TR/2017/WD-html52-20170406/sec-forms.html#the-datalist-element

The datalist element matches user input to options in a list. In current implementations in Chrome and Firefox, as you type into a text input field the browser suggests alternatives based on the text you type.  This is extremely useful for working with long lists (such as country selection), or for helping the user find list items when they don't know the beginning of the option text.

However, the string matching involved can be taken to various levels of complexity when dealing with languages besides English, especially because this is matching of natural language data, rather than identifiers.

Current implementations will match 'This' to 'this', which seems reasonable.  However, the i18n WG feels that browsers should as a minimum also normalise the text being compared prior to matching. We feel that this normalisation should not be compatibility normalisation (ie. it should be NFC or NFD, but not NFKC or NFKD).

We also believe that case-insensitive matching should take into account local tailoring, eg. so that Turkish i matches İ but not I.

Beyond that, however, there are many types of comparison that could be made, including things such as accent-stripping, matching kana with kanji, matching full- and half-width characters, etc.

The i18n WG proposes that the HTML spec:
1. indicate that locale-tailored string matching and normalization SHOULD be done during comparison of input strings and datalist options, and
2. include a note to alert browser implementers to the fact that they MAY want to consider additional methods of string matching for international users.

**Comment by aphillips** [comment]
The problem here is the larger problem of "string searching" (for which we have a [FPWD](https://w3c.github.io/string-search/) that we're not currently working on). This type of natural language text matching is somewhat more complex than substring or namespace name matching--including (and not limited to) case insensitivity issues. Browsers do have implementations of this kind of searching--which is not specified in HTML: it's the "find" feature.

Note that Richard wrote "matching kana with kanji", to which I would add matching katakana and hiragana (and the wide/narrow katakana equivalents should match). And to accent-stripping (the matched text), I would add respecting accepts (case-insensitively) when they form part of the user input.

**Comment by r12a** [comment]
[@aphillips please correct me if needed]

For the SHOULD text i think we're asking HTML to require implementers to:

1. apply a set of Unicode rules for case matching in certain locales - such as match dotted i with upper case dotted i for Turkish
2. use the Unicode standard normalization algorithms to normalise text where the same characters are represented in more than one way - eg. `é` as opposed to `e+<acute accent>`

Both those should be testable.

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
