### ISSUE TITLE
[question] about rules of setting max attribute after setting value in <progress> element

### ISSUE THREAD

**Issue by Jinjiang** [w3c/html#1024]
As https://w3c.github.io/html/sec-forms.html#the-progress-element says:

> if the parsed value was greater than or equal to the maximum value, then the current value of the progress bar is the maximum value of the progress bar.

So in demo https://jsfiddle.net/r5gohw4w/
If we set `50` to `value` first (before setting `100` to `max`), the current value (50) is greater than the maximum value (1.0). So the current value will be set as `1`. And then we set `100` to `max` so at the end the position of the `<progress>` element should be 1/100.

Is that correct? But in Safari & Chrome it always be 50/100.

Thanks.

**Comment by chaals** [comment]
Interesting - it depends when the normalisation step happens. Firefox behaves like blink - but Edge does the normalisation so you get 1/100 - which seems like it is actually correct according to spec.

@travisleithead @bzbarsky @hober @cynthia should we normalise the common behaviour... which would mean filing a bug on Edge and specify timing for how clamping values happens, or should we try to change the others to match what the spec seems to say and then clarify what in the spec meant it wasn't implemented like that?

**Comment by bzbarsky** [comment]
Fwiw, the Gecko implementation is that the clamping happens when you ask.  That is, the "current value" is not actually stored anywhere; it's just computed when someone (like layout) needs it.  

All that said, the spec as currently written is nonsensical, imo, and the Edge behavior is inconsistent (which is good).  If Edge were consistent, it would render `<progress max=100 value=50>` and `<progress value=50 max=100>` differently, which is not what anyone wants.

I would argue that similarly no one wants the linked demo to behave as it does in Edge.  Order in which attributes are set really should not affect the resulting state; any time it does that's a bug in the platform.

**Comment by chaals** [comment]
(In passing, note that Firefox presents `<progress value="a"></progress>` visually as completed, which is inconsistent with the spec and what it does in JS, setting value to 0.)
