### ISSUE TITLE
Bug: 8.2.4.76. Hexadecimal character reference state

### ISSUE THREAD

**Issue by todor-dk** [w3c/html#1025]
The case statement in 8.2.4.76 lists:
- Uppercase ASCII hex digit 
- Lowercase ASCII hex digit 
- ASCII digit 
- U+003B SEMICOLON character (;) 
- Anything else 

... however, "Uppercase ASCII hex digit" and "Lowercase ASCII hex digit" are defined as containing the characters "0 ... 9". This means the "ASCII digit" will never be hit. On top of this, digits (0..9) will be handle by the first case resulting in wrong results.

Suggestion - re-structure the case as follows: 
- ASCII digit 
- Uppercase ASCII hex digit 
- Lowercase ASCII hex digit 
- U+003B SEMICOLON character (;) 
- Anything else

**Comment by chaals** [comment]
Thanks for picking this up. I'll check it this week.

**Comment by chaals** [comment]
It seems that parsers generally do what they are told outside the parentheses -

> Add a numeric version of the current input character as a hexadecimal digit (...) to the character reference code.

Which is right, but not "formally defined", instead of what is inside the parentheses

> ...subtract 0x0037 from the character’s code point...

Which indeed comes out wrong if you try to apply the same rule to digits. An alternative approach would be to remove the bad parenthetical instruction, and optionally define what "a numeric version of the current character" means, but I will go with the suggestion provided - Pull request coming shortly.

Thanks for picking this up.
