### ISSUE TITLE
Improve: 8.2.4.72. Character reference state

### ISSUE THREAD

**Issue by todor-dk** [w3c/html#1026]
Please consider re-writing the "Anything else" part of "8.2.4.72. Character reference state". It is a mess and difficult to interpret and implement.

**Comment by edent** [comment]
This relates to https://w3c.github.io/html/syntax.html#character-reference-state

@todor-dk please could you give a little more detail about how it could be clarified?

**Comment by mrmixer** [comment]
When you enter the "Anything else" part, a character as already been consumed. Should it be added to the temporary buffer ? Or test for a partial match before adding it ? Should it be treated differently that what the first paragraph of the "Anything else" part says ?

> Consume the maximum number of characters possible, with the consumed characters matching one of the identifiers in the first column of the §8.5 Named character references table (in a case-sensitive manner). Append each character to the temporary buffer when it’s consumed.

It's not clear to me what are the condition for stopping and what is the state of the temporary buffer after.
I can't stop if I have an exact match because for example "Aacute" is an exact match but maybe there is a semicolon after that would match "Aacute;". But if on the next "consume" I get something else than a semicolon than there would be no match. And since it says to add the character to the temporary buffer after consuming there would be a "bad" character at the end of the buffer.

Does that mean that we need to peek (not consume) at the next character, see if, when added to the temporary buffer, it would match a line in the character reference and only consume it (and add it permanently to the temporary buffer) if it matches ? But then how would the case of the second paragraph be possible (a & followed by ascii characters and finished by a semicolon, the whole thing not matching a reference) ? If this is what to do should the spec specify to use the "next input character" to peek before consuming.

Should the matching be done using the temporary buffer (I guess not since it contains a &) and the character list doesn't ? Some pseudo code would probably make that step clearer.

The example (example 13) is a bit confusing because for some reason the & is a character in the first example string but then is a character reference in the following example strings. I think that the example fails to indicates that some reference will be interpreted if they are missing the semicolon while other wont because the name character reference list contains some lines without the ';' (for historical reason I suppose). "&Agravex" will be "interpreted" as "Àx" (because the list contains line without the semicolon), while "&acx" will be "interpreted" as "&acx" not "~x" (because there isn't a line without the semicolon).

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).
