### ISSUE TITLE
Forms [pattern] attribute should be usable with textarea

### ISSUE THREAD

**Issue by soanvig** [w3c/html#1028]
Forms [pattern] attribute should be usable with `<textarea>`. What I'm talking about is:
https://w3c.github.io/html/sec-forms.html#element-attrdef-input-pattern

Is there any reason for that attribute to be used only with inputs? The only difference between input and textarea is that the former is single line.

`<textarea>` supports [minlength] and [maxlength] but sometimes it's not enough. Sometimes one may want to limit available signs in textarea to letters-only.

**Comment by chaals** [comment]
Does this work in any browser today, or do you have a polyfill that demonstrates it?

@johanneswilm any ideas?

**Comment by chaals** [comment]
> Is there any reason for that attribute to be used only with inputs

I certainly can't see any obvious reason, beyond "we implemented it that way because we didn't think further than input"

**Comment by soanvig** [comment]
i believe that it could work exactly the same way as input does. In fact it uses standard regexp, and standard regular expression can handle multilines. AFAIK no browser implements it. No spec mentions it.

**Comment by chaals** [comment]
See also

* [stack overflow question -2012](https://stackoverflow.com/questions/13643417/how-to-validate-pattern-matching-in-textarea)
* [Angular allows this with ng-pattern](https://docs.angularjs.org/api/ng/directive/textarea)
* [bootstrap issue](https://github.com/1000hz/bootstrap-validator/issues/51)

**Comment by siusin** [comment]
Thanks @soanvig .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
