### ISSUE TITLE
Typos in Changes between Working Draft 8 and Working Draft 7

### ISSUE THREAD

**Issue by lvdbrink** [w3c/html#1078]
There are two typos in the Changes between [Working Draft 8 and Working Draft 7][1] section. 

In the 4th change listed: ‘resrouce’

In the last change listed: ‘Coordinates [...] are no longer include’ is not grammatically correct. Probably removing the word ‘are’ is the fix for this.

[1]: https://www.w3.org/TR/html52/changes.html#changes-wd7

**Comment by LJWatson** [comment]
Thanks for letting us know @lvdbrink.

Unfortunately we can't edit the HTML5.2 spec now because it's a Proposed Recommendation. This [commit on HTML5.3](https://github.com/w3c/html/commit/f9d9f969f3ed95f8fcb28db799e809f15fb76ee1)  solves the problem by clearing the changelog for the next version.

Not ideal, but fixed.
