### ISSUE TITLE
initial pass at article definition rewrite

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html#110]
I have written an initial draft of an updated [article element definition](http://stevefaulkner.github.io/article/).
This is intended as part of a wider rewrite of the way sectioning elements and the outline algorithm are defined in HTML.
The major differences between the [current article definition](http://w3c.github.io/html/sections.html#the-article-element) and the updated definition:
- What article represents is more prescribed
- definition has been simplified
- Wording around syndication and its relationship to atom 'entry' has been removed along with other 'in principle' statements
- Advice/explanation of how AT may expose has been added
- The **should** level requirement to add a heading has been emphasised.
- examples have been updated

Some Questions are:
- Is it now easier to understand?
- does it make sense?
- what more is needed?

**Comment by stevefaulkner** [comment]
related issue https://github.com/w3c/html/issues/33

**Comment by unor** [comment]
What is the reason for removing the example case of "a user-submitted comment", and the paragraph starting with "When `article` elements are nested […]"?

**Comment by stevefaulkner** [comment]
@unor user submitted comments would be better not marked up as `<article>` elements as the meaning of `<article>` becomes over generalised, degrading the semantics. It is arguable whether user submitted comments are _complete and self contained compositions_ as their meaning is directly tied to the context of the parent article. Also it does not often make sense to include individual user comments in the document outline and if this is deemed useful they can be marked up with a `<section>` element and child heading per comment. For SemWeb purposes schema.org annotations are much better to denote granular semantics such as _this is a comment_.

> "When article elements are nested […]"?

This was removed  as the nesting of article elements is de-emphasised, it could well be added as a note in the address definition http://w3c.github.io/html/sections.html#the-address-element

**Comment by unor** [comment]
@stevefaulkner Is there really a semantic difference between forum posts (which are still given as example case in the rewritten definition) and comments? There can be long and nested discussions in a blog post’s comment section just like in a forum thread, and in both cases it’s possible that the replies only make sense within the parent article’s context. A forum has a different information architecture than a blog, but as soon as we look at a single page (a thread vs. a blog post with comments), I think they should be handled the same semantically.

Not using `article` for user-submitted comments has the drawback that the [`author` link type](http://w3c.github.io/html/links.html#link-type-author) and the [`address` element](http://w3c.github.io/html/sections.html#the-address-element) can’t be used for a comment’s metadata anymore (bold emphasis mine):

> For `a` and `area` elements, the `author` keyword indicates that the referenced document provides further information about the author **of the nearest `article` element ancestor** of the element defining the hyperlink, if there is one, or of the page as a whole, otherwise.



> The `address` element represents the contact information **for its nearest `article`** or `body` element ancestor.

I always thought that using `article` + the `author` link type (for the commentator’s link to their own site, or internal link to their user profile) is a good way to semantically convey that the content is not (well, except when it’s the case) authored by the page/article author.

**Comment by AmeliaBR** [comment]
I would be disappointed to see comments removed from the definition of `<article>` without creating a parallel element that has the same semantic relationship to `<address>` or `rel="author"`.  For me, this authorship-encapsulation is as important a part of the semantic concept of `<article>` as its self-contained nature.

That said, I would also argue that comments are often self-contained in a meaningful way, even if they are extensions of other content. Stable URLs that go directly to a particular comment are provided and used in nearly every blogging platform.  Usually this is done with target fragments, but a few platforms (such as Medium) give each comment it's own URL to an individual page.

**Comment by stevefaulkner** [comment]
@unor @AmeliaBR, thanks for the insights/feedback, will work on modifying the draft, also see related https://github.com/w3c/aria/issues/275 as i consider the way `<article>` is used effects how its semantics are expressed in aural UI's and therefore the API mapping of `<article>`.

Do you have any idea about who/what consumes/makes use of the semantic relationships you describe? I understand in theory they may be important, but would like to better understand how they are used in practice.

**Comment by TzviyaSiegman** [comment]
The definition seems to assume that all `<article>`s are embedded in existing websites, thus require `<h2-h6>`. When I offer scholarly articles to users, I want to make the article (and nothing but the article) available. In that case, `<h1>` should (must?) be allowed.

**Comment by stevefaulkner** [comment]
@TzviyaSiegman the outline algorithm dictates that a heading elements rank is based on its nesting within a section. Only headings scoped to the body element can have a rank of 1 (=h1) so the highest rank a heading can have in a section/article is 2 (=h2).

**Comment by jongund** [comment]
Why are **region** and **complementary** landmark roles not allowed on the article element?

**Comment by darobin** [comment]
@stevefaulkner I would claim that that is a bug in the outline algorithm. It should start from the rootmost sectioning element that has a heading, or `body`, rather that automatically `body`. When publishing an article it is typical for there to be no more meaningful heading than the one given by the article, it would be quite weird to have to place the article's title outside `article`, or to have `h2` as the primary heading for the page.

**Comment by AmeliaBR** [comment]
@stevefaulkner Re who uses authorship semantics.

Not sure. Google used to use `rel="author"` with Google Plus profiles to enhance search results, but [dropped the feature in 2014 due to poor adoption](http://searchengineland.com/google-leave-your-authorship-markup-on-your-page-232090).  Like most of semantic HTML, there's a chicken-vs-egg issue where tools don't catch on because there isn't the semantic content out there, and authors & CMS developers don't bother including semantics because they don't have any clear effect.

**Comment by jordanlev** [comment]
YES! I very enthusiastically support this change. I respectfully disagree with some of the other responders here about the removal of "comments" as a use-case for the `<article>` tag -- to me this example in the spec was so confusing and ambiguous that I just never wound up using the `<article>` tag at all (because I can't think of a situation where a comment would be considered "syndicatable on its own" outside the context of its parent post).

Thanks @stevefaulkner

**Comment by stevefaulkner** [comment]
@jongund 

> Why are region and complementary landmark roles not allowed on the article element?

There are native HTML equivalents, so their use is encouraged by restricting role usage. What are the use cases for allowing?

**Comment by stevefaulkner** [comment]
@darobin 

> I would claim that that is a bug in the outline algorithm. It should start from the rootmost sectioning element that has a heading, or body, rather that automatically body. 

yes i agree the outline algo itself has issues that need fixing, please feel free to file an issue

**Comment by stevefaulkner** [comment]
@AmeliaBR 

> Like most of semantic HTML, there's a chicken-vs-egg issue where tools don't catch on because there isn't the semantic content out there, and authors & CMS developers don't bother including semantics because they don't have any clear effect.

That is the issue I am trying to improve, the inclusion of usage rules based on semantic relationships that are not used. Unfortunately HTML is littered with potentially useful theoretical semantics that are not reflected in real world authoring practices.

**Comment by LJWatson** [comment]
@stevefaulkner
I like the rewrite. It makes the definition much easier to understand IMO.

@unor
In conversation it doesn't seem natural to refer to a comment as an article. A comment can indeed be a stand alone piece of content, but more often than not it is not (either because it references a point made in the primary article, or because it refers to another comment).

It also seems strange to have an actual article (the blog post or whatever), as well as many articles (comments on the blog post), when they are fundamentally different things.

I'm not convinced there is a need to call out a comment as a semantically unique piece of content at all though.

**Comment by unor** [comment]
@jordanlev and @LjWatson: 

Wouldn’t this also apply to forum posts (which are still given as example in the rewrite)? Or where do you see the difference?

Exactly the same discussion could happen on a blog post page and on a forum thread (where the blog post would be equivalent to the opening post in the thread), it’s just the software that is different. Allowing `article` only in one case would make it hard to decide whether or not it should be used for discussions created by other kinds of software (e.g., mailing list archives, issue trackers, …).

**Comment by jordanlev** [comment]
My interpretation is that he means the forum post as-a-whole (the initial post and all of its replies)... which is equivalent to a blog post in the sense that there's an original "topic" and then a bunch of replies to it.

It sounds like you're interpreting "forum post" as each individual reply to the top-level post.

So perhaps this is something that should be clarified in the wording.

(Unless my interpretation is wrong and he *does* mean that each individual reply to a forum post is its own article -- in which case I give up and am just going to stick with div tags for another 10 years :)

**Comment by jordanlev** [comment]
@unor:
My interpretation is that he means the forum post as-a-whole (the initial post and all of its replies)... which is equivalent to a blog post in the sense that there's an original "topic" and then a bunch of replies to it.

It sounds like you're interpreting "forum post" as each individual reply to the top-level post.

So perhaps this is something that should be clarified in the wording?

(Unless my interpretation is wrong and he _does_ mean that each individual reply to a forum post is its own article -- in which case I give up and am just going to stick with div tags for another 10 years!)

**Comment by rossb** [comment]
@jordanlev:

I think you are right in that the forum post example is intended to encapsulate an entire thread. Otherwise it would fail the "would you give each comment its own heading in the doc outline" test, at least in my opinion (maybe that's debatable).

That creates a problem though, in that forum threads as a whole are never "complete," which is part of the opening definition.

Personally I don't think comments or forum posts should use the article element -- they can be used to publish complete and self-contained compositions, but they are more often used otherwise, and there's obviously no way for the HTML author to determine which comments/posts can be expected to be self-contained at the time of authoring the HTML.

**Comment by travisleithead** [comment]
@stevefaulkner, is this issue fixed completely by #442, or are we missing more?

**Comment by stevefaulkner** [comment]
@travisleithead , this issue is fixed
