### ISSUE TITLE
Inconsistency about body-ok for stylesheets

### ISSUE THREAD

**Issue by Comandeer** [w3c/html#1103]
There is information in section [4.8.5.13. Link type "stylesheet"](http://w3c.github.io/html/links.html#link-type-stylesheet) that this keyword is body-ok:

> The stylesheet keyword may be used with link elements. This keyword creates an external resource link that contributes to the styling processing model. **This keyword is body-ok.**

however in section [4.8.5.1. Hyperlink auditing](http://w3c.github.io/html/links.html#sec-hyperlink-auditing) there is no such information in [link types table](http://w3c.github.io/html/links.html#body-ok). What's even more confusing, there is such fragment just above that table:

> The body-ok keywords defined by this specification are prefetch, and stylesheet.

This fragment contradicts information from the table, which states that only `prefetch` and `preload` keywords are body-ok.

Probably the table should be updated to mark `stylesheet` keyword as body-ok.

**Comment by chaals** [comment]
Yes. I thought (without checking) that we had picked this up and fixed it already.

Also, **link types** should be a separate section. I reviewed the new hyperlink auditing section for markup so that would be my bad.

ping also @edent in case you want to take a look. Otherwise I will probably get to it in the next couple of days.
