### ISSUE TITLE
A11y: Color contrast issue on hovering the options in select element

### ISSUE THREAD

**Issue by iamrafan** [w3c/html#1111]
![image](https://user-images.githubusercontent.com/22068434/34024047-0fb6a072-e0fd-11e7-811b-6ae212d9d3e8.png)

On hovering over one of the options, the native background and text colors don't seem to have the WCAG recommended color-contrast ratio of 4.5 : 1.

**Comment by chaals** [comment]
This seems to be an accessibility bug in your browser, not in the HTML specification. Please file the bug against the browser.

**Comment by iamrafan** [comment]
@chaals aren't the hover colors inbuilt into the semantics of the ``` <select> ``` element?

**Comment by chaals** [comment]
@iamrafan no it isn't. 

Presentation is rarely built into semantics in the specification because we generally try to separate these two things. 

There is a rendering chapter in HTML, because fairly consistent rendering across browsers is helpful for users to understand what they are getting.

But details of colours is a user agent implementation decision.

**Comment by iamrafan** [comment]
sure, thanks
