### ISSUE TITLE
Include suggestions for auditory user agents in examples, not just visual

### ISSUE THREAD

**Issue by jkshapiro** [w3c/html#1143]
The examples in the spec occasionally make reference to how elements might be represented by visual user agents. For instance, at https://w3c.github.io/html/dom.html#elements we find
>In this example the HTML headings may be presented as large text in a desktop browser, or standard size text in bold in a mobile browser.

It would be nice to have some guidance on how they might be represented by TTS / screenreaders as well.

One particular example for which it would be nice to have guidance is [the &lt;br&gt; element](https://w3c.github.io/html/textlevel-semantics.html#the-br-element). What does "line break" mean in an audio context? Current user agents tend to ignore it, but it's been suggested that they should present it as a short pause. Which more closely matches the semantics, in a non-visual medium, of "line break"?

**Comment by jkshapiro** [comment]
There are some places, e.g. [the &lt;pre&gt; element](https://w3c.github.io/html/grouping-content.html#the-pre-element), where this is already being done. I'd just like to see more of it please.

**Comment by edent** [comment]
That's an interesting idea. Please can you give some examples of how current text-to-speech systems deal with this now?  

For example, does an `<em>` get read out with a different intonation, or is it announced another way?  

I know that `<h1>` is often announced ("Top Level Heading") - but are there other ways it is read out?

**Comment by jkshapiro** [comment]
It seems like the usual thing is to make a text string including...

- Announcements of headings, lists, current row and column when you're in a table, form fields, etc.
- Text on the page, however marked up
- Certain glyphs, e.g. bullets

...and then read it all out together.

I'm told there have been some attempts in the past to use intonation more naturally, but none have caught on, owing to the multitudinous ways page authors use and misuse HTML. Writing user agents is hard.

**Comment by jkshapiro** [comment]
Also relevant: https://www.w3.org/TR/CSS22/aural.html

**Comment by LJWatson** [comment]
We do include some informative content about the way ATs behave. For example the definition of the [```<header>``` element](http://w3c.github.io/html/sections.html#the-header-element) has this:

<Assistive Technology may convey to users the semantics of the ```<header>``` element when it applies to the whole page. This information can provide a hint as to the type of content. For example, the role of the element, which
in this case is "banner", can be announced by screen reader software when a user navigates to a ```<header>``` element that is scoped to the ```<body>``` element. User Agents may also provide methods to navigate to a ```<header>``` element scoped to the ```<body>``` element.<

We can definitely add more like this.

@jkshapiro to your comment about [```<br>```](http://w3c.github.io/html/textlevel-semantics.html#the-br-element), it has no implicit semantics. When an element has an implicit role, it's noted in the spec as having "XYZ role (default)". The [```<table>``` element](http://w3c.github.io/html/tabular-data.html#the-table-element) is an example.

The Aural Style Sheets specification morphed into the [CSS Speech module](https://www.w3.org/TR/css3-speech/). Unfortunately it doesn't have enough adoption for the W3C to ship it as an official Recommendation. Last time I checked, Safari in iOS had limited support for some properties, but that was about it.

**Comment by chaals** [comment]
With regards to examples in the spec I think it makes sense to do this. Rather than keeping this issue open, I suggest we add a note to the documentation for developing the spec (which is something that needs work anyway), and then open specific issues wherever it makes sense to add something... (or an issue covering a list of things to do).

It might be reasonable to provide putative speech styling in the rendering section. As @LJWatson notes the CSS Speech module has not been adopted by many speech engines (I know of implementations that were made for Emacspeak (which could "sing"!), and Opera.

I would be more interested in doing the work if there were some expression of interest from tools that render web pages in audio - there are quite a lot of those including OS-native ones, screenreaders, tools that generate audio directly from a page, and so on.

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
