### ISSUE TITLE
Update docs on `rev` attribute

### ISSUE THREAD

**Issue by chharvey** [w3c/html#1151]
I noticed a couple of bugs with the [now-reintroduced](https://github.com/w3c/html/issues/256) `rev` attribute, and wanted to document them here.

1. The [`.rev` IDL attribute for `HTMLAnchorElement`](https://w3c.github.io/html/textlevel-semantics.html#dom-htmlanchorelement-rev) has a broken documentation link. I think the solution would be to add it into this paragraph, and fix the link to point to it:
  > The IDL attributes download, target, rel, hreflang, and type, must reflect the respective content attributes of the same name.

2. Under the section [**Links created by `<a>` and `<area>` elements**](https://w3c.github.io/html/links.html#links-created-by-a-and-area-elements), there is documentation on the `[rev]` content attribute, which applies to `a` and `link`. This is misleading because `link` is not in the section title. Perhaps the title should be changed to “Links created by `<a>`, `<area>`, and `<link>` elements”.

3. The `[rel]` content attribute for `a` and `area` is documented in this same section, but `[rel]` for `link` is documented under its own section: [**The `link` Element**](https://w3c.github.io/html/document-metadata.html#elementdef-link). If the title of the section is changed to include “`<link>`”, perhaps documentation for `link[rel]` should be moved here.

4. Lastly, not a bug, but a question: Should the `[rev]` content attribute be allowed on `area` elements? Since `area` is very similar to `a`, I feel like it should be consistent.

**Comment by chaals** [comment]
Thank you for picking these up.

I have assigned myself to them, somewhat hopefully, but if you have time to make a Pull Request you are very welcome to do so. (I am happy to help with that...)

Comments on your detailed observations:

1. `rev` should be in that list I think, subject to testing whether that happens.
2. and 3. Yes, we should clean that up one way or another.
4. Yes, it should, IMHO.

**Comment by janboy22** [comment]
![9780738746104](https://user-images.githubusercontent.com/24379912/35537057-be2a4590-04fd-11e8-8394-cf53af0b32b7.jpg)
[Second Income Opportunities.pdf](https://github.com/w3c/html/files/1675435/Second.Income.Opportunities.pdf)

**Comment by janboy22** [comment]
I am not a developer, I know no coding. Just trying to learn all I can!

**Comment by chaals** [comment]
This is a bit more complicated than I thought. I propose to do the following (but slip to the next milestone - instead of being now a couple of days overdue, that means within 4 weeks):

* [ ] test `link rev="stylesheet" href="some-potentiall-open-doc"` which should not work in browsers and should be forbidden to work by spec. If something like that does work (it seems unlikely), file browser bugs.
* [ ] test `area rev="something" ...` for RDFa processors like Google's and Yandex' structured data validator, 
* [ ] Note that links with "rel" **only** create hyperlinks and do not create links to external resources (like stylesheets).
* [ ] Refactor the documentation, but probably by moving the description of `rev` for `link` elements up to the description of `link` elements, and if the attribute is processed by e.g. RDFa processors, make the relevant changes (which is s/link/area/ in the section mentioned, I think). The section on link types should probably also note which types are not allowed on `rev` (basically those that lead to creating a Link to an external resource`.

**Comment by chaals** [comment]
OK, it turns out that `rev` does reflect, so I am going to commit that.

having it on `area` at least breaks in that unlike `rel` it doesn't seem to reflect there, so allowing it would mean making tweaking the editorial stuff noted in some more ways.

I haven't checked if RDFa processors actually handle `rev` on `area`.

So I will commit the bugfix, and open new issues for 
1. editorial cleanup
2. whether `rev` should be allowed on `a`

**Comment by chaals** [comment]
opened #1335, #1336 to deal with the aspects of this not covered by #1328

**Comment by chharvey** [comment]
Summary for newcomers:

Item 1 is closed by #1328
Items 2 and 3 are closed by #1335
Item 4 is opened in #1336 (as of this time not closed yet)

Thanks
