### ISSUE TITLE
Propose <cookie-notice> element

### ISSUE THREAD

**Issue by nekitozzz** [w3c/html#1184]
With `<cookie-notice>` element website users can hide and automatically agree to all cookie notices if they want to (can be implemented as option in browsers).

And this feature will be especially helpful for people with disabilities who use Text-to-Speech readers. They will have less distracting experience if they disable and agree to all cookie notices.

**Comment by chaals** [comment]
This proposal is not clear enough for adding to a spec, and you should first "incubate" the idea in https://discourse.wicg.io ...

In paticular, you should have a clear problem statement, which I think is something like "users should be able to agree to accept cookies automatically", rather than go through the "cookie warning notice".

Then you would need to explain the mechanics of whatever solutions seem promising, for websites, users, and browsers. You should also examine why the problem exists. 

In this case it seems to be a European Union reqirement - and it is quite possible that using an element to make it easy to ignore cookie warnings would itself breach the relevant requirement. In which case the solution is to clarify to the EU that they have not solved the right problem, and get them to change their regulation, rather than trying to change the Web Platform.

I am going to close this here for now - if incubation leads to a proposal with some commitments for implementation through the relevant parts of the stack, it can be re-opened.
