### ISSUE TITLE
Create Style Guide for our examples

### ISSUE THREAD

**Issue by agcolom** [w3c/html#1193]
As per discussion on #1182, create a style guide with the aim to improve consistency of our examples. This guide should also highlight that html can be written in many different ways...
Items that should be covered:

- attributes in no quotes/single/double quotes, 
- HTML element and attribute names in upper case, lower case, 
(-> I'd prefer to use lower case as upper case can be hard to read for people with dyslexia)
- omissible closing tags,
- unusual position of closing angle bracket (see #487),
- general code indentation (HTML and CSS), 
- spacing (in particular in CSS declarations),
- use of semi colon in CSS declarations, 
- max line length,
- highlight of code snippets,

Please add anything else that should also be covered. Many thanks!

**Comment by scottaohara** [comment]
- Location and style of code comments.
- Indentation for JavaScript examples as well.

**Comment by edent** [comment]
Agreed with all this. I'd add

* Self closing tags `<hr />` or `<hr>`? Should `<img` end with ` />`?
   * Personal opinion - I think it makes it easier to see the tag has closed.
* No escaped characters - except invisible characters.
  * For example, I replaced `&#x05D0;` with `א`
  * I also replaced `<mo>⁢</mo>` with `<mo>&#x2062;</mo>` (There is an invisible character in the original!)

My personal opinion on your suggestions...

* attributes in no quotes/single/double quotes,
   * Double. Always. Makes it very clear where an attribute ends.
* HTML element and attribute names in upper case, lower case,
   * Lower.
* unusual position of closing angle bracket (see #487),
   * Argh! That's horrible! Keep them on the same line.
* general code indentation (HTML and CSS),
   * My preference - tabs to indent. That way people can set the width that they prefer.
* max line length,
   * None.  Every code editor can wrap lines. Having a forced wrap makes editing difficult, and makes diffs unreadable.

**Comment by scottaohara** [comment]
@edent I agree with your opinions here.  

The only thing I wonder about is the code indentation and max line length, unless we're proposing a change to [general formatting rules](https://github.com/w3c/html/blob/master/docs/contributing-documentation.md#formatting-conventions) as well.

**Comment by agcolom** [comment]
also add for JavaScript and CSS: 
- position of opening and closing parenthesis 
  * I would have a preference for opens end of line, closes on a new line. And add a blank line between CSS rule declarations.

**Comment by agcolom** [comment]
@scottaohara @edent [First_draft](https://github.com/agcolom/html/wiki/Style-Guide---WIP) (still WIP). Do you have edit access?

**Comment by scottaohara** [comment]
@agcolom thank you.

Quick thoughts:
* If a nested element, we should consistently indent. So I'd format the first code example as:
  ```
  <!-- 
    This demonstrates the preferred indentations and styling
    I will update once we've agreed where we use indentation
  -->
  <!DOCTYPE html>
  <html>
    <head>
      <title>Sample styled page</title>
      <style>
        body { 
          background: navy; 
          color: yellow; 
        }
      </style>
    </head>
    <body>
      <h1>Sample styled page</h1>
      ...
  ```
* Formatting - I'm for lowercasing all the things, unless we are specifically calling out that upppercase tags are allowed. In which case, an example that utilizes uppercase for one tag, should use them for all tags.
* Same sort of idea for optional closing tags.  If an example is showing that they are optional, then all optional closing tags should be omitted.  Otherwise I agree, examples should include closing tags, even if optional.
* For single line JavaScript, do we want to go with `// single line` instead of `/* single line */`

**Comment by agcolom** [comment]
@scottaohara Thanks! 
Single line JavaScript comment: Yes absolutely! That's just me copy pasting from CSS and forgetting to think :-P 
I'll update this according to your comments now :-)

**Comment by edent** [comment]
The `!DOCTYPE` is inconsistently capitalised throughout the examples.

It doesn't matter - https://www.w3.org/TR/html5/syntax.html#doctype - but we ought to pick one.

**Comment by agcolom** [comment]
I agree. I have a preference for lowercase here as well.... But not strongly opinionated :-) 
Do you prefer // for single line JS comments only or for single and multiline?

**Comment by edent** [comment]
I think `//` is only suitable for single line comments.

**Comment by posimmons** [comment]
making everything lowercase makes everything more simple. and comment symbols should be the same across the board

**Comment by chaals** [comment]
I generally favour lower case for markup code, double quotes for attribute delimiters, a reasonably compact style with enough whitespace to be readable, and some latitude to vary according to the needs of a particular example.

Allowing for some variation makes sense to me. I realise that one person's "very unusual" is another person's "more comfortable and natural", so this isn't something easy to set rules on.

**Comment by scottaohara** [comment]
Reading through the comments in [1199](https://github.com/w3c/html/pull/1199) and I'm wondering a bit about how we want to think about the idea of the code examples style guide here.  I'm leaning a bit more on to the idea of treating it as a "preferred" style guide than as a "strict" one.

For example things like self closing tags, or how `!doctype` is declared.  I've been thinking a lot about it, and am starting to feel a bit wary to firmly say we should choose one method and only one method for all of the spec's examples, as that will decrease the visibility to other valid formatting options.

That said, I do strongly feel that a single example, or related examples within a particular section, should have a consistent formatting style and that coding styles should not be mixed in these instances.

Please note, that if we decide that a strict style guide is the route we want to follow, you'll hear no complaints from me. I just wanted to pose the question to see what others thought.  

Thanks!

**Comment by chaals** [comment]
Apart from anything else I think after a certain level of rough clarity, effort put into ensuring consistency of style could be more profitably applied to something more important.

I'm inclined to suggest we generally make examples that match XHTML (although some cannot for various reasons). But I am not dogmatic about programming style in any event.

**Comment by LC43** [comment]
is this discussion open to everyone?  if so :) 

while reviewing #1199 , i found that:

- some references to tags use `<{p}>`, others to `&lt;/a&gt;` and even to: 
``` 
"`p`"
```
which is preferred?

- if `<mark>` is used to highlight some code, these examples will need to use `<pre highlight="html">` and escape all the other tags: ( ref.: https://github.com/w3c/html/pull/1199#discussion_r167443002 )
```
<pre highlight="html">
    &lt;table><mark>&lt;b></mark>&lt;tr>
   ...
```
- some incorrect code can be highlighted by using the "bad" class:

```
<xmp highlight="html" class="bad">
```

**Comment by edent** [comment]
@lc43 welcome! The `class="bad"` *should* highlight the entire codeblock as being "bad". In practice, it does nothing.

Regarding `mark` there are a few ways to do it. None of which is very nice.

`<pre>&lt;table><mark>&lt;b></mark>&lt;tr>...` which has all the escaped characters.

Or

```
<xmp>
   This line is good.
</xmp>
<pre>
   <mark>This line is bad.</mark>
</pre>
<xmp>
   And this is also OK.
</xmp>
```
Or...

```
<pre>
   <xmp>
      This is good
   </xmp>
   <mark>bad</mark>
   <xmp>
      Good
   </xmp>
</pre>
```

**Comment by edent** [comment]
There is another way to do this! Using line-highlighting https://tabatkins.github.io/bikeshed/#line-highlighting

```
<xmp highlight="html" line-highlight="2" line-numbers="on">
```

For some reason, line-numbers need to be on. Otherwise the highlighted line has numbers, but none of the others do.

**Comment by ericwbailey** [comment]
Would people be open to considering incorporating an [editorconfig](http://editorconfig.org/) file to assist with this effort? It is a lightweight, editor and OS-agnostic project with [a wide range of support](http://editorconfig.org/#download).

I keep one on user root and noticed when working with the repo it was trimming whitespace on save. That would have removed the spaces between some words due to the line break at 100 characters, had I not caught it. 

I'm thinking that providing a simple `.editorconfig` at the root of the repo might defensively help errors from sneaking in, while simultaneously providing some nice authoring ergonomics.

**Comment by chaals** [comment]
see also #1250

**Comment by edent** [comment]
Should we use [Unicode Control Pictures](https://en.wikipedia.org/wiki/Control_Pictures) for showing control codes?

For example, replace

* `(FF)` with `(␌)`
* `(LF)` with `(␊)`
* `(TAB)` with `(␉)`

It *is* what the pictures are there for - but I'm not sure how many users will understand them.

**Comment by scottaohara** [comment]
Reading through the proposed style guide again, and wondering if there was anything else we wanted to sort out here?  Otherwise, I'm thinking it might be nice to get this added.

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
