### ISSUE TITLE
Create  a meta tag of age limit

### ISSUE THREAD

**Issue by Andreiyw** [w3c/html#1196]
It is for the safety of children on the Internet - specify the age limit of content on the site for search engines. 
For example:
`<meta name="age" content="18+">`

**Comment by edent** [comment]
The ratings tag already exists - https://www.metatags.org/meta_name_rating - but it isn't in widespread use.

There *was* a specification calls [PICS](https://www.w3.org/PICS/) which never took off.  It was replaced by [POWDER](https://www.w3.org/2007/powder/) which also failed to be widely adopted.

**Comment by chaals** [comment]
There is a [rating system called "RTA"](https://rtalabel.org) meaning "restricted to adults" that seems to be fairly widely used for adult content. It is extremely simplistic, which may explain the high adoption rate.

Complaints around older systems often included the complexity, or the fact that they enabled ratings that matched different people's ideas of what is appropriate. Note that in the english-speaking world there are may different societies who provide many different classifications for movies, with the result that the same film may not be legally offered to the same audience under the same conditions in different places.

And for what it's worth, PICS *did* take off, but "landed again", or particularly moved to what began as PICS NG and ended up as RDF and the Web of linked data... but I would no longer recommend using PICS except for historical interest.

For now I am going to close this, since I think the use case is solved in theory and practice, and none of the solutions that have been widely supported need any change to HTML.

But thank you for the comment.
