### ISSUE TITLE
improve explanation of "highlighting" semantics

### ISSUE THREAD

**Issue by chaals** [w3c/html#1247]
Various elements (at least `b`, `em`, `i`, `mark`, `strong`, `u`) call attention to, or highlight, their content, without a clear explanation of why.

In the "[usage summary](http://w3c.github.io/html/textlevel-semantics.html#text-level-semantics-usage-summary)" section each has an example of use and a couple of words of explanation. In many cases explanations of some elements refer to others as appropriate for particular cases.

It would be helpful if there were a coherent single explanation of when to use each of them, what they mean, and when their potential uses overlap.

It is also possible that deprecating one or more of these elements is the right path forward. Since they have been there a long time, trying to remove any of them them will be a very long process - but asking the world  to stop using a deprecated element is a first step.

See also #1245, #1246, #1249

**Comment by programmer3000** [comment]
IMHO, today when quality big meaning i think should be deprecated `<em>`, `<i>`, `<mark>`, `<u>` and `<cite>` elements.
Because in global web they almost unused. Mabye only in theoretical examples often sucked out of a finger and having similar semantic.

All they just represents more or less `<b>` and `<strong>` elements, where `<strong>` - great important meaning and `<b>` not important meaning.

**Comment by Comandeer** [comment]
We had some lengthy discussions in CKSource, which element is appropriate for each case, see ckeditor/editor-recommendations#2 (`i` vs `em`), ckeditor/editor-recommendations#1 (`b` vs `strong`, ckeditor/editor-recommendations#4 (`u`). Additionally it seems that `mark` is established as implementation of highlighting searched terms (see ckeditor/editor-recommendations#63).

IMO differences between these elements are pretty clean:

* `strong` is used for conveying great importance of span of text;
* `em` is used for pointing that certain span of text should have different stress emphasis;
* `i` is used for technical terms, foreign terms etc.;
* `b` is used to distinguish some span of text (TBH I always understand "for utilitarian purposes" as just "visually");
* `u`… ok, that one is tricky, because "non-textual annotation" is very broad term, yet – there aren't so many such annotations in webpages (at least I haven't encountered many of them);
* `mark`, as I pointed already, is often seen as implementation of search or other kinds of highlithing.

Therefore I don't see a need for deprecation as every element has its own niche. The only doubt is with `u` element, which semantics is very peculiar. However I also think that it could be slightly altered to just indicate misspelled words (as there is at least minimal interest in implementing native spellchecking API, see whatwg/dom#547).

However there are two issues that I see with these elements:

* a11y,
* default styling.

The first issue is connected with implementation of accessibility tree in browsers. None of these elements, except `mark`, is even represented in it. Therefore e.g. definition of `em`, that underlines the different stress emphasis, isn't actually properly stressed out by screen readers. There is also no difference to AT between `b` and `strong` etc. I know that this issue is somehow outside of HTML scope, but without proper implementation in accesssibility tress, text-level semantics are in fact partially theoretical, meaning more to robots than humans.

The second issue is connected with the fact how these elements are styled. As it can be seen in ckeditor/editor-recommendations#4, we dropped underline functionality from CKEditor 5 not because it has "wrong" semantics, but because its styling was a big no-no from the UX point of view (underline is reserved for links). In fact all names of editor's features are derived from styling, not actual semantics – the same as in text preprocessors (e.g. Microsoft Word). In case of WYSIWYG editors for web there were even so strong statements as [<q>throw out the semantics</q>](https://github.com/ckeditor/editor-recommendations/issues/2#issuecomment-227993230). What's more, even semantics for these elements were retro-actively added to HTML standard, as prior to HTML5 they were [purely presentational](https://www.w3.org/TR/html401/present/graphics.html#h-15.2.1). Therefore IMO there's a very strong need to clearly state that HTML defines only semantics of the elements and it is totally separate from presentation layer of these elements. Maybe even separate section, similar to [the one dedicated to forms' validation security](http://w3c.github.io/html/sec-forms.html#constraints-security), would be appropriate.

@programmer3000

> Because in global web they almost unused.

Could you back up this statement with some statistics?

**Comment by chaals** [comment]
My initial impression is that I would be happy to live with neither `b` nor `u`, and replace them by styling one of the others as appropriate - probably omst often `mark` but it depends on the specific case - or `span` with e.g. microdata or ARIA providing more detailed information. 

In any event I don't think we should rush to try and do this, even if it were possible to do so.

**Comment by programmer3000** [comment]
@Comandeer 
> We had some lengthy discussions in CKSource, which element is appropriate for each case, 

Ckeditor is not HTML. And is not relevant to the issue, because CKeditor could made their editor as they want.

> `<em>` is used for pointing that certain span of text should have different stress emphasis;
yes, specification HTML said it have different stress "`<em>` element represents stress emphasis of its contents." but and `<i>` have different stress too "represents a span of text in an alternate voice or mood, or otherwise offset from the normal prose".
I think it must be deprecated, because for stress emphasis people could used `<strong>` - if strong stress emphasis or `<b>` - if not strong emphasis (people could use `<b>` and `<strong>` for every cases without any implicit understanding)

> `<i>` is used for technical terms, foreign terms etc.;
no, specification HTML said it have different stress as `<em>` element " i element represents a span of text in an alternate voice or mood, or otherwise offset from the normal prose in a manner indicating a different quality of text, such as a taxonomic designation, a technical term". It's mean `<i>` could use for technical terms in alternative voice (different stress) same as `<em>` could use for different stress.

> `<u>`… ok, that one is tricky, because "non-textual annotation" is very broad term, yet – there aren't so many such annotations in webpages (at least I haven't encountered many of them);

`<u>` could use because for mistakes no other elements  But then it must have more cleary and explicit description only about mistakes like this: "The `<u>` element represents labeling the text as being misspelt."
But I think it must be deprecated too, because for mistakes could use also `<b>` or `<strong>` - if important mistake.

> `<mark>`, as I pointed already, is often seen as implementation of search or other kinds of highlithing.

it's your humble opinion using `<mark>` for search. And what is other kinds of highlithing? 
If people strongly want possible 
specification HTML said  "The mark element represents a run of text in one document marked or highlighted for reference purposes, due to its relevance in another context. " - it's not for search. That's element have too bad implicit description. Also `<mark>` have different examples in specification HTML which doesn't match with description. And example with search result doesn't match the description. 
Sure, `<mark>` must be deprecated as it have strongly strange implicit semantic and bad description.

>  Because in global web they almost unused.
> Could you back up this statement with some statistics?

Yes, you can open global popular web sites where too much visitors like amazon and watch source code - you'll find not there something like `<i>`, `<u>`, `<mark>` or `<cite>`. 

It is possible keep one of  `<i>`, `<u>`, `<mark>` and `<em>`  for stress emphasis or strange semantic and other 3 made deprecated if peoples strongly needed for stress emphasis or strange semantic.

**Comment by Comandeer** [comment]
> Ckeditor is not HTML. And is not relevant to the issue, because CKeditor could made their editor as they want.

Please refer to [General Policies page of Editor Recommendations project](http://ckeditor.github.io/editor-recommendations/general-policies/). In fact CKEditor is all about producing semantic, accessible HTML and is relevant here as one of the HTML's use-cases.

> Yes, you can open global popular web sites where too much visitors like amazon and watch source code - you'll find not there something like `<i>`, `<u>`, `<mark>` or `<cite>`.

But there are also thousands of smaller sites, with more text content (Amazon is e-commerce website with not so much text outside of links and short descriptions of products). Probably extracting data from HTTP Archive could show how frequent is the use of these elements.

**Comment by programmer3000** [comment]
@Comandeer 
> Please refer to General Policies page of Editor Recommendations project. In fact CKEditor is all about producing semantic, accessible HTML and is relevant here as one of the HTML's use-cases.

Ckeditor - it's plugin, not HTML standard at all. Ckeditor could use any HTML element as they want or not use or use something else. 
But HTML is standard - yes. Who want is can use it.

> But there are also thousands of smaller sites, with more text content (Amazon is e-commerce website with not so much text outside of links and short descriptions of products).

Ok, you can open big BBC news site where too much content, it's no using those elements too.

**Comment by prlbr** [comment]
[HTML Design Principles](https://www.w3.org/TR/html-design-principles/) (W3C Working Draft) includes many points that may be relevant to this discussion. It’s really good to read and it’s not too long, here’s one example:

> HTML strikes a balance between semantic expressiveness and practical usefulness. Names of elements and attributes in the markup may be pragmatic (for brevity, history, simplicity) rather than completely accurate. […] The `b` and `i` elements are widely used — it is better to give them good default rendering for various media including aural than to try to ban them.

**Comment by chaals** [comment]
CKEditor is a perfectly legitimate example case - a group with a lot of experience in HTML have done some careful thinking about HTML to deploy a real-world tool that has a lot of users and therefore has to deal with a range of situations. I am grateful that thinking is shared with us, because I find it helpful to know what a range of other people think in order to reach conclusions.

[And as co-chair a reminder: please keep the discussion respectful and focused on issues.]

**Comment by programmer3000** [comment]
@chaals

> CKEditor is a perfectly legitimate example case - a group with a lot of experience in HTML have done some careful thinking about HTML to deploy a real-world tool that has a lot of users and therefore has to deal with a range of situations

You talk about different things. Standard and plugin. It's like compare HTML and Photoshop or snowboard and apple.

Sure, those older elements ( `<em>`, `<i>`, `<mark>`, `<u>` and `<cite>`). should be deprecated as have similar meaning for other elements and almost unused

**Comment by prlbr** [comment]
@catalinred, could you share which percantage of webpages include the elements `<b>`, `<em>`, `<i>`,`<u>`, `<mark>`. From your article https://css-tricks.com/average-web-page-data-analyzing-8-million-websites/ we can see that `<strong>` is used on 44,3% of webpages. The other elements would be interesting, too. Even more awesome would be a full list of elements and their percentage, which could be referenced in future discussions. Thanks in advance!

**Comment by catalinred** [comment]
Hey,

it's been a while since I updated that study, but here you can find the full statistics, which that article was based on: https://www.advancedwebranking.com/html/

Also, I think this is the exact comparison that what you're looking for: https://www.advancedwebranking.com/html/#inline-text-semantics

That comparison section shows the breakdown of around 936,809,246 "Inline text semantics" elements that were found within ~8 million pages. That data representation model is inspired by MDN's [HTML elements reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element).

Hope that helps!

**Comment by prlbr** [comment]
Thank you @catalinred. The comparison of inline text tags is helpful, but not exactly what I was looking for.

For example, the most used tag `<a>` in [that table](https://www.advancedwebranking.com/html/#inline-text-semantics) has a score of 53.4%, which I interpret as `<a>` tags being just a little bit more numerous than all the other inline tags together. But it would be wrong to conclude that `<a>` occurrs only on roughly half of the pages. In fact it occurs on 89.6% of the pages, as we can see in the table at the top which shows the twenty-five elements occurring on most pages.

A look at the heading elements also stresses the difference in these statistics. According to the list of elements used on most pages, `<h1>` is used on more pages than any other heading element, but according to the [comparison of sectioning elements](https://www.advancedwebranking.com/html/#content-sectioning) `<h3>`, `<h2>` and `<h4>` are used more often than `<h1>` in total – presumably because many pages contain multiple lower-level headings, but only one top-level heading.

So the list of elements used on most pages tells something different than the other comparisons on the page. I would have been interested in more data of the former, because, in a way, it tells more about how widespread an element is (`<h1>` is more widespread than `<h3>`, even though `<h3>` occurs more often than `<h1>` in total). But I am nevertheless thankful for your work, it does help!

We see that `<strong>`, `<i>`, `<b>`, `<em>` are the four most used inline elements which attach semantics to a string of text (not counting `<span>` and `<br>` obviously, and `<a>` as an “action” element) and `<u>` is still amongst the more popular ones.

**Comment by patrickhlauke** [comment]
for what it's worth, i use `<mark>` in code samples when wishing to highlight something specific about that particular code sample...
```
<pre><code>&lt;div <mark>tabindex="0"</mark> <mark>role="button"</mark> ...&gt; fake button &lt;/div&gt;</code></pre>
```

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
