### ISSUE TITLE
Contributing.md feedback and observations

### ISSUE THREAD

**Issue by ericwbailey** [w3c/html#1250]
I thought I'd take @chaals up on [their offer](https://github.com/w3c/html/issues/1212#issuecomment-366101352) and share the observations I had in working with [`CONTRIBUTING.md`](https://github.com/w3c/html/blob/master/CONTRIBUTING.md). 

Commentary on the language of the document is below. Provided there's any interest, I'd be more than happy to follow up the results of this conversation with a Pull Request reflecting our decisions.

---

>Contributions to this repository are intended to become part of the **W3C's HTML Recommendation**, and are governed by the W3C Patent Policy and Software and Document License.

I might link to the HTML Recommendation to remove any ambiguity about what the current Recommendation is, but to also match the convention of linking to the Patent Policy and Software and Document License. 

>Editorial improvements are welcome, just make a pull request! If you are not a member of the W3C Web Platform Working Group you may see a warning about **IPR commitments**, but this will be handled by **the editorial team**.

Seeing as this might be a contributor's first encounter with the IPR acronym, I might spell it out. It might also be beneficial to have a sentence about why it's okay to ignore the warning and where it will show up, so the reader is not left wondering if they've created extra work for the editorial team or have accidentally triggered any false alarms. For the sake of transparency, I'd also suggest linking to who the current editorial team is. 

>You should read the documentation on editing conventions and the source documents, and you may want to read how the spec is built

I might move this up before the "editorial improvements are welcome" paragraph. The idea is first you read what is required to get started, then read up on the specifics of how to do it.

>To make substantive contributions that clarify or change conformance requirements, you must either participate in the W3C Web Platform Working Group or make anon-member patent licensing commitment.

I'd suggest defining what the W3C considers the threshold for a substantive contribution, possibly pulling from [examples in this repo's history](https://github.com/w3c/html/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed). 

>For **normative changes**, a corresponding web-platform-tests PR is highly appreciated. Typically, both PRs will be merged at the same time. Note that a test change that contradicts the spec should not be merged before the corresponding spec change. If testing is not practical, please explain why and if appropriate file an issue to follow up later. Add the type:untestable or type:missing-coverage label as appropriate.

I would define what constitutes a normative change versus non-normative. This might also be a good document to proactively surface [the full index](https://w3c.github.io/html/fullindex.html#index) for questions about the meanings of W3C-specific jargon.

**Comment by LJWatson** [comment]
+1 to all your suggestions @ericwbailey. A PR would be most welcome.

**Comment by chaals** [comment]
@ericwbailey thank you for taking this up.

Just to start... (and at risk of repeating things many people know)

A **substantive change** is one that changes conformance.

Because the W3C Patent Policy hinges on granting licenses for "essential claims", i.e. stuff you need to do to implement the spec, as well as purely editorial changes removing things generally doesn't need a patent grant. Especially when it is because they weren't implemented in the first place so are clearly not essential in any meaningful sense.

**Comment by Rubenvdveen** [comment]
test

**Comment by ericwbailey** [comment]
Thanks for the clarification! I've submitted a PR for the issue: https://github.com/w3c/html/pull/1252.

**Comment by siusin** [comment]
Thanks @ericwbailey .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).
