### ISSUE TITLE
No example for bdo element

### ISSUE THREAD

**Issue by programmer3000** [w3c/html#1254]
HTML 5.2 specification have no example for `<bdo>` element https://www.w3.org/TR/html/textlevel-semantics.html#the-bdo-element

**Comment by chaals** [comment]
(@programmer3000 if you are looking for errors in the spec that need fixing, it is probably better to look at the latest editors' draft](https://w3c.github.io/html) - it has numerous corrections compared to HTML 5.2)

**Comment by ericwbailey** [comment]
I'll try taking a crack at this.

**Comment by r12a** [comment]
I'm reopening this because there are some significant issues in my mind with https://github.com/w3c/html/commit/9c6dc8b82fbde7d04b3236f799a5d21099508e05

You shouldn't have both `bdi` and `bdo` in this example because the `dir` attribute provides the isolation and the direction information already. `bdi` is completely redundant and inappropriate here.

Many people, including some famous educators, get confused over the difference between `bdi` and `bdo`, so it's  important imo to make the point that `bdo` is **only for use in very special circumstances**, nearly always for educational text talking about the bidi algorithm when dealing with Arabic and Hebrew, although potentially more useful for Egyptian, Runic and Tiginagh scripts. 

The effect of `bdo` is not just to change the direction, but to rather completely **disable the bidi algorithm**, and then pretty much as an afterthought indicate the direction in which characters should be strung out for display.  In bidi text (as opposed to rtl text) it will reorder chunks of text as well as changing the sequencing on a character by character basis.  It's important to understand this because many people get confused because they assume it is one of the standard tools for ordering characters in normal text. It's definitely not. The current HTML text certainly doesn't make that clear.

Perhaps the example at https://www.w3.org/International/articles/inline-bidi-markup/#override would be helpful?

hth

**Comment by ericwbailey** [comment]
I'm clearly out of my element here, pun not intended. 

@r12a I'm going to bow out if you'd like to flesh out the example properly.

**Comment by shwetank** [comment]
At the risk of falling flat on my face, I'll take this up and have a crack at it. @r12a I might need to contact you to sanity-check the example. Hope thats fine!

**Comment by r12a** [comment]
@shwetank sorry i haven't been able to get to it yet - the 4-day weekend didn't help.  I'm happy to help review your version, thanks.

**Comment by shwetank** [comment]
@r12a Sent a PR here https://github.com/w3c/html/pull/1334 ... a review would be much appreciated. Thanks!
