### ISSUE TITLE
Name attribute of object element should be removed?

### ISSUE THREAD

**Issue by programmer3000** [w3c/html#1306]
What idea uses with `<object>` element `name `attribute?
https://www.w3.org/TR/html/semantics-embedded-content.html#elementdef-object .
How it works with `<object>` element? What made `name` attribute for `<object>` element? Maybe it should be removed for `<object>` element from HTML specification
`<object type="application/x-shockwave-flash" data="enigma_5.swf" width="400" height="400" name="obj1"></object>`

**Comment by chaals** [comment]
This is poorly explained in the specification - and refers to a poorly-written part of the spec.

The idea is that Browsing Contexts - windows, frames, etc - have a name so you can refer to them, e.g. with a `target` attribute on a link.

It would be helpful to explain that a bit more clearly in this context. It would also be useful to test what actually happens when you try to e.g. target a link into an `object`'s browsing context.

**Comment by chaals** [comment]
I did some testing. **In general** this works in Firefox/Vivaldi, but not in Edge - although
the [relevant Edge bug](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11235003/) is marked Fixed - @arronei maybe you want to look at that.

More particularly, [my test]() in Firefox/Vivaldi shows that if the initial `object` is SVG or HTML the `name` attribute creates a browsing context, but if the initial content is a JPEG image it doesn't and instead a new browsing context is created.

That seems to be a bug in those browsers.

cc @ameliabr

**Comment by chaals** [comment]
(Updated test case link: http://chaals.github.io/testcases/object-name-target-manual.html)
