### ISSUE TITLE
clean up descriptions of rel/rev

### ISSUE THREAD

**Issue by chaals** [w3c/html#1335]
This is the editorial part of #1151 

1. Under the section [**Links created by `<a>` and `<area>` elements**](https://w3c.github.io/html/links.html#links-created-by-a-and-area-elements), there is documentation on the `[rev]` content attribute, which applies to `a` and `link`. This is misleading because `link` is not in the section title. Perhaps the title should be changed to “Links created by `<a>`, `<area>`, and `<link>` elements”.
1. The `[rel]` content attribute for `a` and `area` is documented in this same section, but `[rel]` for `link` is documented under its own section: [**The `link` Element**](https://w3c.github.io/html/document-metadata.html#elementdef-link). If the title of the section is changed to include “`<link>`”, perhaps documentation for `link[rel]` should be moved here.

**Comment by chharvey** [comment]
Following up on one more editorial bug:

In the element overview of [§ 4.2.4 The `link` element](https://www.w3.org/TR/html53/document-metadata.html#elementdef-link), the content attribute `rel` links to the WHATWG HTML spec. I believe this is an error, because in the element overview of [§ 4.5.1 The `a` element](https://www.w3.org/TR/html53/textlevel-semantics.html#elementdef-a), the content attributes `rel` and `rev` correctly link to their respective paragraphs in [§ 4.8.2 Links Created by `a`, `area`, and `link` elements](https://www.w3.org/TR/html53/links.html#links-created-by-a-area-and-link-elements).

**Comment by chharvey** [comment]
Following up on one more editorial bug:

In the element overview of [§ 4.2.4 The `link` element](https://www.w3.org/TR/html53/document-metadata.html#elementdef-link), the content attribute `rel` links to the WHATWG HTML spec. I believe this is an error, because in the element overview of [§ 4.5.1 The `a` element](https://www.w3.org/TR/html53/textlevel-semantics.html#elementdef-a), the content attributes `rel` and `rev` correctly link to their respective paragraphs in [§ 4.8.2 Links Created by `a`, `area`, and `link` elements](https://www.w3.org/TR/html53/links.html#links-created-by-a-area-and-link-elements).
