### ISSUE TITLE
allow 'rev' attribute on 'area' element?

### ISSUE THREAD

**Issue by chaals** [w3c/html#1336]
This comes from #1151 - it's the speculative part we might do nothing about.

The `area` element makes a link, and in various ways such as describing link types they are currently treated as equal.

But the `rev` attribute is not currently valid on the element. Unlike `rel` it is not implemented a a reflecting attribute at the moment. 

Unclear if it is processed e.g. by RDFa processors @iherman @gkellogg @msporny?

**Comment by iherman** [comment]
@chaals, RDFa supports the use of `@rev` on any element; the [HTML+RDFa](https://www.w3.org/TR/rdfa-in-html/#additional-rules) spec makes it explicit, without any reference to whether it is valid or not on a specific element. (The area element does not have any specific semantics defined in that document.)

Yes, PyRDFa (the RDFa extension to Python's RDFLib) does process `@rev` regardless of the element it is on. I would expect the implementation of @gkellogg to implements it, too.

**Comment by gkellogg** [comment]
Yes, there are tests for `@rev` in the RDFa test suite, not sure what tag, though. All conforming RDFa processors will handle it.

Given the current Microdata spec, which simply converts Microdata into RDFa, it would work implicitly, aside from the HTML validity issue.

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
