### ISSUE TITLE
Validation of<input> type='date' not conforming to ISO 8601-2 (WD) & not suitable for recording birth dates & incorrect autofill suggestions for 'bday' field

### ISSUE THREAD

**Issue by akehir** [w3c/html#1340]
# Introduction
While implementing a form recording birth dates as written on official passports and similar travel documents, I've stumbled on a small issue with the <input> type='date'.

# Background
The underlying issue is, that the Swiss Government may issue identity cards or passports which do include a birth day of '00' and a birth month of '00', as it has happened with [this example](https://www.swissinfo.ch/eng/red-tape-quirk_when-your-birthdate-lands-you-in-trouble/44023072). The official birth date is actually specified as **00 00 68** on the passport. According to the officials, this practise is based on the [following law](https://www.admin.ch/opc/de/classified-compilation/20092157/index.html#a6),  which was written in conformance to the guidelines of the  International Civil Aviation Organization (ICAO) on Machine Readable Travel Documents. The 7th edition from 2015 is retrievable as [PDF](https://www.icao.int/publications/Documents/9303_p3_cons_en.pdf).

This document, valid for 191 [member states](https://www.icao.int/about-icao/Council/Pages/council-states-2016-2019.aspx) regulates how birth dates may be recorded. While they do not foresee the '00' used by Switzerland, they write the following:

> Unknown date of birth. Where a date of birth is completely unknown, that data element shall appear in the date format used for dates of birth by the issuing State or organization but with Xs representing unknown elements (numbers and/or letters) of the date.
> 
> Examples:
> XXbXXbXX
> XXbXXbXXXX
> XXbXXXbXX where b = a single blank space.
> 
> If only part of the date of birth is unknown, only that part (day, month, year) of the date shall be represented by Xs as per the date format used by the issuing State or organization

As well as using an empty filler character for the machine readable format:

> If all or part of the date of birth is unknown, the relevant character positions shall be completed with filler characters (<).

# Issues with HTML Specification
The HTML specification uses the ISO 8601 standard (2004), upon which [date validation in general](https://www.w3.org/TR/html5/infrastructure.html#valid-date-string), and the [date input in particular](https://www.w3.org/TR/html5/sec-forms.html#element-statedef-input-date) is based. The current standard does not foresee any 'unknown' dates.

Additionally. the recommendations for [Autofill ](https://www.w3.org/TR/html5/sec-forms.html#autofill-field) for 'bday' as well are also based on the incorrect assumption that birth dates are issued in compliance with the ISO 8601 standard from 2014. The recommendation is to use the date input element, and to only allow valid dates. 

Therefore, people with unknown birth days / months will encounter issues when trying to enter their official birth date anywhere in the web, where a input type date is used. In our case, we'd need to opt for a text input field with a custom validation - in the end this defeats having a standardized input field for dates.

A solution might lie in the forthcoming update to the ISO 8601 standard, which does cover the problematic case of unknown date parts.

# ISO 8601-2 Recognizes 'X' as placeholder for unknown dates
In the [ISO 8601-2 (extensions), 2016](https://www.loc.gov/standards/datetime/iso-tc154-wg5_n0039_iso_wd_8601-2_2016-02-16.pdf) draft standard, the use of an 'X' for an unknown date has been adopted:

> 4.3 Unspecified
> The character 'X'	may be used as a replacement character, in place of a digit to indicate that the value of that digit is unspecified.
> 4.3.1 Level 1
> The replacement character ‘X’ may be substituted for the right-most digits in the following cases:
> • Year and month specified, day unspecified.
> • Year specified, day and month unspecified.
> • Entire date unspecified
> Representations with reduced accuracy
> For representations with reduced accuracy,  ‘X’ may be used in the following cases:
> • A year-month, with month unspecified.
> • A year-month, with year and month unspecified.
> • A year with one or two (rightmost) unspecified digits.
> • A year, entire year unspecified. 
> 4.3.2 Level 2
> For level 2 the character ‘X’ may be used as a replacement for any character in the string. 

# Resolution
Preferably, the HTML specification would also allow for 'X' to be used in birth dates, or dates in general. Unfortunately, this will make date validation more complicated, as more than only numbers would be acceptable.

Maybe, date validation needs to distinguish the exact / inexact case, or the birthday case - although exact dates can easily be implemented with regex patterns.

This would not completely remedy the '00' date as issued by Switzerland, as it's not compliant to the new ISO spec. I do not know how many countries have a similar issuing policy.

**Comment by edent** [comment]
It seems to me that there are two distinct problems here.

1. Authors can't indicate "fuzzy" times like `She was born in  <time datetime="195X-01">January in the 1950s</time>`.
2. Users can't input fuzzy dates. If they do, then they won't validate.

On the face of it, this seems like an easy fix for (1).

But for validating input I wonder about the consequences. The `input type="number"` allows `e` and `tel` allows `+*,;`, for example - and that causes confusion and mistakes in validation.

Additionally, I'm not sure how a date dropdown could represent that level of imprecision.  How do you write a date picker which allows form `197X-XX-X1`?

This is a very interesting problem!

**Comment by chaals** [comment]
The implementation probably isn't that complex, it's just a case of adding "unknown" in various parts of the interface, allowing a decade selector (for picking the year of my birth, I would be grateful if every date picker asking for included such a feature as a shortcut to get through the list), adding "x" to the numbers in validation code...

Is there implementation experience? If this is used in travel documents that get presented to real computers at real borders every day then I presume that people have written code that handles it, and if so references to such systems would be helpful.

**Comment by StommePoes** [comment]
It appears this differs per country. Some countries, such as the Netherlands, cannot process 00 or xx. 
https://www.binnenlandsbestuur.nl/bestuur-en-organisatie/nieuws/niet-bestaande-geboortedatum-00-00-jj-blijft.9484714.lynkx
(to fix this, in 2014 it was decided everyone coming to NL as immigrants gets assigned a date of 1 July. Folks assigned a 00 have to just deal with it)
                                                                                   
The UK assigns dates as well: date that identification papers are finalised OR 31 December (for pension collection).
https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/118580/date-and-place-of-birth.pdf
                                                                                   
It seems people entering a country with a 00 or xx get dropped into a fallback, separate, or hand-done section and generally do not go through the "usual" system (especially since airlines generally can't handle 00 or xx and most countries, for immigration purposes, force airlines to force customers to have a date of birth matching on both tickets and passports, or the ticket must use a date on any other paper such as a Naturalisation paper or visa papers).
                                                                                
So, I wonder if a fallback is the better idea here-- that validation does not have to weed through more possibilities, but that a bool/flag can be set stating "there are known unknowns in this date" and use a separate validation (it could be called The Rumsfeld Validation Method)?

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
