### ISSUE TITLE
How I can edit HTML specification and made Pull Request?

### ISSUE THREAD

**Issue by programmer3000** [w3c/html#1373]
Can anyone help me, please? How I can edit HTML specification and made Pull Request? I forked HTML repository. But which of files about full specification?

**Comment by chaals** [comment]
It isn't as easy as we would like it to be.

Basically, the files are in the "sections" folder, and are called [something].include

Usually the .include filename is **related** to the eventual filename in the [HTML editor's draft](https://w3c.github.io/html) but if it isn't please don't change them to make more sense, because there is a script that builds the content which will break if the filenames are not the right ones.

You will see lots of special syntax in there - the spec is written using an augmented markdown. Some of it, including some of the linking syntax is described toward the end of https://github.com/w3c/html/blob/master/docs/contributing-documentation.md

We tried to document some of this in https://github.com/w3c/html/tree/master/docs and in the main file [about contributing](https://github.com/w3c/html/blob/master/CONTRIBUTING.md) but we know that they are not good enough yet.

We would appreciate your comments on specific things you try to do that are not well-documented - feel free to add them to this issue and we will try to answer as we go.

Note that if you want to change something **substantive**, i.e. that changes conformance,, you will need to make a patent commitment - I can help with that, if  you email me (@yandex.ru).
