### ISSUE TITLE
HTML5.3 wide review tracker

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#1415]
* Architecture: Request filed as w3ctag/design-reviews#275
* A11y: [Request sent to APA WG](https://lists.w3.org/Archives/Public/public-html/2018Apr/0023.html) [No issues](https://lists.w3.org/Archives/Public/public-html/2018May/0034.html)
* A11y: [Request sent to ARIA WG](https://lists.w3.org/Archives/Public/public-html/2018Apr/0024.html) [No issues](https://lists.w3.org/Archives/Public/public-html/2018May/0037.html)
* I18n: Request filed as w3c/i18n-activity#534 Issues filed: #1039
* Privacy: [Request sent to Privacy IG](https://lists.w3.org/Archives/Public/public-html/2018Apr/0026.html) Issues filed: #1456 #1457 #1458
* Security: [Request sent to Web Sec IG](https://lists.w3.org/Archives/Public/public-html/2018Apr/0025.html)
* SVG: [Request sent to SVG WG](https://lists.w3.org/Archives/Public/public-html/2018Apr/0027.html)

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).
