### ISSUE TITLE
`input type="number"` misses a `unit`property

### ISSUE THREAD

**Issue by lespacedunmatin** [w3c/html#1417]
I’d like to have to possibility to set a `unit` property on `input type="number"`.

Browsers would be expected to display the specified unit close to the number (perhaps there would need a specific CSS option to specify if the unit should be before or after the figure, like for $10 vs 10€). 

Assistive technologies would be expected to expose the unit to the user, and copy/paste would be expected to copy the number and its unit.

**Comment by prlbr** [comment]
Is there a benefit compared to having the unit symbol outside the `<input>` element other than it being easier to copy number and unit at once?

Do you expect the unit to be included in the transfered data, if a form submitted? In what form?

**Comment by lespacedunmatin** [comment]
> Is there a benefit compared to having the unit symbol outside the `<input>` element

That’s exactly the point : the unit information would be as close as possible from the data and _inside_ the input box, from my point of view it is a better visual clue.

Example: 
<pre>
¥ | 5 | 
</pre>

is not as good to me than

<pre>
| ¥5 |
</pre>

(the bars representing of course the input box)

> Do you expect the unit to be included in the transferred data, if a form submitted?

No, the unit would be used only for display purpose.

**Comment by AurelioDeRosa** [comment]
If it's only about visual, why the current solutions aren't enough? I mean wrapping the `input` inside a `div` and then adjust via CSS.

**Comment by lespacedunmatin** [comment]
Because it’s difficult to adujst the unit position regarding the length of the data inserted into the input and the controls provided by the browser (like the up and down arrows used to increase/decrease the number). And I think it would be better for assistive technologies either (so it’s not only about visual, but also text to voice, and so on).

**Comment by chaals** [comment]
This feels a bit like the `placeholder` attribute (which has its downsides...)

It might be a good candidate to prototype with a customised built-in element.

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
