### ISSUE TITLE
tbody max-height support

### ISSUE THREAD

**Issue by jayh99** [w3c/html#1423]
The tbody element really should support max-height.  This would allow you to create a table with a thead that is always visible as you scroll the tbody.  

```
<table>
<thead>
   <tr>.......</tr>
</thead>
<tbody>
   <tr>.......</tr>
   <tr>.......</tr>
   <tr>.......</tr>
   <tr>.......</tr>
   <tr>.......</tr>
</tbody>
</table>
```

**Comment by chaals** [comment]
Yes it should, that was part of the original purpose of having it as I understand (ping @draggett who was working on it in the 90s when the discussions took place).

As far as I can tell, this is a CSS implementation request - nothing in the HTML specification even suggests that this should not be supported. In which case I think the right path is to close this issue, and open (or more likely comment on existing) browser bugs.

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
