### ISSUE TITLE
Can aria-label render as title attribute (tooltip)?

### ISSUE THREAD

**Issue by devarshipant** [w3c/html#1425]
Something like:

`<input type="text" aria-label="search" set-title="yes">
`

When aria-label is meaningful and benefits sighted keyboard only users, the value of aria-label can be made to appear as the tooltip using the set-title attribute (new).

**Comment by prlbr** [comment]
Is there an advantage compared to setting both the `aria-label` and `title` to the same value as in

```
<input type="text" aria-label="product search" title="product search">
```

**Comment by devarshipant** [comment]
In your example, screen reader (at least JAWS) will speak the aria-label and ignore title as they are same. I don't think that combination (same aria-label and title) is frequently used.

Other use case could be:

`<input type="text" aria-label="product search" title="item 1">`

Where the screen reader output would be **"product search, item 1."**

Which I think could be rewritten as:

`<input type="text" aria-label="product search item 1" set-title="yes / true flag to show aria-label as tooltip">`

**Comment by scottaohara** [comment]
@devarshipant while I agree it's an issue when a UI does not consider all users with visibly identified form controls, I'm wondering what would be the benefit of using this new attribute coupled with `aria-label` over just using the `title` attribute alone to supply the accessible name of the form control? (outside of the fact that not all browsers reveal `title` on focus...but that wouldn't necessarily be solved here?)

`set-title` itself doesn't really indicate that this is a hook specifically for `aria-label`.  Would any accessible name be revealed via tooltip if it was set to yes/true?  And if not, why?

**Comment by devarshipant** [comment]
> I'm wondering what would be the benefit of using this new attribute coupled with aria-label over just using the title attribute alone to supply the accessible name of the form control? 

The purpose is to expose `aria-label `in addition to the `title` attribute as part of tooltip. Often, information given to screen reader users via aria-label is meaningful enough to benefit sighted users, but unavailable to sighted users.

The `set-title` signals the browser or the underlying API to display aria-label as tooltip. 

> set-title itself doesn't really indicate that this is a hook specifically for aria-label. Would any accessible name be revealed via tooltip if it was set to yes/true? And if not, why?

I meant `set-title` to be a global hook to display the accessible name (in this case, using aria-label) as tooltip. It can be extended to include `a`, table elements, `placeholder`, input types, and aria-attributes like `aria-expanded`, `aria-sort`, etc.

**Comment by LJWatson** [comment]
The `title` and `aria-label` attributes are both factors in the [accessible name and/or description computation](https://www.w3.org/TR/2018/CR-accname-1.1-20180619/). Duplicating the same value will either mean the `title` attribute is ignored as part of the accessible name computation, or bumped to being the accessible description, and in either case duplication is a bad thing.

In terms of the tooltip behaviour described, this can already be accomplished by using `title` on its own. Note: this may not be advisable though, because a [tooltip can obscure the original content](https://developer.paciellogroup.com/blog/2010/11/using-the-html-title-attribute/) when triggered by someone using a screen magnifier.

In terms of exposing the accessible name for an element visually, there doesn't seem to be a good use case. If the accessible name needs to be presented visually, there are already mechanisms for doing it - even using CSS to create a tooltip if really desired.
