### ISSUE TITLE
Need clarification on <audio> element support for <track> elements

### ISSUE THREAD

**Issue by OwenEdwards** [w3c/html#1429]
[EDITED to improve clarity] In https://w3c.github.io/html/semantics-embedded-content.html#the-audio-element, the Content model explicitly allows `<track>` elements.

Almost immediately afterward, there is a NOTE:

> In particular, this content is not intended to address accessibility concerns. To make audio content accessible to the deaf or to those with other physical or cognitive disabilities, a variety of features are available. If captions or a sign language video are available, the video element can be used instead of the audio element to play the audio, allowing users to enable the visual alternatives.

Later, in https://w3c.github.io/html/semantics-embedded-content.html#the-media-elements, there is a NOTE:

> Both audio and video elements can be used for both audio and video. The main difference between the two is simply that the audio element has no playback area for visual content (such as video or captions), whereas the video element does.

Putting this together, `<track>`s with `kind="subtitles"`, `kind="captions"` and possibly `kind="descriptions"` are **not** supported in an `<audio>` element - this does not seem to be explicitly called out anywhere in the spec.

It seems _likely_ that `kind="chapters"` would/could be supported for `<audio>` elements (and `kind="metadata"`), but since no UA currently supports chapters or metadata, it's not clear which tracks are **intended** to be supported in `<audio>` elements but **just aren't yet**, and which tracks are **not intended** to be supported based on this spec.

**Comment by LJWatson** [comment]
Ping @ScottAOhara for assistance (video/audio element inaccessibility is hindering my progress).

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
