### ISSUE TITLE
HTML5 media play/pause triggered while seeking playing media

### ISSUE THREAD

**Issue by friday** [w3c/html#1440]
While media is playing, seeking with the browser media controls triggers the events `pause`, then `seeking`, and once complete `seeked`, then `play` again (and likely other events that I didn't listen to).

I have verified this behavior in Firefox and Crome. The `pause` and `play` events being triggered here doesn't seem to be documented, unless it's implied by something else? Should it be documented or is it non-standard?

Replication:
http://jsbin.com/jutiveyefa/edit?console,output

https://dev.w3.org/html5/spec-preview/media-elements.html#mediaevents
https://dev.w3.org/html5/spec-preview/media-elements.html#seeking

Update:
Added replication link and rephrased the initial statement since I got a one important detail wrong.

**Comment by chaals** [comment]
That behaviour makes sense, but isn't documented somewhere obvious enough for me to find it.

I wonder if there are alternatives - e.g. might a player continue playing while it is seeking, and then just jump to the new time when the `seeked` event fires?

**Comment by friday** [comment]
Pausing does make a better seeking user experience here, but I was surprised to see that the actual events were triggered (and the paused property change).

As I read the spec, if `paused` is false, that means it's "potentially playing": It's supposed to play but is temporarily hindered because of not having future data or being "blocked" by the media controller. I think pausing while seeking fits in here better than actually changing the state and triggering the events, since it's a side effect of seeking. The user never intended to "pause" it.

In addition, the play/pause-button always enable the opposite of the current state afaik, except for this case. So custom media controls that intends to follow the spec couldn't use the play/pause-events and paused property alone to determine what option to show.

Maybe I'm not seeing the whole picture though. There's no way for custom media controllers to "block" the media afaik, so this may be the best option.

**Comment by siusin** [comment]
Thanks @friday .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
