### ISSUE TITLE
br should be acceptable as ul child

### ISSUE THREAD

**Issue by Nick-Levinson** [w3c/html#1455]
A list is normally vertical. But if a list item is short enough, the next list item appears on the same line with the short item. This misleads visitors trying to read or skim the list.

To prevent this, after asking around, I found that the solution is to add a br element after the li end tag of the short item (and I add it to after every li end tag). If it's before the end tag, it does not work, or work as well. Therefore, it's best after the end tag. That makes the br element a child of the ul element.

This works in browsers I've checked but fails validation because the spec allows as children of ul only li, script, and template elements.

Please add the br element as a potential child of the ul element.

**Comment by prlbr** [comment]
> A list is normally vertical. But if a list item is short enough, the next list item appears on the same line with the short item.

This is not the standard behaviour in browser that I know. For example, here’s a list without `<br>` and each item on a new line:

1. one
2. two
3. three

It sounds as if you’ve used the CSS `float` property with unintended consequences and/or maybe `display`.

**Comment by scottaohara** [comment]
@Nick-Levinson, I agree with @prlbr.  List items are block level elements and their default layout behavior shouldn't require the need for a `br` element.  

Without more information, I can only assume your `li`s have been modified by CSS to behave as you've described. 

I'm going to leave this issue open to allow you to provide additional information about your issue, but if it truly is caused by your project's CSS, I would suggest you modify your styles to resolve the problem.

**Comment by Nick-Levinson** [comment]
Might it be useful anyway, for situations where an author would use a br element within running text if it weren't inside an li element?

If not, I'll take your consensus. A test file with only the styles assigned by the browser by default produced a vertical list within ul (you did ol) of short (single-digit) list items even without br tags in a Firefox version that's likely more recent than when I had the problem (2-22-16--3-2-16 on my c*.* website). I think I found the pages that likely had the horizontal layout, although it didn't replicate the effect now; in the CSS some li elements were to display as inline-block and were padded and the relevant div element did not have float but did have clear both while other divs had float left or right. I can change those styles but I likely put them in to solve some problems, so to take them out would likely wreak havoc somewhere else. I tried to find where I asked and someone answered that a horizontal layout is normal and doing something about it is up to the author and not HTML, but I couldn't find it; someone else said the br should precede the li end tag but that did nothing, so I have it follow, and it seems okay (it does not create too much space). I'd be interested in applying disinheritance but haven't tried that. It seems one or two other posters have experienced a similar problem with short li even if many don't, so it might be worth allowing br as a descendant of ul anyway.

Either way, thanks.

**Comment by prlbr** [comment]
The `<br>` element, [as it is defined now](https://w3c.github.io/html/textlevel-semantics.html#the-br-element), is not supposed to fix styling issues. That would be an [abuse](https://w3c.github.io/html/textlevel-semantics.html#example-1ca3dae0) of the element. The semantcis of the `<br>` element would need to be changed first before allowing it as a child of `<ul>`/`<ol>`. But I don’t think that a need has been demonstrated.

> in the CSS some li elements were to display as inline-block

That is most probably why you got the horizontal layout. The [default](https://www.w3.org/TR/html5/rendering.html#section-lists) browser setting is `display:list-item`. `inline-block` is fine if you want a horizontal layout. I use it deliberately on `<li>`s for a horizontal navigation on my website.

**Comment by scottaohara** [comment]
@Nick-Levinson since this is an issue with styling, CSS should be used again to solve the problem.

I made [a quick codepen](https://codepen.io/scottohara/pen/KROrRM) to show how using either pseudo elements or setting the `li`'s width to 100% could potentially be of use to you.

If this issue is caused by a global style having unintended consequences on other lists, then you might want to consider revising the selector that's causing this issue, to only target the elements you want this horizontal list item effect on.  

Good luck!
