### ISSUE TITLE
Update 7.8 Images

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#1477]
The WHATWG recently [rewrote CreateImageBitmap](https://github.com/whatwg/html/commit/5b40420b83dad83e5e566de9581dc51e4e4ee6cd
) in [section 8.8 Images](https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#images-2). We should review against [section 7.8 Images](http://w3c.github.io/html/webappapis.html#webappapis-images).

**Comment by scottaohara** [comment]
assigning to myself to review

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).
