### ISSUE TITLE
browsers don't implement kind=chapters well

### ISSUE THREAD

**Issue by chaals** [w3c/html#1478]
see also https://github.com/w3c/webvtt/issues/344

Chapters are important to navigate audio, and are reportedly implemented by many javascript media players, but not natively in browsers.

At least some players rely on browsers providing the `track.kind == chapters`.

My thinking is we should note the implementation state, and in particular point out that **native** browser media players don't do this, so authors should not rely on them if they are using chapters.

**Comment by siusin** [comment]
Thanks @chaals .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
