### ISSUE TITLE
Review Following Hyperlinks

### ISSUE THREAD

**Issue by scottaohara** [w3c/html#1482]
Review the differences between [WHATWG Following Hyperlinks](https://html.spec.whatwg.org/#following-hyperlinks) and [W3C Following Hyperlinks](http://w3c.github.io/html/single-page.html#follow-hyperlinks) to determine if we would like to similarly trim down the steps

**Comment by patricia-gallardo** [comment]
It seems that the simplification is based around defining concepts:
* what "cannot navigate" means
* what is a "node document"
* what is a "targetAttributeValue"
* how to "get an element's target given subject"
etc
I'm not sure either text is very readable - do you have any pointers with regards to which direction we want to go? If some of these terms are defined elsewhere, then repeating them here is probably not very useful?

**Comment by patricia-gallardo** [comment]
I'm still working out what differences exist in semantics, but I do believe there is a typo in our version:
"Otherwise, if **target** is an a or area element with no target attribute"

If I'm not mistaken this should be:

"Otherwise, if **subject** is an a or area element with no target attribute"

**Comment by patricia-gallardo** [comment]
The typo is adressed in this pull request https://github.com/w3c/html/pull/1635

**Comment by patricia-gallardo** [comment]
Other notes:

The section linked to in the whatwg step number 7 seems quite more involved than step 3 in the w3c version: 
https://html.spec.whatwg.org/#the-rules-for-choosing-a-browsing-context-given-a-browsing-context-name

Especially it seems that the w3c version does not talk about the impact of noopener wrt choosing the target

**Comment by patricia-gallardo** [comment]
The similar section in the w3c version seems to be 
http://w3c.github.io/html/single-page.html#the-rules-for-choosing-a-browsing-context

**Comment by patricia-gallardo** [comment]
High level the differences are:
whatwg has added a step before the ones in the w3c section: 
"1. If subject cannot navigate, then return."

Further they have split step 3 in the w3c version, into five steps (steps 4 to 8) in the whatwg version.
A part of this difference is that they refer to the section about choosing the browsing context instead of trying to write out the steps.

We could probably do these changes as well (or similar ones), since step 3 is quite long and repetitious, and might be missing some nuance.

**Comment by patricia-gallardo** [comment]
Relevant whatwg issues
https://github.com/whatwg/html/issues/2619
https://github.com/whatwg/html/issues/2615 
https://github.com/whatwg/html/issues/2708
https://github.com/whatwg/html/issues/2681

specifically (at least) these commits: 

https://github.com/whatwg/html/commit/d22a9f12e1cc13a77504fa6482b7ded6ba790b54
https://github.com/whatwg/html/commit/a68a1f712b641981d7367d78758596b21a04521c
https://github.com/whatwg/html/commit/0b31844d6dcc7ef49b3815f4f709d4c0284378f1
https://github.com/whatwg/html/commit/f3c354add894e1ac01e3732ff976aa9874a77b3f
https://github.com/whatwg/html/commit/055e6b757a94bc1b77d4e07383bc8f0699005e32

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
