### ISSUE TITLE
Bikeshed: CSS for popout sidebar is broken

### ISSUE THREAD

**Issue by scottaohara** [w3c/html#1495]
Not sure what might have caused this, but noticed that the CSS for the pop out sidebar table of contents was broken today.

![screen shot of pop out sidebar with large gap between section numbers and section text pushed over to the right of the TOC](https://user-images.githubusercontent.com/4152514/42129591-2c81a554-7c97-11e8-90e6-1c668b400800.jpg)

**Comment by chaals** [comment]
Did it come from updating the bikeshed version @siusin

**Comment by siusin** [comment]
It seems to be a common problem for all the specs using bikeshed...

@deniak any suggestions?

**Comment by deniak** [comment]
The issue comes from the following inline css:
```
#toc ol,
#toc li,
#toc a {
  display: contents;
  /* Switch <a> to subgrid when supported */
}
```

Removing that rule fixes the TOC so it's likely a bug with CSS introduced by bikeshed.

**Comment by scottaohara** [comment]
FYI @siusin, it looks like this issue has been fixed for the index file of the spec, but going to a sub page, e.g. http://w3c.github.io/html/semantics-embedded-content.html#the-track-element, the CSS issue still exists.

**Comment by siusin** [comment]
Weird... I'll look into this. Thanks @scottaohara .

**Comment by scottaohara** [comment]
Note, `display: contents` is also the culprit for why the TOC has become inaccessible.

[Issue filed with Bikeshed, 1316](https://github.com/tabatkins/bikeshed/issues/1316)

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
