### ISSUE TITLE
more detaily : <meta> element within <noscript> element that is a child of <head> element.

### ISSUE THREAD

**Issue by mtrootyy** [w3c/html#1496]
https://w3c.github.io/html/semantics-scripting.html#the-noscript-element
> Content model:
> - When scripting is disabled, in a head element: in any order, zero or more link elements, zero or more style elements, and zero or more meta elements. 
> - When scripting is disabled, not in a head element: transparent, but there must be no noscript element descendants. 
> - Otherwise: text that conforms to the requirements given in the prose.

https://w3c.github.io/html/document-metadata.html#the-meta-element
> Contexts in which this element can be used:
> - If the charset attribute is present, or if the element’s http-equiv attribute is in the encoding declaration state: in a head element. 
> - If the http-equiv attribute is present but not in the encoding declaration state: in a head element. 
> - If the http-equiv attribute is present but not in the encoding declaration state: in a noscript element that is a child of a head element. 
> - If the name attribute is present: where metadata content is expected. 

"Contexts in which this element can be used:" of `<meta>` element is not altogether to allow everything of `<meta>` element in `<noscript>` element that is a child of `<head>` element.

But it should be specyfied in "Content model:", because "Contexts in which this element can be used:" is "non-normative"(Ref: https://w3c.github.io/html/dom.html#element-definitions).

Threfore, sentence of "zero or more meta elements" of "Content model:" of `<noscript>` element should be described more detaily in accordance with content of "Contexts in which this element can be used:" of `<meta>` element.

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
