### ISSUE TITLE
add description of when border attribute value is "0"

### ISSUE THREAD

**Issue by mtrootyy** [w3c/html#1497]
`border` attribute value on `table` element.
https://w3c.github.io/html/tabular-data.html#element-attrdef-htmltableelement-border
> If a value other than the empty string, or "1" is set, such as a text string, user agents should interpret the value as the empty string.

  ↓
Therefore, if the `border` attribute value is setted to "0", user agents should interpret the value as the empty string.

https://w3c.github.io/html/rendering.html#tables
> table[border] { border-style: outset; } /* only if border is not equivalent to zero */

> table[border] > tr > td, table[border] > tr > th,
> table[border] > thead > tr > td, table[border] > thead > tr > th,
> table[border] > tbody > tr > td, table[border] > tbody > tr > th,
> table[border] > tfoot > tr > td, table[border] > tfoot > tr > th {
>    /* only if border is not equivalent to zero */
>    border-width: 1px;
>    border-style: inset;
> }

  ↓
If user agents interpret "0" of the `border` attribute value as the empty string, requirement of "only if border is not equivalent to zero" is satisfied.
Therefore, user agents will drawn borders around cells of the table, even though the `border` attribute value is setted to "0".
The above is strange.

Therefore, description of when `border` attribute value is "0" should be add to "https://w3c.github.io/html/tabular-data.html#element-attrdef-htmltableelement-border".

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
