### ISSUE TITLE
Additional cleanup for link element

### ISSUE THREAD

**Issue by scottaohara** [w3c/html#1506]
Consider [removal of `serviceworker`, addition of `manifest`](https://github.com/w3c/html/issues/1392#issuecomment-392572257), as well as [removal of `pingback`](https://github.com/w3c/html/pull/1467#pullrequestreview-130037492)

**Comment by Malvoz** [comment]
@siusin 
Is the `manifest` link relation ready to have its place in the spec yet? 😉 
(I thought I'd read through the contributing docs for guidelines because I'd like to help on this, but I realized you're assigned.)

**Comment by siusin** [comment]
@Malvoz 
W3C is [exploring effective partnership mechanisms for HTML and DOM](https://www.w3.org/2019/04/w3c-highlights/#html) with the WHATWG. Could you try contributing your thoughts to the [WHATWG/html](https://github.com/whatwg/html/) repo instead? Please let us know if any questions or problems while doing so.

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
