### ISSUE TITLE
fix "Contexts in which this element can be used:" of <img> element

### ISSUE THREAD

**Issue by mtrootyy** [w3c/html#1507]
http://w3c.github.io/html/semantics-embedded-content.html#elementdef-img
> Contexts in which this element can be used:
> - Where embedded content is expected.

　↓

The above should be fixed following:
> Contexts in which this element can be used:
> - Where embedded content is expected.
> - As the last element in a picture element.

**Comment by mtrootyy** [comment]
Ref: https://w3c.github.io/html/semantics-embedded-content.html#the-picture-element
> Content model:
> - Zero or more source elements, followed by one **img** element, optionally intermixed with script-supporting elements.

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
