### ISSUE TITLE
<dialog> element should send focus back to the element that opened it when it is closed

### ISSUE THREAD

**Issue by Dan503** [w3c/html#1515]
In the W3C Accessibility guidelines on how to make accessible dialog elements, it specifically says to send focus back to the element that activated it unless the element doesn't exist or it makes more sense to send the focus elsewhere.

> When a dialog closes, **focus returns to the element that invoked the dialog** unless either:
> - The invoking element no longer exists. Then, focus is set on another element that provides logical work flow.
> - The work flow design includes the following conditions that can occasionally make focusing a different element a more logical choice:
>     1. It is very unlikely users need to immediately re-invoke the dialog.
>     2. The task completed in the dialog is directly related to a subsequent step in the work flow.
>
>         For example, a grid has an associated toolbar with a button for adding rows. The Add Rows button opens a dialog that prompts for the number of rows. After the dialog closes, focus is placed in the first cell of the first new row.
>
> https://www.w3.org/TR/wai-aria-practices/#dialog_modal

I was looking at the [official dialog element polyfill](https://github.com/GoogleChrome/dialog-polyfill) made by the Google Chrome team and in their documentation they point out that the `<dialog>` element spec has not been written to include that functionality in it.

> The WAI-ARIA doc suggests returning focus to the previously focused element after a modal dialog is closed. However, **this is not part of the dialog spec itself.**
>
> https://github.com/GoogleChrome/dialog-polyfill#focus

That makes me wonder, why not?

The `<dialog>` element should be as accessible as possible by default but by excluding this functionality from the spec it is not as accessible as it should be.

I think that, by default when the dialog closes, it should send focus back to the element that activated it. If that element doesn't exist then focus should be sent back to the document at large (or whatever the default functionality is currently). We can't really automate figuring out what the most appropriate element to send focus to is if the original element doesn't exist.

This functionality needs to be easily over-writable by authors so that they can more easily handle the edge case scenarios mentioned in the accessibility guidelines. I'm thinking that an `event.preventDefault()` on the `dialog.close()` event would make sense for this purpose.

Dialog element specs:
https://w3c.github.io/html/interactive-elements.html#the-dialog-element
https://w3c.github.io/html/editing.html#focusing-steps

**Comment by siusin** [comment]
Thanks @Dan503 .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
