### ISSUE TITLE
typo in autocomplete

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/html#1519]
Number 17 says "indexth"

![image](https://user-images.githubusercontent.com/2365411/42842676-d940cddc-89db-11e8-8f7f-4dedc6f58639.png)

https://www.w3.org/TR/html53/sec-forms.html#autofilling-form-controls-the-autocomplete-attribute

this is in 5.2 also
https://www.w3.org/TR/html52/sec-forms.html#autofill-processing-model

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
