### ISSUE TITLE
Native video controls

### ISSUE THREAD

**Issue by FPChris** [w3c/html#1521]
There needs to be better options for native video controls. Google for example keeps
changing the native controls in Chrome (look and behavior) and as a result
previous client products are effected without a fallback option. 

Example. We have medical scans in MP4. Doctors can stop the video and
frame advance via the arrow keys. The controls used to be on all the time
at the bottom of the video. Then they went to fading them on mouse
movement. Not a big deal but not ideal. Then then went to sticking a
giant PLAY button in the middle of the video when paused.
That leaves a doctor unable to see the entire image. Which they need to do.
It's even worse in full screen mode.

I'm sure it is all an effort to make the controls more tablet friendly
while making the desktop suffer.

Maybe ?...
controls:desktop
controls:version1

**Comment by chaals** [comment]
On Thu, 19 Jul 2018 21:25:27 +0200, FPChris <notifications@github.com>  
wrote:

>
> There needs to be better options for native video controls. Google for  
> example keeps
>
> changing the native controls in Chrome (look and behavior) and as a  
> result
>
> previous client products are effected without a fallback option.
>
>
>
> Example [...]
>

This seems like implementation bugs better filed against the players that  
are problematic.

However, it might be worth providing some informative implementation  
guidance in the spec.

-- 
Chaals: Charles (McCathie) Nevile    find more at https://yandex.com
Using Opera's long-abandoned mail client: http://www.opera.com/mail/
Is there really still nothing better?

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
