### ISSUE TITLE
Recursion in paragraph specification

### ISSUE THREAD

**Issue by Chealer** [w3c/html#1590]
The specification is unclear about what paragraphs are. In particular, section 4.4.1. "The p element" defers to 3.2.4.4 to define what a paragraph is. But 3.2.4.4 defines 2 types of paragraphs:

1. A lengthy definition not based on the `<p>` element ("Let view be a view of the DOM that replaces all...").
1. "A paragraph is also formed explicitly by p elements.", which defers to section 4.4.1.

So 4.4.1 defers to 3.2.4.4, which partially defers to 4.4.1. Effectively, this states that some things are paragraphs, but fails to define what is not a paragraph.

Note that section 3.2.4.4. "Paragraphs" has several self-links (3 in the first note, 1 in "A paragraph is also formed explicitly by p elements.").

**Comment by siusin** [comment]
Thanks @Chealer .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
