### ISSUE TITLE
ping attribute of <a> and <area> must be ommitted, if the href attribute is not present

### ISSUE THREAD

**Issue by mtrootyy** [w3c/html#1592]
https://w3c.github.io/html/textlevel-semantics.html#the-a-element
> The target, download, rel, rev, hreflang, type, and referrerpolicy attributes must be omitted if the href attribute is not present.

↓
The above should be fixed following;
> The target, download, **ping,** rel, rev, hreflang, type, and referrerpolicy attributes must be omitted if the href attribute is not present.

https://w3c.github.io/html/semantics-embedded-content.html#the-area-element
> The target, download, rel, hreflang, type, and referrerpolicy attributes must be omitted if the href attribute is not present.

↓
The above should be fixed following;
> The target, download, **ping,** rel, hreflang, type, and referrerpolicy attributes must be omitted if the href attribute is not present.

Ref: https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element
Ref: https://html.spec.whatwg.org/multipage/image-maps.html#the-area-element

**Comment by siusin** [comment]
Thanks @mtrootyy .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
