### ISSUE TITLE
fix "Contexts in which this element can be used:" of <header> and <footer> element

### ISSUE THREAD

**Issue by mtrootyy** [w3c/html#1596]
https://w3c.github.io/html/sections.html#the-header-element
> Contexts in which this element can be used:
> - Where flow content is expected.

↓
The above should be fixed following;
> Contexts in which this element can be used:
> - Where flow content is expected, **but with no address, dt, or th element ancestors, or header, footer elements that are not ancestors of sectioning content which is a ancestors of the header**.

https://w3c.github.io/html/sections.html#the-footer-element
> Contexts in which this element can be used:
> - Where flow content is expected.

↓
The above should be fixed following;
> Contexts in which this element can be used:
> - Where flow content is expected, **but with no address, dt, or th element ancestors, or header, footer elements that are not ancestors of sectioning content which is a ancestors of the footer**.

　
　
　
Ref: https://w3c.github.io/html/grouping-content.html#the-address-element
> Content model:
> - Flow content, but with no heading content descendants, no sectioning content descendants, and no main, **header, footer**, or address element descendants.

Ref: https://w3c.github.io/html/grouping-content.html#the-dt-element
> Content model:
> - Flow content, but with no **header, footer**, sectioning content, or heading content descendants.

Ref: https://w3c.github.io/html/tabular-data.html#the-th-element
> Content model:
> - Flow content, but with no **header, footer**, main, sectioning content, or heading content descendants.

Ref: https://w3c.github.io/html/sections.html#the-header-element
> Content model:
> - Flow content, but with no main element descendants, or **header, footer elements that are not descendants of sectioning content which is a descendant of the header**.

Ref: https://w3c.github.io/html/sections.html#the-footer-element
> Content model:
> - Flow content, but with no main element descendants, or **header, footer elements that are not descendants of sectioning content which is a descendant of the footer**.

**Comment by carolgilabert** [comment]
I can look into this 🙋‍♀️

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
