### ISSUE TITLE
Document differences with whatwg spec

### ISSUE THREAD

**Issue by chaals** [w3c/html#1599]
We should have documentation of the explicit / deliberate differences between the specs, such as the fact that W3C publishes Web Workers separately, we don't include  `accessKeyLabel` because there has only ever been one implementation, or we recommend against using nested `h1` elements in the pattern

```
<section><h1>principal title</h1>
 ...
 <section><h1>nested second-level title</h1>
 <p>A screenreader will have the heading presented as a level 1 heading. In modern browsers it will *look* visually like a level 2 heading by default, but older browsers and some stylesheets will make it look like a level 1 heading
 </section>
 <section><h1>nested second-level title</h1>
 <p>That's why we don't recommend doing this.
 </section>
```

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
