### ISSUE TITLE
Clarify <input type="file"> change event behavior

### ISSUE THREAD

**Issue by SebastianZ** [w3c/html#1610]
Similar to #194 there are some discrepancies between browsers when to trigger the [change](url) event on `<input type="file">` elements.

The spec. [allows to set the `files` attribute dynamically](https://html.spec.whatwg.org/multipage/input.html#dom-input-files). Currently it does not say to trigger the `change` event in this case.

Though browsers disagree on whether to trigger an event in this case. Chrome, Opera and Safari do trigger it, Firefox and Edge don't.

Here's an example:
https://jsfiddle.net/SebastianZ/fyLkp91u/

At the first sight, it may be correct to trigger the event, because the value of the element changes. On the other hand, changing the value of another input type dynamically, doesn't trigger a `change` event either.

For comparison, an `<input type="text">` example:
https://jsfiddle.net/SebastianZ/1jmqa06r/

So, what should be done in this case?

Sebastian

**Comment by siusin** [comment]
Thanks @SebastianZ .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
