### ISSUE TITLE
Drop requirement for li "value" attribute's value to be a "valid integer"

### ISSUE THREAD

**Issue by amingilani** [w3c/html#1612]
The current draft of HTML 5.3 contains the following line:

>The value attribute, if present, must be a valid integer giving the ordinal value of the list item.
> &mdash; https://www.w3.org/TR/html53/grouping-content.html#element-attrdef-li-value

I propose that this requirement be dropped and any valid string be accepted by the `value` attribute and be rendered as the 

## Why

This requirement hinders the ability for legal text to be semantically marked in HTML. If a body of legal text contains multiple clauses, and a legislative amendment is passed to insert a clause in the middle of the clauses, it must be added in a backward compatible manner.

Usually, this is done by appending a letter from a counter based on a different character-class at the end of the count of the preceding clause, e.g. "2A" between "2", and "3".

This ensures that text that cites clause "3" remains valid since clause "3" remains unaltered.

## Example

The Constitution of Pakistan originally contained the following articles:

>2	Islam to be State religion
>Islam shall be the State religion of Pakistan.
> 
>3	Elimination of exploitation
>The State shall ensure the elimination of all forms of exploitation and the gradual fulfillment of the fundamental principle, from each according to his ability to each according to his work.

On 2nd March 1985, another article was inserted between these two, titled "2A":

>2	Islam to be State religion
>Islam shall be the State religion of Pakistan.
>
>2A	The Objectives Resolution to form part of substantive provisions.
>The principles and provisions set out in the Objectives Resolution reproduced in the Annex are hereby made substantive part of the Constitution and shall have effect accordingly.
>
>3	Elimination of exploitation
>The State shall ensure the elimination of all forms of exploitation and the gradual fulfillment of the fundamental principle, from each according to his ability to each according to his work.

This method of calling it article 2A ensured that all previous works citing article 3 remained valid.

## Furthermore

Since the `value` attribute essentially resets the `li` counter and starts from the beginning, I propose that this behavior is left unchanged for any _valid integer_ values passed to the `value` attribute.

**Comment by siusin** [comment]
Thanks @amingilani .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
