### ISSUE TITLE
Suggested parameters for element.focus() function

### ISSUE THREAD

**Issue by ColBoogie** [w3c/html#1621]
Not all browsers treat .focus the same, and I suggest two parameters that makes programming more browser independent.
Currently there are 2 ways that I have seen focus() implemented
1) If element after current screen display, the screen scrolls down until the first line of the element (or image) is on the bottom of the screen. If element before current screen display, the screen scrolls up until the first line of the element (or image) is on the top of the screen. If the element is already on the screen, the screen stays the same (unless CSS changes appearance with change of focus).
2) The first line of the element is put in the middle of the screen. Sometimes this will force document to top or bottom of document.

Suggested parameters (focus_V, focus_H)
Focus_V could have the following suggested values
1: Top, the first line of the element becomes to top line on the screen. If not enough document left to fill out the screen, this becomes the same as scrolling to the bottom of the document.
2: Bottom, the last line of the element becomes to last line on the screen. If not enough document left to fill out the screen, this becomes the same as scrolling to top of the document. If element exceeds size of screen, this becomes the same as Top.
3: Middle: Same as second way browsers do things above.
4: ##%, 0% same as top, 100% same as bottom, 50% same as middle, other relative percentages is how far from top to bottom of screen to start element (rounded down).
Focus_H =could have similar parameters: Right, Left, Center, ##% when current document width exceeds the screen width.
Note: You could have a default values of .focus(Top, Left) or let browser decide.

**Comment by siusin** [comment]
Thanks @ColBoogie .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
