### ISSUE TITLE
Fix "Content attributes:" of Autonomous custom elements

### ISSUE THREAD

**Issue by mtrootyy** [w3c/html#1622]
https://w3c.github.io/html/semantics-scripting.html#sec-autonomous-custom-elements
> Content attributes:
> - Global attributes, except the is attribute

　↓
The above should be fixed following;
> Content attributes:
> - Global attributes, except the is attribute
> - Any other attribute that has no namespace, as determined by the element's author, so long as the attribute name is XML-compatible and contains no ASCII upper alphas.

Ref: https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-core-concepts:autonomous-custom-element

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
