### ISSUE TITLE
Link preview popup API

### ISSUE THREAD

**Issue by Voronar** [w3c/html#1634]
Hello.
According to very useful [page preview](https://medium.com/freely-sharing-the-sum-of-all-knowledge/how-we-designed-page-previews-for-wikipedia-and-what-could-be-done-with-them-in-the-future-7a5fa6b07b96) feature from Wikipedia, it would be a great possibility to make the page preview popup for any web site via HTML link additional proposed API.
Is it technically possible and are there some security restrictions for this functionality?

**Comment by chaals** [comment]
It is technically possible, but it relies more on browser implementation. There are approaches like "AMP" which rely on this being done through the Web rather than being a browser feature. There are many bad things about that approach, number one being about the general concern raised by preview/prefetching, of centralising data that has serious privacy issues...

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
