### ISSUE TITLE
The "valid e-mail address" definition doesn't accept IPv6 emails

### ISSUE THREAD

**Issue by mgol** [w3c/html#1638]
The "valid e-mail address" definition in the spec:
https://html.spec.whatwg.org/#valid-e-mail-address
doesn't accept emails with an IPv6 host like `xyz@[IPv6:2001::1]`. E-mails like that are defined in "RFC 5321 (SMTP)" in section 4.1.3:
https://tools.ietf.org/html/rfc5321#section-4.1.3
We've got an issue in AngularJS about not supporting such e-mails:
https://github.com/angular/angular.js/issues/16599
and I noticed the HTML standard doesn't do that either. Is it a conscious decision? If yes, what are the reasons?

I searched the issues & PRs but the word "IPv6" doesn't return any results.

**Comment by chaals** [comment]
The HTML specification changed in January to reference RFC 6531 which means more or less anything with an '@' sign in the middle should be valid. Your reference is to the WHATWG spec and I don't know why they seem uninterested in supporting modern email addresses.

If I misunderstood the RFC and we still don't support IPv6 addresses that was an oversight and we should fix it. Otherwise, I think this issue can be closed...

**Comment by mgol** [comment]
Forgive me, I filed it under a wrong repo! I’ll re-check with WHATWG...

Thank you for your time.

**Comment by mgol** [comment]
Submitted to WHATWG HTML as https://github.com/whatwg/html/issues/4089.
