### ISSUE TITLE
Incorrect fragment case marking for body-template-body

### ISSUE THREAD

**Issue by peteroupc** [w3c/html#1646]
The HTML 5.2 spec. states:

> ***The "in-body" insertion mode***
>
> [...]
>
> **A start tag whose tag name is "body"**
>
> [...]
>
> If the second element on the stack of open elements is not a `<body>` element, if the stack of open elements has only one node on it, or if there is a `<template>` element on the stack of open elements, then ignore the token. (fragment case)
>
> [...]

This entire step is marked as "fragment case"; however, it's possible to reach this step on an HTML document (not fragment) like the following:

    <body foo=x><template><div></div><body bar=y>

This is similar to one of the html5lib test cases and has different behavior depending on whether the step is implemented or not.

That step should be changed to the following:

> If there is a `<template>` element on the stack of open elements, then ignore the token.
>
> If the second element on the stack of open elements is not a `<body>` element or if the stack of open elements has only one node on it, then ignore the token. (fragment case)

**Comment by siusin** [comment]
Thanks @peteroupc .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
