### ISSUE TITLE
future:javascript add gpio api

### ISSUE THREAD

**Issue by annopnod** [w3c/html#1664]
add general-purpose input/output (GPIO) function
var gp=new GPIO();
gp.setpin(value);//set pin input or output
gp.read(value); // read byte count of gpio
gp.write(value);// write data to gpio

**Comment by siusin** [comment]
Thanks @annopnod .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
