### ISSUE TITLE
dialog element - closing when clicking outside

### ISSUE THREAD

**Issue by o-t-w** [w3c/html#1667]
It is overwhelmingly common question on Stack Overflow. Its something that is often not implemented well (see [_The Dangers of Stopping Event Propogation_](https://css-tricks.com/dangers-stopping-event-propagation/ ))
This popular [blog post](https://keithjgrant.com/posts/2018/01/meet-the-new-dialog-element/) documents one _far from perfect_ method of closing the `<dialog>` by clicking outside. 
Could we please get an easy way to do this?

**Comment by OmidHekayati** [comment]
As it proposed in #860 I also think `<dialog>` must have a modal bool attribute `<dialog modal>` for these reasons:
- closing when clicking outside dialog
- style scrim behind the dialog like dark or blur behind modal dialog!
- ...

**Comment by siusin** [comment]
Thanks @o-t-w and @OmidHekayati .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
