### ISSUE TITLE
Audio element doesn't accept URL in the src attribute

### ISSUE THREAD

**Issue by Mcgurk-Adam** [w3c/html#1670]
I posted a question on Stack Overflow that I think is better suited for here. Here is the link to the question: https://stackoverflow.com/questions/53974730/html5-audio-element-closing-connection-when-passing-url-as-src

The tl;dr is that the HTTP connection is being closed or refused when I pass a URL to the SRC attribute. The question is, can the <audio> element stream directly from a URL?

**Comment by chaals** [comment]
Answered in stack overflow. I don't think there is anything in the spec that stops you using a stream, and it is clearly intended that it can work. But it might not in a given case, e.g. because the stream times out or the user agent doesn't recognise the particular format....

I'll close for now, but if there is indeed something in the spec that causes a problem, please re-open.
