### ISSUE TITLE
Preformatted `<pre>` tags should ignore tabs and spaces outside its tab-order

### ISSUE THREAD

**Issue by calebpitan** [w3c/html#1675]
HTML looks ugly sometimes when we write codes in &lt;pre&gt; tags. The next line has to start from the leftmost end or all the spaces or tabs would be included.  
This is what I'm trying to say:  
(assume the dots to be spaces)  
```
........<pre>
<p>Hello Programmers</p></pre>
```
When it could look beautiful if it were like this:  
```
........<pre>
........<p>Hello Programmers</p></pre> 
```

Relative to the previous tab order. Where all other spaces before &lt; won't be rendered, since it has the same tab order with the &lt;pre&gt; tag.
That is; if the next line in the &lt;pre&gt; tag is 2 spaces more than those before the tag, only the two spaces would be rendered and not six.

**Comment by chaals** [comment]
That might be nice, but would be pretty complex to specify and implement, for something that is pretty much an edge case.

I would prefer to see `<code>` triggering more intelligent rendering in general for code samples. There are now a lot of auto-formatters for code, enabling people to see many language in a style that they find most readable...

**Comment by calebpitan** [comment]
Yeah the code tag would be better for code samples if it can be well enhanced for the purpose, so we can leave the pre tag to what its most suited for.

**Comment by siusin** [comment]
Thanks @calebpitan .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
