### ISSUE TITLE
Some rel attributes are linked to WHATWG HTML, not W3C

### ISSUE THREAD

**Issue by bangseongbeom** [w3c/html#1678]
In <https://w3c.github.io/html/links.html> (and other sections) some `rel` attributes are linked to [WHATWG HTML's `rel`](https://html.spec.whatwg.org/multipage/semantics.html#attr-link-rel), not [W3C HTML's `rel`](https://w3c.github.io/html/links.html#element-attrdef-a-rel).

I found in `sections/semantics-links.include` that **`<{links/rel}>`** works well, but **`<{link/rel}>`** is linked to WHATWG.

**Comment by siusin** [comment]
Thanks @bangseongbeom .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
