### ISSUE TITLE
Example for bread crumb navigation might need to be revamped

### ISSUE THREAD

**Issue by ianthedev** [w3c/html#1686]
The recommended markup for bread crumb navigation [is using unordered list (`<ul>`)](https://www.w3.org/TR/html51/common-idioms-without-dedicated-elements.html#bread-crumb-navigation).

In my opinion, bread crumb navigation is a **trail**, not a list. It's similar to a **series of marks on a map**. So the current use of unordered list is not a good approach, in my humble opinion.

Also, the use of unordered list implies that the order of items is not important, while it is.

So I humbly suggest that the recommended markup be looked into. Thanks.

**Comment by iandevlin** [comment]
I agree, the order here matters a lot.

**Comment by Malvoz** [comment]
The implicit ARIA role of [`list`](https://www.w3.org/TR/wai-aria-1.1/#list) in e.g. `<ul>`, `<ol>` is highly valuable to visually impaired users. It conveys that it is a list, and screen readers usually announce the amount of list-items within that list which I can only imagine is really helpful - as a sighted user I can quickly get an overview of how many items are available to me within an element group. 

Personally, I'd say `<ol>` is the optimal markup because the order of items in a bread crumb nav is relevant.

**Comment by siusin** [comment]
Thanks @ianthedev .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
