### ISSUE TITLE
Proposal: <button once="true" /> attribute

### ISSUE THREAD

**Issue by NickCraver** [w3c/html#1692]
A common case I've seen many hundreds of times across the years is: clicking a `<button>` should disable it. This is usually due to an HTTP request (or some other operation) that's kicked off. Clicking twice is *usually* an error.

I propose something to more easily handle this case:
```html
<button once="true">Foo</button>
```
This would be equivalent to:
```html
<button onclick="this.disabled = true;">Foo</button>
```

As a bonus, we could consider a CSS addition along the lines of:
```css
button:loading { // ...or button:disabled:loading perhaps?
  // spinny thing, but no seizures please!
}
```
<sub>(maybe that naming is terrible, but the idea is what I want to convey)</sub>

I'd love to have something like this. We could save so much JavaScript written and cases where it's not written continually caught and addressed. The user would only need to *re-enable* the button when the operation completes and it's valid to do so...the same thing they need to do today, no net change on the tail end.

In the non-JavaScript case...things just work. With no JS in play, we're in a full form submission/reload scenario, so this just lets you not even use JavaScript to protect the simple case. To me, this may be the strongest argument for such an attribute.

When building apps, I'd even go so far as to validate it (in our tooling). Having an attribute makes that easy to reason about and check for. A sea of JavaScript and possibly-attached handlers isn't, though to be fair inline we could check for.

Thoughts?

**Comment by gaui** [comment]
`EventTarget.addEventListener()` already has the option: `once: boolean` so this makes total sense. Only question I have, what when you need to retry, e.g. the action/request wasn't successful?

**Comment by NickCraver** [comment]
@gaui I think a retry would happen via JavaScript as it would be today. If we have no JS, this is a full page load in which case state is reset already. If we are submitting via JavaScript, then we handle whatever response in whatever way there.

**Comment by iandevlin** [comment]
Nice idea, I would make `once` (or `disableonclick`) a Boolean attribute.

**Comment by siusin** [comment]
Thanks @NickCraver !

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
