### ISSUE TITLE
Clarify a element having no href

### ISSUE THREAD

**Issue by iandevlin** [w3c/html#1693]
For the `a` element, the specification currently says:

> If the a element has no href attribute, then the element represents a placeholder for where a link might otherwise have been placed, if it had been relevant, consisting of just the element’s contents.

The corresponding [code example](https://www.w3.org/TR/html53/textlevel-semantics.html#example-e35d4fc1) showing a navigation list is an ideal example of what the above quote means, but I think it needs to be emphasised more (because the above quote has been used as a reason to me why `a` does not have to have `href` at all)

I propose moving the example code directly below the quoted sentence and the Example text changed to something like:

> If a site uses a consistent navigation toolbar on every page, then in this case the link that would normally link to the page itself could be marked up using an a element without a href:

An extended note could also be added to clarify that the `href` should only be left out in certain circumstances, similar to the code shown in the example above and should not be used as a reason to use `a` elements without `href`s where `button` should probably be used instead.

I am happy to hear your thoughts, and implement this change myself (so feel free to assign it to me if my suggestion is thought worthy!)

**Comment by iandevlin** [comment]
No comment? Nothing? Should I go ahead with the PR? If I do, will it also go the way of this issue and be ignored? Things are a bit slow in here, sadly.

**Comment by LJWatson** [comment]
Sorry there hasn't been a response. Work on this specification has been put into a holding pattern for the time being, pending discussions between the W3C and the WHATWG. We expect to know more about the outcome of those discussions fairly soon.

**Comment by iandevlin** [comment]
Oh ok, I somehow missed that that was the case. Many thanks for the update @LJWatson

**Comment by LJWatson** [comment]
I'm sorry. It hasn't been communicated to the community at all well, but I think that will be rectified in the next week or so.

**Comment by siusin** [comment]
Thanks @iandevlin !

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
