### ISSUE TITLE
Security: If a link title looks like or contains a url/domain that doesn't match its target, the link should be displayed differently and make users go through an informative security prompt.

### ISSUE THREAD

**Issue by PlNG** [w3c/html#1694]
An example: [http://www.example.com](http://www.example.org) the link title itself is example.com but the actual link target is example.org. I can't think of a legitimate use case for this occurring (except maybe by typo) and I see a lot of this in phishing attempts where the link title is a seemingly legitimate url, but the underlying target is a malware url.

The link should be styled or displayed differently and make users go through a security prompt if they click on it.

**Comment by SebastianZ** [comment]
This is indeed an important security feature, and at least for Firefox there is an [enhancement request to implement this](https://bugzilla.mozilla.org/show_bug.cgi?id=388052) (filed many years ago).

Though, I believe this something UI related and unrelated to the HTML spec. So, browser vendors are in the duty to implement this feature.

Sebastian

**Comment by rniwa** [comment]
That would be a neat browser feature but I'm not certain if it's something we want to spec in HTML.

**Comment by prlbr** [comment]
I've often seen this with affiliate programs. In these cases the link does actually lead to the target given in the link text, but only via a redirect that counts the click for the affiliate program, so the `href` is different.

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
