### ISSUE TITLE
Add a valid event to input element constraint validation

### ISSUE THREAD

**Issue by a2sheppy** [w3c/html#1696]
Currently, form constraint validation has a single event, `invalid`, which is sent when the value of the `<input>` is detected to be invalid. This makes it easy to detect when the value becomes invalid.

But there isn't really a clean way to detect the opposite -- when the value of the input becomes valid again. I propose adding a new `valid` event, which would be fired when an invalid input becomes valid.

With this addition, I would also suggest that it might be useful to send a `valid` or `invalid` event for each input in the following situations (in all cases, assuming that constraints are established for the element):

* When the document is first loaded, for each visible input
* When a new, visible, input element is added to the document
* Whenever an input becomes visible
* Whenever an input's value is altered programmatically

This would allow the `invalid` and `valid` handlers to deal with all the work, instead of having to special-case various situations, like checking the value manually on initially creating a form that has values pre-loaded, etc.

However, minimally, simply having the `valid` event fired when the existing validation succeeds would be a big help, I think. Creates balance that would be very useful for developers.

**Comment by siusin** [comment]
Thanks @a2sheppy !

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
