### ISSUE TITLE
<img>additional events, especially onprogress

### ISSUE THREAD

**Issue by Misiu** [w3c/html#1698]
On [w3cschools](https://www.w3schools.com/tags/ref_eventattributes.asp) page there is a nice section about Media Events:

> Events triggered by medias like videos, images and audio (applies to all HTML elements, but is most common in media elements, like `<audio>`, `<embed>`, `<img>`, `<object>`, and `<video>`).

Unfortunately, `<img>` don't support `onprogress` and to track the progress we must use `XMLHttpRequest` as shown [here](https://stackoverflow.com/a/22593907/965722)

Because I didn't find a good explanation of why this event isn't supported by `<img>` tag I'd like to ask for it here.

Are there any contraindications to add this event to `<img>` tag?

**Comment by siusin** [comment]
Thanks @Misiu . Hope the section of [image.complete](https://html.spec.whatwg.org/multipage/embedded-content.html#dom-img-complete) will help to explain this problem, if not, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
