### ISSUE TITLE
Drag and Drop API browsers should not open the file if not handled

### ISSUE THREAD

**Issue by barkermn01** [w3c/html#1703]
### Overview
I'm new here so not 100% sure if this correct, however, I think the spec needs to explicitly state that browsers should not perform any automatic handling of dropping.

### Example
So some website use `<input type="file" />` and a user has the ability to drop a file on this element that makes sense. what does not make sense is if you slightly miss the input due to bad CSS or just miss the element the browser then open the file making the browser act as a viewer (`file://` URI), causing the user to have to navigate back (back button, or otherwise) to the page and if they filled out a form first have the will have to refill it out as the form is cleared by the browser.

stackoverflow.com has the outlined problem.

Github.com does not so I assume they have coded handles into the pages to prevent the browser.

### Personal Views on the mater
I think the Drag and Drop section of the specification should explicitly state that dropping a file into WebSite viewport that is not handled by Javascript or specific elements in the case of the input file should be disregarded and not acted upon.

If people wish a file to be viewed in their browser they can use the "open with" prompt of there OS or if the browser support tabs drop it to the Tab Control area, not the viewport.

**Comment by siusin** [comment]
Thanks @barkermn01 .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.

**Comment by barkermn01** [comment]
Thanks just to update this I have moved the issue to the above issue.
