### ISSUE TITLE
Allow figcaption anywhere in a figure element?

### ISSUE THREAD

**Issue by chaals** [w3c/html#177]
From Bugzilla: https://www.w3.org/Bugs/Public/show_bug.cgi?id=12835

**Comment by LJWatson** [comment]
Test case:
http://ljwatson.github.io/test-cases/figcaption/index.html
On Windows, Chrome, Edge, Firefox and IE (11) render the `<figcaption>` based on its position in the DOM. It does not appear to be necessary for it to be the first/last child of `<figure>`.

**Comment by LJWatson** [comment]
IE (MSAA) does not support `<figure>` or `<figcaption>` (referenced from html5accessibility.com). Firefox and Chrome (IA2) expose the `<figcaption>` as the accessible name for the `<figure>`, regardless of where the `<figcaption>` is located within the `<figure>`.

Ping @stevefaulkner for confirmation and additional results.

**Comment by travisleithead** [comment]
Let me work up a PR for this

**Comment by travisleithead** [comment]
OK. Feedback on the PR please.

**Comment by chaals** [comment]
More tests and some preliminary results: http://chaals.github.io/testcases/figcaption-anywhere.html

**Comment by chaals** [comment]
This presumably should be synched with ARIA accessible name calculation... @stevefaulkner?

**Comment by stevefaulkner** [comment]
@chaals @LjWatson the acc name calculation will not be effected by the position of `<figcaption>` within the `<figure>` subtree, so no change in name calc required, me thinks.

**Comment by chaals** [comment]
I was wondering what happens if there is more than one `<figcaption>`. In my tests, all of them are included, along with all the `alt` values. Is that according to spec, or are implementations doing something different to what ARIA says?

**Comment by LJWatson** [comment]
@chaals
"I was wondering what happens if there is more than one  <figcaption> . In my tests, all of them are included, along with all the  alt  values. Is that
according to spec, or are implementations doing something different to what ARIA says?"

Included in what? AFAIK only the `<figcaption>` should be used as the accessible name for the `<figure>`. The alt provides the accessible name for the `<img>`.

The HTML spec says there should only be one `<figcaption>` (either before or after flow content) within a `<figure>`.http://w3c.github.io/html/grouping-content.html#the-figure-element 

If it seems there is implementation support for multiple `<figcaption>` elements within a `<figure>`, we should probably open a separate HTML issue and verify.

There is no figcaption role in ARIA, but ARIA 1.1 introduces the figure role:
https://www.w3.org/TR/wai-aria-1.1/#figure 

An object with the figure role can have its accessible name provided using aria-label or aria-labelledby. The latter can take content from multiple sources, which seems to be the approximate equivalent of multiple `<figcaption>` elements in the native case.

**Comment by chaals** [comment]
> If it seems there is implementation support for multiple <figcaption> elements within a <figure>, we should probably open a separate HTML issue and verify.

I'll run [my tests](http://chaals.github.io/testcases/figcaption-anywhere.html) on Windows today, but as far as Mac goes, anything I found that supports figcaption supports multiple ones. And for the PR #179 to address this we're talking about a couple of words, so I think we can handle it within the scope of this issue. 

> Included in what? AFAIK only the `<figcaption>` should be used as the accessible name for the `<figure>`. The `alt` provides the accessible name for the `<img>`.
> [...]
> [In ARIA 1.1] An object with the figure role can have its accessible name provided using `aria-label` or `aria-labelledby`. The latter can take content from multiple sources, which seems to be the approximate equivalent of multiple `<figcaption>` elements in the native case.

I agree that only the `<figcaption>` (or collection of them) should be used for figures. The problem is that I have yet to find an implementation that does that. But that's partly an ARIA question - although what we state as "the figure means whatever the `figcaption` says" is a restatement of the name calculation, and they should be in synch with each other and reality.

**Comment by stevefaulkner** [comment]
@LjWatson the test case which has `<figcaption>` inside a `<p>` element is not practical as <p> is closed when the parser encounters the `<figcaption>`. So you end up with 2 `<p>`'s
[live dom view](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A...%0A%0A%3Ch1%3E%20figure%20tests%3C%2Fh1%3E%0A%0A%3Cfigure%3E%0A%09%0A%09%09%3Cp%3ELorem%20Ipsum%20dolor%20sit%20amet...%0A%09%09%3Cfigcaption%3EFig.2%20Latin%20text%3C%2Ffigcaption%3E%3C%2Fp%3E%0A%0A%09%0A%3C%2Ffigure%3E%0A%0A%3Cfigure%3E%0A%09%0A%09%09%3Cp%3ELorem%20Ipsum%20dolor%20sit%20amet...%0A%09%09%3Cfigcaption%3EFig.2%20Latin%20text%3C%2Ffigcaption%3E%0A%3Cp%3Etest%0A%09%0A%3C%2Ffigure%3E)

first figure has `figcaption` inside `p`, second has `p` then `figcaption`, then another `p`. 
first does not parse as expected.

**Comment by LJWatson** [comment]
@stevefaulkner

Good catch, thanks. Have updated the test case.

**Comment by chaals** [comment]
fixed by #179
