### ISSUE TITLE
Create <?xml-stylesheet?> processing model

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#214]
Cloned from bug: https://www.w3.org/Bugs/Public/show_bug.cgi?id=14689

In "[load processing model for XML files](http://w3c.github.io/html/browsers.html#page-load-processing-model-for-xml-files)" we hint at a processing model for the `<?xml-stylesheet ...?>` directive (processing instruction), however, how this works is not defined.

It is also mentioned in the style and script sections in brief. As all modern web browsers support this functionality, we should be sure to describe how it works.

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
