### ISSUE TITLE
Should ordered list numbering consider list items in child blocks?

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#225]
Moved from bug: https://www.w3.org/Bugs/Public/show_bug.cgi?id=18263

This is a browser interop issue that should be resolved. The original concern was the difference in rendering the following: 
Consider this testcase:

``` html
<ol>
  <div><li>One</li></div>
  <li>Two</li>
  <li>Three</li>
</ol>
```

> This is numbered "1, 2, 3" by Gecko, WebKit, IE7 and before, and IE quirks mode.
> 
> It's numbered "1, 1, 2" by IE8 and IE9 standards modes and Presto.
> 
> I'm pretty sure that at least for quirks mode pages depend on this behavior.  I would also somewhat prefer that the behavior here not depend on mode...
> 
> Note that for <ol reversed> this also raises the question of how the start value is computed.

**Comment by prlbr** [comment]
It's probably obvious, but let me note anyway that this issue only concerns **invalid** HTML. I'm not sure whether browser behaviour needs to be defined here, but when it is, we need to consider things like:

```
<ol>
    <ol>
        <li>One</li>
        <li>Two</li>
    </ol>
    <li>Foo</li>
    <ol>
        <li>Bar</li>
    </ol>
</ol>
```

How shall Foo be numbered – 1, 3 or even 2?
How shall Bar be numbered – 1, 4, 2, …?
Would this change if the (incorrectly) nested `ol`s were `ul`s instead?

**Comment by travisleithead** [comment]
Sounds like getting this specified may need to wait a bit, given the following note in the [Rendering section](http://w3c.github.io/html/rendering.html#lists):

> This specification does not yet define the CSS-specific rules for rendering li elements, because CSS doesn’t yet provide sufficient hooks for this purpose.

**Comment by travisleithead** [comment]
Wondering if the above is still true. @tabatkins can HTML describe how to number nested lists? I'm not sure what hooks need to be described for this purpose. Can counters be used?

**Comment by tabatkins** [comment]
Counters are fully described in https://drafts.csswg.org/css-lists/#creating-counters.  It's a little complex, but yes, the "1,2,3" behavior described in the OP is still correct.  This behavior is necessary for counters in general, to allow things like numbering examples across a document.  (I've done some design work on creating a variant counter behavior that would only look at children, so this case would make more sense, but there wasn't sufficient interest for me to continue with it.)

The "ol > ol" behavior is... less certain.  I'm trying to get that changed _right now_, because it happens to have a weird effect on _valid_ code.

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
