### ISSUE TITLE
Media-type registrations should include clipboard flavor names

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#227]
Moved from Bugzilla bug: https://www.w3.org/Bugs/Public/show_bug.cgi?id=18508

> As suggested on the IETF-types mailing-list, I would like to request that the working group includes two extra fields in the xx section of almost each of the media-types registrations' appendices:
> http://www.ietf.org/mail-archive/web/ietf-types/current/msg01715.html
> - a Windows Clipboard Flavor Name (probable link: http://msdn.microsoft.com/en-us/library/ms649013.aspx)
> - Macintosh Uniform Type Identifier (see http://developer.apple.com/mac/library/documentation/FileManagement/Conceptual/understanding_utis/)
> 
> This way platforms, which mostly already define these types, would do so based on an open standard.
> 
> Previous examples of doing such include the MathML and the SVG specifications.
> 
> I am happy to formulate proposals from experimentation and spec reading.

@polx, we welcome your experiments/PRs!

**Comment by siusin** [comment]
Looking at [Apple's System-Declared Uniform Type Identifiers](https://developer.apple.com/library/content/documentation/Miscellaneous/Reference/UTIRef/Articles/System-DeclaredUniformTypeIdentifiers.html) and MS's [Standard Clipboard Formats](https://msdn.microsoft.com/en-us/library/windows/desktop/ff729168(v=vs.85).aspx), I think the current [IANA considerations](https://w3c.github.io/html/iana.html#iana) section is up-to-date.

No changes need to make here.

**Comment by polx** [comment]
Hey @siusin, 
The [IANA considerations](https://w3c.github.io/html/iana.html#iana) I can see does not have the word clipboard, flavor in it. Should I look in the history orsee candidate version?

Moreover, are you telling me in your comment that:
1) you feel it's ok to leave this in the hands of software vendors such as Apple or MicroSoft instead of writing this in a standard?
2) The MicroSoft page you refer has something for HTML ?

For the first, I personally disagree and can tell you that such referred pages have a bad tendency to change. Hence I believe it is valuable to capture that in a standard so that one architect software based on it.

For the second, I hope I have overlooked.

All in all, can you please elaborate why you think it should be closed?

thanks in advance.

Paul

**Comment by siusin** [comment]
@polx apologise if I got it wrong in the previous comment... 

Were you proposing the spec should 1) append the Macintosh Universal Type Identifier code/Macintosh file type code, the Windows Clipboard Name information to [Additional information](https://w3c.github.io/html/iana.html#iana) , or did you want to 2) define a general clipboard flavour names for all the software vendors?

If 1) makes sense to you, I can submit a PR for the Macintosh UTI, do you have any information (or could you direct me to information) for the Windows Clipboard Name of text/html, multipart/x-mixed-replace, application/xhtml+xml? also /Cc @travisleithead 

If you prefer 2), could you tell us more about your thoughts on the names?

**Comment by LJWatson** [comment]
@polx if you can offer @siusin any further help/guidance, that'd be welcome. We're in the last few weeks before we lock HTML5.2 for release. Thanks

**Comment by siusin** [comment]
According to the latest MSDN document, we can add a Windows Clipboard Name for HTML: [CF_HTML](https://msdn.microsoft.com/en-us/library/ms649015(v=vs.85).aspx).

@polx wdyt?

**Comment by polx** [comment]
Dear Siusin,

yes, [your PR](https://github.com/w3c/html/pull/1282)  looks very good to me.
I am wondering if it is possible to get a MicroSoft person involved before the publication so that the durability of the URL can be ensured. This has been rather difficult of the years.

I'll try to do so the same for MacOSX UTI based on your model which is rather helpful!

thanks

paul

**Comment by polx** [comment]
[PR for UTIs for MacOSX](https://github.com/w3c/html/pull/1302) posted.
thanks in advance.
Paul

**Comment by siusin** [comment]
Sure @polx .

@travisleithead @adrianba 
do you know whether the information on the [HTML Clipboard Format MSDN](https://msdn.microsoft.com/en-us/library/ms649015(v=vs.85).aspx) page is still up-to-date? This issue requires to add a Windows Clipboard Format (CF_HTML) to the Media-type registrations of HTML.

**Comment by travisleithead** [comment]
@gked may be better posed to answer this :)

**Comment by chaals** [comment]
@siusin should this still be open?

**Comment by polx** [comment]
Hello @chaals,
There's only the long-term of the URLs which is questionned at this point, I think.
@gked, can you provide an answer?
thanks
paul
