### ISSUE TITLE
persistent localstorage allowing cachepage

### ISSUE THREAD

**Issue by marquish** [w3c/html#228]
Localstorage would be better with relatively persistent storage. With capability managing script and stylesheet links in cache (defined in CACHE Manifest). 
With added Storage of BSON type data automatically indexed on the location. 
Might make client side 'high availability' feature. An added attribute for 'realtime browsing' that would deactivate the cache functionality. 

OpenDatabase("notes", , ,) could search for the indexed storage.

**Comment by chaals** [comment]
This is being closed as invalid since it doesn't clarify the problem to be solved.

Please do not reopen this bug unless
- [ ] the problem to be solved is clearly stated
- [ ] it is clearly an issue for the HTML specification. This issue seems relevant to the [Web Storage](https://www.w3.org/TR/webstorage/) specification
- [ ] Any feature requests have been incubated for example in the [Web Platform Incubator Community Group](http://discourse.wicg.io), and there is demonstrable interest in implementation.
