### ISSUE TITLE
introducing <phonetics> tag

### ISSUE THREAD

**Issue by marquish** [w3c/html#232]
using <phonetics>/fəˈnɛtɪks/</phonetics> in content word, would provide wonderful usability to the html users. The multilingual websites too could take advantage.
The content should be pronounced when hovered, selected in web browser.

**Comment by chaals** [comment]
There are various ways to do this, but it seems unlikely that a new HTML element will be one of them. Although the market might decide otherwise leading us to reopen this issue, for now I am going to close it as "wontfix".

This is a common use case for [ruby markup, which is already in HTML](https://w3c.github.io/html/textlevel-semantics.html#the-ruby-element).

More generally, when requesting new features that don't have any current implementation, please "incubate" them first - get a specification together that people think is a reasonable base to start test implementations, before bringing it to the HTML specification.

It is also helpful to have something more concrete than the simple statement of intent above: where can the element be used, what sort of systems implement it, what if it is used wrongly, etc. All those things should be written down somewhere, if you're going to discuss a proposal in discourse, so other people get a better sense of what you are asking for.

The WICG group is meant to enable that - discussions are held in their ["Discourse" system](https://discourse.wicg.io/), which is similar to github's issue tracker.
