### ISSUE TITLE
[Proposal] passphrase input

### ISSUE THREAD

**Issue by Lcfvs** [w3c/html#249]
Hi all,

I was always surprised that no multiline support for password fields.

However, this may increase their complexity and push the user to use long passwords .

I'm well aware, a such feature doesn't risks to appear on all sites, for design reasons, but I find it unfortunate that at present, the possibility doesn't exist, technically and offering the "hidden characters" ability.

What do you think about it?

**Comment by RyanSquared** [comment]
I would think it would break how multiple users log into websites; allowing for paragraph-format passwords would mean that login forms no longer can be pushed by pushing Enter and instead would require the user to remove focus from the passphrase box.

**Comment by chaals** [comment]
More to the point, I am not sure what the value is. I would be surprised if browsers want to implement it, and agree that changing the standard behaviour of a password field isn't all that helpful.

You can already enter a very long phrase in a password field (or else there is a bug in your browser or the processor on the website).

Since this is a feature request and as far as I know hasn't ever been implemented, if you want to follow it up I would encourage you to raise it in the [Web Incubator Community Group](http://discourse.wicg.io) and get some support and something more of a specification together.

**Comment by Lcfvs** [comment]
I don't want to change the existing element.

It's why I suggest un new input type: "passphrase", not "password".  ;)

@chaals : Ok, thanks, for the incubator :)
