### ISSUE TITLE
De-emphasis DOCTYPE: shift focus from ”required preamble” to ”required rendering mode”

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#253]
Moved from Bugzilla: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25232

 following up with @komputist

> SITUATION: 
> 
>  Spec makes clear that the requirement to use a conforming DOCTYPE is a legacy behavior issue. Thus, the underlying logic is that we should get rid of the legacy necessity.
> 
>  Then the spec goes on describing the DOCTYPE as 
> 1. ”a required preamble” which 
> 2. ”ensures that the browser makes a best-effort attempt at following the relevant specifications”. I.e. spec says DOCTYPE triggers no-quirks mode.
>    
>    The problem is that neither of above two statements are completely true. How true they are, depends on context:
> 1. Above spec quotations are true only for HTML pages in Web browsers.
> 2. Inside @srcdoc, the spec itself says that the DOCTYPE is optional: http://www.w3.org/html/wg/drafts/html/master/single-page.html#attr-iframe-srcdoc Thus, DOCTYPE is not required for @srcdoc documents.
> 3. For HTML mail, the effect of DOCTYPE falls in 3 categories, with well known implementations in each category:
>    1. DOCTYPE ignored, falling back to no-quirks, is implemented by
>       - Web mail apps (because app itself is in no-quirks) Examples: 
>         - Microsoft Outlook.com
>         - Google Gmail
>       - Mozilla Gaia of Firefox OS (because it’s a offline Webmail app?)
>    2. DOCTYPE ignored, falling back to quirks mode. Implemented by:
>       - Mozilla Thunderbird (https://bugzilla.mozilla.org/show_bug.cgi?id=335499)
>       - Microsoft Email app for Windows 8.1
>    3. DOCTYPE treated same as in Web browsers:
>       - Microsoft Windows Live Mail 2012 (latest release: 2014)
>       - Microsoft Windows Mail,
>       - Microsoft Outlook Express,
>       - Apple Mail for OSX
>       - Apple mail for iOS
>    
>    (Though this be another bug, my general proposal for HTML mail is that A) (DOCTYPE ignored, falling back to no-quirks) should be the rule for HTML email.)
> 
> PROPOSAL:
> 
>  Rework the spec towards saying that
> 1. conforming documents are required to be authored so that they cause no-quirks rendering.
> 2. user agents are required to 
>    - EITHER treat the DOCTYPE as OPTIONAL, in which case the UA MUST always use no-quirks mode. (This ought to be preferred behavior for 'new' specs.)
>    - OR, they must adhere to the mode selection rules defines by the HTML specification.
> 3. Sub sections of the spec and "sub specifications" may give more specific rules for certain usage contexts and/or media types. Examples: `@srcdoc`, HTML email and Web mail.

I'm not confident (but would love to be proven wrong) that we could make not including a `<DOCTYPE>` default to no-quirks rendering mode. So, your point (1) sounds good to me, point (2) would need to be the "must adhere to the mode selection" part of the spec, and point (3) also sound good.

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
