### ISSUE TITLE
Can HTML Mail be exempt from using <DOCTYPE>? (And get no-quirks rendering)

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#255]
This issue is related to issue #253. @komputist

> PROPOSAL:
> 
> For HTML mail, the DOCTYPE should be ignored, falling back to no-quirks rendering. THus doctype should not be required. This should be said in new section somewhere in the spec.
> 
> COMMMENT:
> 
> Mail is a "date stamped" format that is stored inside private mailboxes. Thus legacy issues are probably seldom.  For online webmail, the rendering mode probably almost always depends on the rendering mode of the Web app.
> 
> Thus, all in all, the only reliable way forward is to make all HTML mail use no-quirks mode and only no-quirks mode. HTML mail is the number one production equipment for HTML and we gotta make it so that mail applications by default and with ease can produce conforming HTML. For many Web authors, it would be a benefit if it this way became simpler to get the same rendering mode etc across email readers.
> 
> Please see #253, which proposes a general approach for de-emphasizing the DOCTYPE and instead emphasizing the rendering mode.

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
