### ISSUE TITLE
Should HTML allow <a rev> and <link rev> to be non-obsolete?

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#256]
Moved from https://www.w3.org/Bugs/Public/show_bug.cgi?id=25398

@darobin previously removed `rev` from the list of obsolete features for the last HTML5 Rec. With our latest draft, `rev` is back to obsolete:

> - rev on a elements
> - rev on link elements
>   - Use the rel attribute instead, with an opposite term. (For example, instead of rev="made", use rel="author".)

Shall we once again make `rev` conforming (in the face of the RDFa Core 1.1 - Second Edition criteria), or keep it obsolete and look for an alternative solution for RDFa?

@f4nt (I think)

**Comment by rogersmark** [comment]
Think you might have the wrong f4nt :)

**Comment by chaals** [comment]
There is a [fair amount of RDFa](http://webdatacommons.org/structureddata/2015-11/stats/stats.html) out there. Not sure how much of it uses `rev` but since that usage is promoted by schema.org which is one of the most common uses of RDFa, we might want to leave it in there…

(How did it get obsoleted anyway?)

/@danbri

**Comment by danbri** [comment]
It's a relatively niche feature of RDFa but addresses a genuine need. Otherwise every structured data vocabulary needs to name every property in both directions ("hasPart" vs "isPartOf"). Even considering just schema.org, we've got approaching 1000 property names and it is consistently difficult finding names for them even in one direction. I'd support the restoration of @rev ...

("Use the rel attribute instead, with an opposite term" only makes sense if someone has defined those opposite terms.)

**Comment by travisleithead** [comment]
OK. Adding this to my queue.

**Comment by travisleithead** [comment]
OK, go checkout PR #315 and let me know what changes you'd like to make before we merge this in.

**Comment by danbri** [comment]
/cc @scor 

The language used, "Relationship between the document containing the hyperlink...", may not be a great fit with RDFa's use of @rev (or @rel). In RDFa the relationships are equally often about real world entities described in the markup. 

Would vaguer language be possible, e.g. "Indicates a relationship to ..."?

**Comment by travisleithead** [comment]
Sure. Let me make that suggested change...

**Comment by travisleithead** [comment]
Hmm. 'relationship' is used in `rel` too... looking for a better word to use in both places...

**Comment by danbri** [comment]
"relationship" feels ok to me, so long as there is some flexibility in the definition to allow for both usages.

It is a longstanding oddity in the Web dating back to the diagram in https://www.w3.org/History/1989/proposal.html and to https://www.w3.org/Talks/WWW94Tim/ that sometimes we're talking about relationships amongst documents, and sometimes amongst the things the documents describe. Both are super useful and "relationship" is general enough for both. The awkwardness is in deciding which specs get to fix which things are being related in any given piece of @rel or @rev markup.

**Comment by travisleithead** [comment]
I went back and took a hint from HTML4 :) PR updated, let me know what you think.

**Comment by danbri** [comment]
Excerpting, 
-    link/rel — Relationship between the document containing the hyperlink and the destination resource
-   link/rev — Describes a <a>reverse link</a> from the resource to the containing document

My nitpicking is around "Relationship between the document containing the hyperlink"; is there a graceful way of saying "Relationship between the document containing the hyperlink (or one of its subsections or topics)"? Then definition of rev would be just the inverse of that.

**Comment by scor** [comment]
A good example to illustrate the need for more granularity is for pages that describe multiple topics/things. For example, http://www.icao.int/pages/contact_us.aspx lists lots of offices around the world, and each of those does not have a separate page/document. In this situation, "document containing the hyperlink" is too broad and we need more granularity to describe each office location.

**Comment by danbri** [comment]
@scor could you sketch how that might look in actual RDFa 1.1 (with @rel and with @rev)?

**Comment by travisleithead** [comment]
>  "Relationship between the document containing the hyperlink (or one of its subsections or topics)"

So, I don't know my rel values very well, but are you describing something like this:

``` html
<link rel="place1" href="somedocument.html#address1">
<link rel="place2" href="somedocument.html#address2">
```

where the "document" is the same, but the sections in the document are different?

**Comment by danbri** [comment]
@scor correct me if I'm wrong please. If RDFa's vocab is used about the @rel in the tree, then unprefixed content of @rel is understood by RDFa to be representing properties of the thing being described by that piece of RDFa. So in this example there are two different Persons being described:

```
<div vocab="http://schema.org/">
 <div typeof="Person">
   <span property="name">Dan</span>
   <link rel="homeLocation" href="/addresses.html#address1">
 </div>
 <div typeof="Person">
   <span property="name">Stephane</span>
   <link rel="homeLocation" href="/addresses.html#address2">
 </div>
</div>
```

Hence  (or one of its subsections or topics); in this case Stephane and Dan are two of the documents topics, and "homeLocation" in both cases is a relationship between the relevant person and the thing at the far end of the link.

**Comment by scor** [comment]
@danbri yes you are right. Here is another example using @rev this time:

```
<div vocab="http://schema.org/">
 <div resource="/addresses.html#address1" typeof="Place">
   <span property="name">Beachwalk Beachwear + Giftware</span>
   Phone: <span property="telephone">850-648-4200</span>
   <link rev="workLocation" href="people.html#dan">
 </div>
 <div resource="/addresses.html#address2" typeof="Place">
   <span property="name">Springfield Town Hall</span>
   Phone: <span property="telephone">617-548-1400</span>
   <link rev="workLocation" href="people.html#stephane">
 </div>
</div>
```

**Comment by danbri** [comment]
Thanks. The point being that these people and places are the natural things you'd say that "workLocation" is relating, hence "(or one of its subsections or topics)".

**Comment by travisleithead** [comment]
Alright, made a change to sync-up the short description for `rel` and `rev` so that they better mirror each other and take your extra 'subsections or topics' prose into account. Go checkout the updated PR at https://github.com/w3c/html/pull/315

**Comment by danbri** [comment]
The #315 change looks good to me. Is there anything more to do on this current issue?

**Comment by tantek** [comment]
Coming to this late (unfortunately), however, I think the overall analysis here is flawed in comparison to the actual usage data on 'rev' collected during the development of HTML5, which determined that it was a very buggy feature, authors being confused more often than not and mis-using it[1][2][3][4]. It's essentially mal-designed (fails usabilty) and any technology depending on it (RDFa, schema, or otherwise), or at least for such scenarios depending on it, are no more likely to succeed (make sense and produce good data from developers) than rev did by itself.

[1] https://developers.google.com/webmasters/state-of-the-web/2005/linkrels?csw=1 has the high-level overview, I don't know where the details are, they may be private to @Hixie, but he would be able to better point to them.
[2] https://lists.w3.org/Archives/Public/public-whatwg-archive/2008Nov/0377.html has perhaps the most recent "litigation" of this debate for background. Suffice it to say, use of rev is rare, most of the time wrong, and unnecessary in practice.
[3] https://philip.html5.org/data/link-rel-rev.txt
[4] https://web.archive.org/web/20091206044551/http://www.xanthir.com/rev_using_links20081119.txt

In attempt to debunk the apparent justifications given in the github comments above:

Travis wrote:

> Shall we once again make rev conforming (in the face of the RDFa Core 1.1

No. This is at best a theoretical justification, which does not measure up to the data against actual 'rev' usage / workability.

Chaals (possibly channeling danbri) wrote:

> There is a fair amount of RDFa out there. Not sure how much of it uses rev but since that usage is promoted by schema.org which is one of the most common uses of RDFa, we might want to leave it in there…

"RDFa out there" != rev usage. (as noted in second sentence).

"Not sure how much of it uses rev" = NONE. No examples were provided, therefore I will assert that NONE of the RDFa "out there" uses "rev". If there were even a single example "out there", there should have been a link provided to it in the thread.

"usage is promoted by schema.org" - no link given for such promotion, and even if it were, such "promotion" is outweighed by the usability failures of 'rev'

"might want to leave it in" - this is a bad reason and an insufficient bar for putting something in a CR, much less _restoring_ something that was explicitly previously dropped.

"might want to" = go try incubating it somewhere and then document the results of that incubation. Not WD-worthy.

danbri wrote:

> It's a relatively niche feature of RDFa but addresses a genuine need.

It cannot be actually addressing any need, genuine or otherwise, in the context of HTML because its usage is so broken.

If it has a "genuine need" as a "niche feature of RDFa", then the right thing to do is to revise RDFa to add it as an extension. It does not belong in the core HTML5.x spec.

danbri wrote:

> It is a longstanding oddity in the Web (snip thing vs thing represented by the thing)

No. This is orthogonal to httprange14, as is the flawed existing usage of 'rev'.

Additionally I will note that not a single real world example (link) was given for a use of 'rev'. (Not that "one example" would be sufficient, but that it's surprising that not even one was provided.)

This (rev being added back to HTML5.1 as a result of this github issue/thread) is frankly, appalling. 

If this github thread were used as evidence for promoting a new WICG attribute from incubation (cc: @cwilso) to a WPWG WD, it would be soundly rejected. The fact that such rigor was glossed over for adding a previously dropped/obsoleted attribute back is out of order, especially since it appears no-one in the above thread actually bothered to cite / analyze / refute the previous research and/or discussions.
