### ISSUE TITLE
Navigation Algorithm Ambiguity

### ISSUE THREAD

**Issue by arronei** [w3c/html#282]
Imported from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28655

I would like to point out one thing that is not clear from the specification. In section 5.6 Browsing the Web(http://www.w3.org/TR/html5/browsers.html#browsing-the-web), if a user-agent is trying to grab a new HTML page that is not in cache (as per step 14 of the navigation algorithm) we will request to get that page using fetch algorithm(http://www.w3.org/TR/html5/infrastructure.html#fetch) which is executed in async mode. After initiating the request, the navigation algorithm in step 18 waits for few bytes to be available before moving on and the fetch algorithm is supposed to queue a task that will fill input byte stream and invoke html parser to do appropriate steps (http://www.w3.org/TR/html5/browsers.html#read-html). But HTML parser is created by queuing a task in step 23 of navigation algorithm. If fetch algorithm gets bytes before execution of step 23 how will it wait for creation of html parser? Will it spin the event loop?

**Comment by plehegar** [comment]
Related https://github.com/w3c/html/issues/132 ?

**Comment by adanilo** [comment]
The current algorithm doesn't match the description which was made almost 2 years ago. In any case, the simple answer is that the browser/fetch algorithm would buffer the bytes until creation of the parser. Also, the waiting for bytes step is to detect if the resource exists, then the next thing is checking the response which could be false or a redirect in which a parser wouldn't be created.

The suggestion in issue #132 should be considered since the specs have been diverging and it's of interest only to browser implementors rather than developers building sites.

Closing, as there is no event loop spinning, the bytes are just buffered until there are either none, or enough to decide if the resource exists and needs to be processed.
