### ISSUE TITLE
Help authors write link and meta elements more efficiently

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#303]
Migrated from <a href="https://www.w3.org/Bugs/Public/show_bug.cgi?id=29484">Bugzilla #29484</a>.

Ping @nick-levinson

**Comment by chaals** [comment]
from the original bug:

> When metadata or link elements are identical across most of a large website, maintenance is slower and costlier.
> 
> Suggestion: Add a file of website meta and link elements that apply to an entire website.
> 
> Exceptions should be supported. If the same meta or link element with the same attribute also appears in a page file, regardless of the value, the one appearing in the page file would get precedence.
> 
> Very large sites may need directory specificity. A file of directory-specific meta and link elements would override the website-wide file of meta and link elements, while being overridden by the same element-attribute pairs written into a specific page.
> 
> I don't program in PHP, but I suspect this being in HTML would mean faster page loading.
> 
> Example: The author of a whole website might be Chris, which need be said in only one place, the website file; except that the author of the Executive subdirectory might be Pat, which need be said in only one place, the directory file; except that the author of the one-page CEO's Letter might be Landry, which need be said in only one place, in the HTML page's head element.

**Comment by chaals** [comment]
This looks like it is really in the realm of the work on [manifest](https://github.com/w3c/manifest)

**Comment by Nick-Levinson** [comment]
If that applies to websites, yes, but I don't see that in Web App Manifest (https://w3c.github.io/manifest/) unless I misunderstand. I'm also not clear that it would permit exceptions (a directory as an exception from the whole website, etc.).

**Comment by chaals** [comment]
The use case is outside HTML, which generally describes the content of a single page rather than a collection. The [Site-wide HTTP headers](https://tools.ietf.org/html/draft-nottingham-site-wide-headers-01) proposal at IETF seems to satisfy the requirements, and it is directly in scope there, so I am closing it for now as an issue for HTML…

There may be a question to raise later about how to use that with `meta http-equiv` if it doesn't "Just Work" - so it would be good to keep an eye on that. Ping @mnot

**Comment by mnot** [comment]
Ping @mikewest - another use case. Chaals, see https://github.com/WICG/origin-policy
