### ISSUE TITLE
Meta property attribute should be recognised

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#304]
Migrated from <a href="https://www.w3.org/Bugs/Public/show_bug.cgi?id=29485">Bugzilla #29485</a>

**Comment by arronei** [comment]
@Nick-Levinson

For the meta element with the property attribute, I'm concerned that someone out there is going to use both attributes (name and property) for the same value strings but with different meanings. Unless creating the property attribute was simply a mistake, that's the likeliest use, and it's likely even if it was a mistake since it's now available to future developers. For now, we're stuck with hoping for the best with it, especially since Facebook and Google are supporting it and they're big players.

Would it help nip this in the bud if HTML5 were to state that the two attributes are interchangeable and therefore are not to both be used in the same element and that value strings for both shall have the same meanings? Or should the WHATWG MetaExtensions page (because it's linked to from HTML5) be explicitly expanded to require (or try to require) registration of property values? Or both? Or should property be deprecated now and reserved for possibly some undefined future use?

**Comment by chaals** [comment]
@danbri does this touch RDFa, as used in schema.org? Or otherwise @halindrome

**Comment by halindrome** [comment]
It certainly touches RDFa.  The property attribute on meta is a common way to provide information about the content attribute of meta.  See https://www.w3.org/TR/xhtml-rdfa-primer/#using-the-content-attribute for examples and https://www.w3.org/TR/html-rdfa/#extensions-to-the-html5-syntax for the normative definition.

In no way do @name and @property have anything to do with one another on the meta element.

@msporny do you have any more to say about it?

**Comment by msporny** [comment]
> Would it help nip this in the bud if HTML5 were to state that the two attributes are interchangeable and therefore are not to both be used in the same element and that value strings for both shall have the same meanings? 

They are not interchangeable. Are people using them interchangeably?

> Or should the WHATWG MetaExtensions page (because it's linked to from HTML5) be explicitly expanded to require (or try to require) registration of property values? 

-1 to require registration of property values. HTML5+RDFa's processing rules on @property and @name in META are clear. We do have the RDFa Core initial context as the "official" registration location for terms and CURIEs:

https://www.w3.org/2011/rdfa-context/rdfa-1.1.html

and there is one for HTML5+RDFa 1.1 (which is empty, on purpose):

https://www.w3.org/2011/rdfa-context/html-rdfa-1.1.html

> Or both? Or should property be deprecated now and reserved for possibly some undefined future use?

-1 for deprecation, it would break RDFa and we don't want that since it has non-trivial deployment:

http://webdatacommons.org/structureddata/2015-11/stats/stats.html#results-2015-1

**Comment by chaals** [comment]
This would break existing W3C Recommendations, out of scope for this group.
