### ISSUE TITLE
html and head elements should not get new attributes

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#305]
Migrated from <a href="https://www.w3.org/Bugs/Public/show_bug.cgi?id=29486">Bugzilla #29486</a>

**Comment by arronei** [comment]
@Nick-Levinson

There seems to be a mild trend toward adding attributes into the html and head start tags (for example, the Open Graph protocol alone may require at least three). However, the charset must be completely declared within the first 1,024 characters of the file. As of yet, I don't think that's a conflict, but if anyone else wants to require more to be written into those 1024 bytes then we could have a problem. Possibly two solutions exist: get rid of the 1024-byte limit (I suppose there's a reason for it and that should be checked) or limit what can be required within that byte count. The most vulnerable are, I think, the html and head opening tags with new attributes and the doctype declaration if we again require a long one (it's shorter now than it was for HTML4). For example, I think putting the dir, lang, and translate attributes into the html element is either required or recommended when I'm not clear why putting all three into the opening body tag wouldn't suffice for all purposes, since the head element's content is, as far as I know, always left-to-right, in English, and not translated and therefore those attributes are irrelevant for the head element's content. I've already proposed to the Open Graph developers (https://groups.google.com/forum/#!topic/open-graph-protocol/e-ryeBShGY4) an alternative solution to requiring that their several attributes be added to the head opening tag (they can accept declarations being in link or meta tags preceding other tags using OGP), although the size of the installed base may make deprecation difficult or at least very slow.

**Comment by r12a** [comment]
> For example, I think putting the dir, lang, and translate attributes into the html element is either required or recommended when I'm not clear why putting all three into the opening body tag wouldn't suffice for all purposes, since the head element's content is, as far as I know, always left-to-right, in English, and not translated and therefore those attributes are irrelevant for the head element's content.

There is no reason to expect the head element contents to be in English when they contain such things as title and meta elements for pages in languages other than english.

The translate attribute is not required in the html tag (and i think it would be unusual to find it there), nor is dir when the direction is not RTL.

As alluded to above, there are items in the head that benefit from lang and dir declarations, such as the title element.  Also, putting dir on the body element results in different behaviour in some browsers.

**Comment by duerst** [comment]
@arronei 
Rather than getting rid of the 1024 limit, it could be extended (e.g. to 2048 bytes or so). As far as I remember, there was a similar limit for IE: It would identify something as HTML if there was a <title> element early on. But I think that was only 400 bytes. That's btw the reason why <title> is mandatory :-).

**Comment by arronei** [comment]
@duerst I didn't get rid of the 1024 limit, I just made a note that people should be aware that there is a gain to be had. Browsers are actually somewhat lenient about this 1024 byte rule and often restart parsing even if they find a charset later than the first 1024 bytes. Having this note just gives a gentle warning and points to a more clarified definition.
