### ISSUE TITLE
Default styling for q element

### ISSUE THREAD

**Issue by r12a** [w3c/html#314]
**[This issue is carefully focused on language choices made by the styling shown in 10.3.6 Quotes in the spec. Please do not widen it to discuss the appropriateness of specific quotation marks proposed in that section for a given language, and please do not widen it to a more general discussion about the value or not of the q element. There are likely to be other issues raised for those points.]**

Users expect default quotation marks around quotes to conform to the conventions of a particular language. For example, en-US typically uses “ ...”, whereas in Greek text a user may expect to see «...».

A recent discussion on the Digital Publications IG list and the I18n IG list produced a groundswell of opinion that the styling indicating the selection of localised quotation marks in the HTML spec is incorrect. The choice of quotation marks should not be based on the language of the quote itself. Instead, the styling should look at the language outside the quote and use that to determine the quotation marks used.  Furthermore, quotes embedded inside other quotes should by default still be surrounded by the quotation marks of the language outside the outermost level quote. 

The discussion lead to suggestions for two alternative ways to style default quotation marks.

This is summarised in more detail at http://w3c.github.io/i18n-discuss/default-quote-styling. Please read.

The i18n WG would like the folks working on HTML to consider these findings and propose a way forward.

(fwiw, this also harks back to a bugzilla issue that was closed without complete resolution, and which can be found at https://www.w3.org/Bugs/Public/show_bug.cgi?id=13398)

**Comment by chaals** [comment]
As I read http://w3c.github.io/i18n-discuss/default-quote-styling the first proposal is for something that only works in one browser, which isn't all that useful IMHO, and on top of that there is an issue…

The second solution seems reasonable to me, in the sense that HTML isn't especially helpful for real multilingual documents anyway so people who do them are more likely to either get it right or have very low expectations for rendering quality.

In any event, so long as this involves replacing a default stylesheet, and changing the rendered view of content without touching the semantics, I think it's something that can be done, although it would help to hear from browsers that they are prepared to do so.

Maybe a good next step would be to file bugs on *browsers* suggesting they look at the proposed solutions?

**Comment by edent** [comment]
I'm coming up to speed with this issue. Could you please clarify a few things for me?

`<p lang="en">She said <q lang="ja">こんにちは</q></p>`

In your opinion, this should render with English quotes around the Japanese text - 
`She said “こんにちは”` - is that correct?

According to the tests at https://www.w3.org/International/tests/repo/results/the-q-element#ml_nesting - this is currently only possible (except Firefox) if this is written as:

`<p lang="en">She said <span lang="ja"><q>こんにちは</q></span></p>`

Have I understood this correctly?

In order to make this work, we need to change the Block at https://www.w3.org/TR/html5/rendering.html#quotes

Have I understood that correctly?
