### ISSUE TITLE
Enhancing the media volume

### ISSUE THREAD

**Issue by Sworddragon** [w3c/html#344]
This ticket was originally posted here ( https://www.w3.org/Bugs/Public/show_bug.cgi?id=29399 ) and got now forwarded to this tracker.

**Comment by chaals** [comment]
It was forwarded to [WICG](https://discourse.wicg.io) because it is a feature request that, as per the [guidelines already pointed to](https://github.com/w3c/html#contributing-to-this-repository), should be incubated to demonstrate some real traction first.

The feature requested is to provide a volume level greater than 1.0 - effectively, amplification, instead of asking the user to balance their various audio resources in the context of a given system volume. That's a significant change to implementations, hence the request to incubate it.

**Comment by Sworddragon** [comment]
Thanks for clarifying that feature requests needs to be incubated. But in my opinion (with the fragmented informations; multiple accounts needed) this is made all unnecessary complicated. Ideally all steps could be done in such a ticket here. Anyway, if somebody finds this feature request here useful feel free to take over the incubation process. I will continue to post ideas here if I have a new one and initiating the incubation process myself only if I have enough spare time and nothing else important to do.

**Comment by Sworddragon** [comment]
A few notes to the part with the sound amplification:

- The Flash Player is capable of sound amplification which works fine there. Developers might have used it on their Flash applications and will then probably find it useful if they could continue to use it on porting their applications to HTML5.
- While this was already pointed out more or less on the linked ticket in the startpost another current use-case for such a feature would be Twitch. Since I'm watching it I notice that the sound compared to other sources (for example native games or other websites like YouTube) is significant more quiet so that I have to adjust my speaker volume. Also sometimes broadcasters on Twitch have different sound input levels causing additional volume differences on switching just to another broadcaster. But because this requires currently to adjust the volume in a global context it can be easy forgotten resulting sometimes in a very loud and unexpected sound if switching to another sound source which would not happen if the sound could be amplified locally for Twitch.
