### ISSUE TITLE
Add text for the ping attribute

### ISSUE THREAD

**Issue by adrianba** [w3c/html#369]
Previous there was a [CfC, which passed, to remove PING](https://lists.w3.org/Archives/Public/public-html/2010Mar/0132.html) from HTML 5. Part of the rationale for the [original change proposal](https://lists.w3.org/Archives/Public/public-html/2009Dec/0183.html) was that, _"The feature is half-baked, insufficiently implemented, and therefore not yet suitable for standardization."_

There are now multiple implementations of the ping attribute and this decision should be revisited with this new information.

The resolution of the CfC said, _"The feature could still be proposed again for a later issue of HTML, or the issue could be re-raised if new information is provided (such as implementation experience  or server-side deployment experience.)"_

**Comment by travisleithead** [comment]
Given what I'm hearing about the privacy group potentially having concerns over adding this API into 5.1, and given our relatively short timeline, I think we are OK with moving this issue to 5.2 and adding it to the spec in order to have time for wider review and resolution of potential issues as a result.

**Comment by chaals** [comment]
Note [don't send a referrer with cross-origin ping](https://github.com/whatwg/html/commit/faec3a50ea181f322ab9819975e285ced34a0308)

**Comment by chaals** [comment]
And [don't send ping for non-http URLS](https://github.com/whatwg/html/commit/b66ec320db01c12d48176052c3b9cd55a10f3176)

**Comment by chaals** [comment]
As well as `a.ping` [`area.ping` is DOMTokenList](https://github.com/whatwg/html/commit/da9e4cb7142277d609e6636a56a282f5aba15e5c)

**Comment by chaals** [comment]
(Live notes from discussion with the Privacy Interest Group)

Note that if we have a requirement that user agents clarify to the user that the link will ping other sites, we need to test whether that happens in real implementations.

Note also that among privacy considerations, this *can* improve the ability to offer privacy because it's declarative and easily parsed, meaning user agents could inform users and allow them to control what happens more effectively than where javascript is used for this kind of tracking

**Comment by LJWatson** [comment]
Based on data from [caniuse.com](https://caniuse.com/#feat=ping): Chrome/Opera and Safari support the ping attribute, Firefox has support behind the browser.send_pings flag, but it's disabled by default), and neither Edge nor IE support it at all.

Should we reintroduce the ping attribute into the HTML5.3 spec?

**Comment by chaals** [comment]
@travisleithead thoughts on this for edge?

**Comment by travisleithead** [comment]
I think Edge is amenable to implementing this in the near future, if that helps 😊

**Comment by shwetank** [comment]
Based on all the comments above, I think we should go ahead with it then.
