### ISSUE TITLE
What to do with Command section?

### ISSUE THREAD

**Issue by chaals** [w3c/html#373]
There is a complex construct that was once meant to include a `command` element that would help define interaction. Is there implementation requirement in there that isn't implemented interoperably?

**Comment by plehegar** [comment]
This is about menu/menuitem/"commands".

http://people.mozilla.org/~prouget/bugs/context-menu-test/test.html

There are some issues, see
  https://bugzilla.mozilla.org/show_bug.cgi?id=676236
  https://groups.google.com/a/chromium.org/forum/?_escaped_fragment_=topic/blink-dev/MkEDloT-yu8#!topic/blink-dev/MkEDloT-yu8

Chrome usage is around 0.27%. ditto for the closing tag:
  https://www.chromestatus.com/metrics/feature/popularity#MenuItemElement

**Comment by plehegar** [comment]
Made a copy of Paul Rouget test (without -moz-) at https://www.w3.org/2016/05/menuitem.html

menuitem works on
- Linux: Firefox (without icons) and Chrome (without icons)
- MacOS: Firefox (with icons), Chrome (without icons, behind flag)
- Windows: Firefox (with icons), Chrome (without icons, behind flag)
- Android: Firefox (without icons)

Imho, given the parsing issue, I recommend to mark this feature at risk, and keep this issue open but reclassified as CR.

**Comment by plehegar** [comment]
See also #274 and https://lists.w3.org/Archives/Public/public-html/2016May/0023.html

**Comment by wseltzer** [comment]
Query how this feature matches user expectations: if users expect that click-menus are controlled by the browser, because that's the way they have been generated to date, they could be misled into putting more trust in a menu action than it warrants. That would have security implications.

**Comment by chaals** [comment]
The security aspect of this went away when we removed `menu`/`menuitem`.

The section is sort of legacy ideas, and should be looked at editorially, but not necessary to do it immediately.

**Comment by chaals** [comment]
Bumping milestone. No real urgent problem has been identified to my knowledge...

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
