### ISSUE TITLE
Consider dropping casual usage of EventSource, WebSocket, BroadcastChannel, etc.

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#388]
These are mentioned in passing in relation to the "message" event. 

`EventSource` is noted as being referenced, but it is only seen in this one place--nowhere else.

We should evaluate whether we really need to drop these references.

**Comment by chaals** [comment]
`EventSource` and `WebSocket` are not so much normative references, since they don't define anything that the HTML spec depends on, as specs with a dependency on HTML, e.g. being referenced in the unload algorithm as things to be cleaned up. But we don't have a smarter way of dealing with that for now and I suspect it would be OK to wait until 5.2 to get one.

`BroadcastChannel` is mentioned once, as an interesting target for message, and isn't defined anywhere.

**Comment by chaals** [comment]
@adanilo can you have a look at this? My inclination is to shift the milestone to 5.2 somewhere…

**Comment by adanilo** [comment]
The reference to [EVENTSOURCE] points at a red warning notice that directs folks to the WHATWG living standard rather than the existing REC at https://www.w3.org/TR/eventsource/ so that needs to be cleaned up at least.

**Comment by adanilo** [comment]
Fixed the reference for EVENTSOURCE in PR#504. We can deal with WebSocket in 5.2. As for BroadcastChannel, it's defined in https://html.spec.whatwg.org/multipage/comms.html#broadcasting-to-other-browsing-contexts but has only 1 implementation in Firefox, where MDN describes it as 'experimental'. There's a Blink 'intent to implement' which dates back a couple of years, with little visible development activity. We should keep an eye on it for the 5.2 time frame.

**Comment by adanilo** [comment]
Closing as done in PR #504
