### ISSUE TITLE
Remove appcache from future HTML specs

### ISSUE THREAD

**Issue by chaals** [w3c/html#40]
It is something that doesn't do what people expect, and while it is used today in combination with web storage and other techniques, we expect it to be rendered truly obsolete by Service Workers.

There is an HTML5 recommendation, showing people how to implement `appcache`, if they want to make 2015-era browsers.

[Firefox has deprecated, and plans to remove it](https://www.fxsitecompat.com/en-CA/docs/2016/application-cache-support-will-be-removed/) in favour of service workers.

At some point, HTML specs should stop recommending its use. Have we reached that point yet?

**Comment by chaals** [comment]
[WG discussion](http://www.w3.org/mid/op.ygv0ajmds7agh9@widsith.local)

**Comment by stuartpb** [comment]
I know @jakearchibald definitely wants to see AppCache kicked to the curb in favor of SW as soon as possible - some really great discussion in [this Bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1237782#c34).

I don't know about removing it from the standard, though. I think there'd definitely have to be at least a stub of a spec left around, so that nothing built on the expectation that AppCache's JS-side APIs exist would break.

**Comment by tBaxter** [comment]
It never worked correctly, is near-non-existent in the wild (because it never worked correctly), is being deprecated and removed in browsers and has a far-superior replacement gaining quick momentum. 

So what's the argument for keeping it?

**Comment by paulbrucecotton** [comment]
The HTML WG had appcache marked "at risk" for HTML 5.0 but the WG decided to keep it when we went to Proposed Recommendation since at the time it was considered interoperable.  See:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=24812#c11
https://lists.w3.org/Archives/Public/public-html-admin/2014Sep/0000.html 

If appcache implementations have been withdrawn since the fall of 2014 then the situation should be re-considered.

/paulc

**Comment by arronei** [comment]
Current plan is to remove appcache from the document and provide only minimal details in the obsolete section of the document.

**Comment by paulbrucecotton** [comment]
Could you document the rationale here for this plan?

Is it simply that the appcache specification will remain available in the HTML 5.0 Recommendation and that the current view is that leaving it in HTML 5.1 is wrong due to possibly the withdrawal of browser support for the feature?

/paulc

**Comment by arronei** [comment]
There are multiple reasons for its removal.
- Lack of consistent inter-operable implementation
- Service Worker has taken off as a more viable solution to appCache
- Browser vendors are considering removing the functionality
- Functionality won't actually be completely "removed" it will be considered obsolete and put into the obsolete section

**Comment by travisleithead** [comment]
Discussed at Web Platform WG May 10th Editors F2F: 
- Basic problem is AppCache doesn't do what developers want.
- SW (v1) is pretty stable. At TPAC 2016, last issues should be resolved.
  - Mozilla implementing.
  - Edge shows positive signs of future implementation

Need to Ask the WG.

**Comment by LJWatson** [comment]
The <a href="https://lists.w3.org/Archives/Public/public-html/2016May/0032.html">CFC to remove AppCache</a> passed, so reopening this for @travisleithead
