### ISSUE TITLE
Support more ISO8601 formats

### ISSUE THREAD

**Issue by christianhujer** [w3c/html#413]
I just wanted to do this:

`Time: <time datetime="2015-08-21T17:30+05:30/PT3H">2015-08-21, 17:30 to 20:30</time>`

and figured out that ISO 8601 datetimes with durations (aka intervals) aren't supported. Instead I had to do this:

`Time: <time datetime="2015-08-21T17:30+05:30">2015-08-21, 17:30</time><time datetime="PT3H"> to 20:30</time>`

I found this surprising and counter-intuitive. I find ISO 8601 datetimes with durations useful. Therefore I suggest to update the `<time/>` element and its supported `datetime` formats to include intervals (the combination of datetimes and durations), just like ISO 8601 does.

**Comment by chaals** [comment]
@christianhujer can you point us to implementations that would use this information if it were valid in HTML? Or even better, implementations that do consume it now...

**Comment by christianhujer** [comment]
There are lots of ISO8601 APIs... I bet the most "natural" way to implement HTML5 datetime is to actually use an ISO8601 API. An ISO8601 API would allow more than HTML5 currently does. Java 8's datetime API for example, and XML Schema. Why doesn't HTML5 simply refer to ISO8601 anyway?

**Comment by chaals** [comment]
HTML doesn't refer to 8601 because you have to go buy it, and because it provides so many possibilities that you can give ambiguous dates, whereas what HTML needs is a far smaller subset.

In terms of implementation I am looking for some things that deal with data found on the "wild" Web, that are products or services being shipped. I'm aware that it is possible to make an API in any language, the question is whether this is important enough that people are using those…

**Comment by paulbrucecotton** [comment]
> HTML doesn't refer to 8601 because you have to go buy it

Without commenting on the requirement for support of other date-time formats, HTML5 does refer to ISO 8601.  See http://www.w3.org/TR/html5/single-page.html#refsISO8601.  And ISO 8601 is in the HTML51 informative references: http://www.w3.org/TR/html51/single-page.html#biblio-iso8601 

And there are several other normative references to ISO documents in HTML51 that are not "freely available" eg. [MPEGTS], [MPTEG4] and [MPEGDASH].

The factor of a specification being "freely available" in just one possible factor in the W3C policy on Normative Reference [1] but the policy also clearly indicates: 

"Any of the factors described in this document are fodder for Director consideration. No single factor is decisive. Different cases will involve different combinations of these factors. The Director may consider other factors not listed in this document as well;".

[1] http://www.w3.org/2013/09/normative-references

**Comment by chaals** [comment]
Just pushed this milestone out. I'm not suggesting there is no need for this, nor that there is no implementation - and since in practice browsers do nothing important with `time`, but other agents consume the data, getting this change to happen is a question of demonstrating the concrete cases for providing and consuming the data, and that they are likely to be implemented…

ping @danbri

**Comment by chaals** [comment]
Is there a concrete use case for extensions beyond intervals, that someone is have trouble with?

If not, I propose renaming this issue to specifically address the lack of a mechanism to describe time intervals. I note that this is a massive practical problem. The following example is made up, but is  pastiche of real-world opening hours. How do we mark it up unambiguously so it an be interpreted?

Opening hours...
Mondays: closed
Tuesdays: 9am - 11pm except Melbourne Cup day (6pm - 2am Wendesday)
Wednesdays: every second Wednesday 10am - noon and 7pm - 1am
Thursdays: 8pm - 2am (8pm - 4am first thursday of every second month)
Fridays: 10pm-4am, 10pm-5am Sunday if the following Monday is a public holiday
Saturday: 4pm-4am - or to 5am if the following Monday is a public holiday
Sundays: noon - 3pm first sunday after a full moon.

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
