### ISSUE TITLE
Rendering range inputs as vertical: should there be normative text (& maybe attribute)?

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/html#456]
See [discussion provoked by Lea Verou's tweet on cool HTML features that aren't implemented](https://twitter.com/LeaVerou/status/737455298575761408).

In short: the rendering chapter [currently recommends that user agents switch to vertical sliders](https://www.w3.org/TR/html51/rendering.html#the-input-element-as-a-range-control) if the element dimensions are taller than they are wide.  No browsers seem to implement it this way.  However, a number of browsers support non-standard attributes that trigger vertical slider widgets.

FWIW, there is also the [`aria-orientation` attribute](http://w3c.github.io/aria/aria/aria.html#aria-orientation) for indicating to assistive tech if a custom slider is vertical or horizontal.  For pure HTML sliders, user agents would need to compute the correct equivalent value to expose to the accessibility APIs.

**Comment by chaals** [comment]
Is this semantics or presentation? If it's not semantic, and I suspect that is the case, then it seems to make more sense to leave it to CSS... As well as following the size allocated, it might make sense when they are inline to follow the writing direction…

That said, what are the non-standard attributes, and what browsers support them?

**Comment by LeaVerou** [comment]
> That said, what are the non-standard attributes, and what browsers support them?
- Gecko: `orient="vertical"` attribute
- WebKit/Blink: `-webkit-appearance: slider-vertical;` CSS declaration
- IE/Edge: `writing-mode: bt-lr` CSS declaration

**Comment by AmeliaBR** [comment]
Re semantics versus presentation

ARIA and the accessibility APIs seem to consider this important semantics. However, as far as I can think the only way it is semantically important is in determining which arrow keys increase versus decrease the value.  It seems (without careful testing) that browsers always allow up/down keys for increase/decrease (regardless of vertical vs horizontal) and map left/right according to writing direction.

For non-standard attributes:

Firefox uses `orient="vertical"` attribute.  WebKit & Blink use the `-webkit-appearance` style property, while IE & Edge match the `writing-mode` style property.

**Comment by chaals** [comment]
It might be useful to put an informative note in the spec describing the various possible ways to do this - for example, pointing to [Lea's comment above listing things](https://github.com/w3c/html/issues/456#issuecomment-224285017). But for getting a common way to do this, we need incubation. I'm leaving this open for the informative comment…

**Comment by chaals** [comment]
Nothing has changed, implementation is still woefully uninteroperable. Should we just say so in the spec? Editorially that is not very hard to do...

**Comment by chaals** [comment]
removed the incubation label - given how many browsers have done this, it seems that the basic functionality and how to express it is clear.

**Comment by chaals** [comment]
A [simple manual testcase](https://chaals.github.io/testcases/vertical-range-manual.html) for the various approaches...

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
