### ISSUE TITLE
Drop in-band metadata handling of track?

### ISSUE THREAD

**Issue by chaals** [w3c/html#461]
Is there any implementation of [tracks exposing in-band metadata](https://w3c.github.io/html/semantics-embedded-content.html#text-tracks-exposing-inband-metadata)?

**Comment by LJWatson** [comment]
Based on info from the <a href="https://developer.microsoft.com/en-us/microsoft-edge/platform/catalog/">MS API catalog</a>, it seems that Edge supportes this, Webkit does with a vendor prefix, and nothing else does.

**Comment by chaals** [comment]
Leaving to check back for HTML 5.2 CR

**Comment by LJWatson** [comment]
It looks like dataCue is <a href="https://developer.microsoft.com/en-us/microsoft-edge/platform/catalog/?page=1&q=DataCue">supported in Edge and Safari (no vendor prefix)</a>.

**Comment by chaals** [comment]
This seems to be implemented, but still need tests. Pushing the milestone back to check, think we need to find some tests to be sure.

**Comment by chaals** [comment]
This still seems to be implemented in a couple of places but not everywhere. Pushing the milestone to re-check later if anything changes. (Google had a [discussion on whether to implement](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/U06zrT2N-Xk) in 2014, which seems to have been inconclusive...)

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
