### ISSUE TITLE
Example code should be in usual easily readable style

### ISSUE THREAD

**Issue by prlbr** [w3c/html#487]
http://w3c.github.io/html/sections.html#the-section-element has an example (example 7) with unusually set code:

```
<html
  ><head
    ><title
      >Graduation Ceremony Summer 2022</title
    ></head
  >
…
```

I think it would be nicer to have it like this:

```
<html>
  <head>
    <title>Graduation Ceremony Summer 2022</title>
  </head>
…
```

If the strange formatting has been caused accidentally by an automatic process, you might want to check if it occured in other places too.

**Comment by chaals** [comment]
I'm pretty sure that it was deliberately written like that - there are various different coding styles used in examples.

I agree that it would make more sense to make examples use a simple style, more or less common - although I don't think we need to go for perfect uniformity.

We can discuss possible coding styles once in the spec.

I'm changing the title and will mark this with an "opportunistic" milestone - i.e. any time you see something of this, feel free to fix a bit.

**Comment by Coder206** [comment]
Could I work on this one?

**Comment by stevefaulkner** [comment]
@Coder206 sure, PR's welcome

**Comment by Coder206** [comment]
I apologize, I must have been overwhelmed with notifications, I just came across this...

**Comment by chaals** [comment]
No problems. You're still welcome to make PRs :)01.10.2016, 00:46, "Coder206" notifications@github.com:I apologize, I must have been overwhelmed with notifications, I just came across this...

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

-- Charles McCathie Nevile - web standards - CTO Office, Yandexchaals@yandex-team.ru - - - Find more at http://yandex.com

**Comment by chaals** [comment]
This is part of editorial conventions for best practice - we'll document it there and close it as a formal issue.
