### ISSUE TITLE
Should <img ismap> coordinates start on the border or the image?

### ISSUE THREAD

**Issue by chaals** [w3c/html#492]
The current specification says

> If the click event was a real pointing-device-triggered click event on the img element, then let x be the distance in CSS pixels from the left edge of the image’s left border, if it has one, or the left edge of the image otherwise, to the location of the click, and let y be the distance in CSS pixels from the top edge of the image’s top border, if it has one, or the top edge of the image otherwise, to the location of the click. Otherwise, let x and y be zero.

in step 3.1 for activation steps for an image as a hyperlink, in the definition of [the `a` element](https://w3c.github.io/html/textlevel-semantics.html#elementdef-a).

This was done for compatibility, but now apparently Blink and Gecko measure from the image itself, while webkit and Edge follow the existing spec.

WHATWG [changed the origin to be on the image always](https://github.com/whatwg/html/commit/87c078dfd7c36d65328db4bb7bfc3c8f411e5997).

Should we do likewise? Any hints from webkit/edge developers?

**Comment by adanilo** [comment]
The issue https://github.com/whatwg/html/issues/438 lacks any context about why, just noting the different behaviors, and a comment about clamping to 0 as well. Would love to hear thoughts from others.

**Comment by chaals** [comment]
Including the border seems to mean that if there happens to be a large border _expected_, whatever calculates the position on the map has to account for that. And if for some reason - user style sheet, CSS didn't load, … - that border isn't applied, the result would be wrong.

As far as I know use of `ismap` is pretty rare these days. But the new Blink/Gecko behaviour does make more sense to me. I wonder if they found significant breakage by doing that, but I would be surprised if they did.

**Comment by travisleithead** [comment]
Locking to the image itself (or in CSS the "content-box") seems very reasonable, making your coordinates much more portable to a variety of different layout styles (where borders, padding, etc. may be applied). I propose we take the spec change, align with the WHATWG, and get a test into WPT for this...

**Comment by prushforth** [comment]
Since the coordinates have to make sense to a server component, which might not have all the info about the page which hosts the image, it doesn't seem right to include borders which aren't actually part of the image.  I will review the guidelines here: https://github.com/adanilo/web-platform-tests#contributing maybe I will be able to pitch in a bit.

**Comment by travisleithead** [comment]
I'm already started on this... but here's a great link to get you started with testing: http://testthewebforward.org/

**Comment by prushforth** [comment]
@travisleithead Thanks!

**Comment by travisleithead** [comment]
At least Edge isn't exactly following the spec. They appear to use the coordinate origin of the CSS box in which the cursor resides. This means that in a map with a border and padding, (no one hit tests on margin thankfully), while the cursor is in the border box, the coordinates are sent relative to the origin of the border box; when the mouse transitions into the padding box, the coordinate origin is reset to the origin of the padding box, and when the cursor transitions into the content box, the origin becomes the content box.

This "resetting" is not per spec. Furthermore because of this resetting, when your cursor moves from the bottom-right of the content box into the padding box, there is a coordinate jump by the size of the padding box edge. So, while the cursor hit-tests within the content box things are interoperable, but any hits outside of that box are likely not :-(

Definitely makes sense just to align with Chrome/Firefox on this...

Web-platform-tests PR created: https://github.com/w3c/web-platform-tests/pull/5118

**Comment by jgraham** [comment]
FYI all the docs are now at http://web-platform-tests.org

**Comment by travisleithead** [comment]
So, we should probably align to what the WHATWG proposes here.
