### ISSUE TITLE
E-mail address 

### ISSUE THREAD

**Issue by superpilou** [w3c/html#506]
Why not help users to end their action when they click on an e-mail address ?
(if no e-mail software is defined on client system, a click on e-mail address has no purpose)

**Comment by chaals** [comment]
`registerProtocolHandler()` is meant to make this possible. I agree that we could explain that better in the spec - if you have concrete suggestions, they would be welcome.

For now I will mark this as editorial, because I am assuming that the appropriate solution is explanatory text, rather than some new feature.

**Comment by superpilou** [comment]
Sorry. Thanks for your answer,

Why not force to display a tooltip ? to send it to clipboard ? 

In 2016, it seems crazy that people couldn't interact with an e-mail address . No exit zone for an e-mail, 

Try something please.

:-)

**Comment by chaals** [comment]
Many tools do provide some behaviour. But requiring a particular one
1. precludes doing something else that some users might find more helpful
2. runs a real risk of picking the wrong thing, and then baking it into the Web for years because people keep relying on it

**Comment by travisleithead** [comment]
@chaals' response makes sense to me.
