### ISSUE TITLE
Upgrade click, dblclick, and contextmenu events to be PointerEvent

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#535]
See discussion: https://github.com/w3c/pointerevents/issues/100#issuecomment-232396438

**Comment by travisleithead** [comment]
This seems like a good idea, and seems to have some consensus and match (at least one) existing implementation.

**Comment by travisleithead** [comment]
The tests show that there is not sufficient interop yet to make the switch from MouseEvent (current described in the spec) to PointerEvent.

* Chrome: `MouseEvent`
* Firefox: `MouseEvent`
* Edge: `PointerEvent`

**Comment by travisleithead** [comment]
Tests are now commited to WPT (https://github.com/w3c/web-platform-tests/pull/5012)

**Comment by cynthia** [comment]
I checked this again, the interop isn't quite there. @patrickhlauke could you comment if this is blocking anything on your side? (And whether or not this will happen at some point?)

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
