### ISSUE TITLE
Add Origin-aware Transferrables

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#543]
As mentioned in the Stockholm TAG meeting (@slightlyoff and I) it was noted that the platform needs an origin-aware version of Transferrable (the structured clone algorithm). Such a mechanism would be used to allow transferrable things only where same-origin destinations apply. (E.g., to workers/service workers of the same origin or frames in the same origin.)

This issue is being opened to track this request.

**Comment by travisleithead** [comment]
Came up again in relation to Web Assembly...(structured clone portability).

**Comment by cynthia** [comment]
@frivoal might have something to say on this.

**Comment by cynthia** [comment]
(apologies, commented on the wrong issue.)

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
