### ISSUE TITLE
Base tag URL modifications should update all relative URLs

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#545]
As reviewed by the TAG, in https://github.com/w3ctag/spec-reviews/issues/118, we have some interest in changing the currently interoperable (but non-sensical) behavior around the base tag--making its changes update all relative URLs.

This issue tracks ensuring the spec is clear, that tests are written, and tracking implementations as they try to see if this change is web-compatible.

**Comment by travisleithead** [comment]
I don't think this needs to be in for 5.2. Moving milestone...

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
