### ISSUE TITLE
Inconsistencies in use of P tags over DIV tags for form fields

### ISSUE THREAD

**Issue by sdrumsalot** [w3c/html#558]
P tags are more suitable for form fields according to the current state of the spec because of the following sections listed below, however, they are not used in the form examples under the forms introduction section (div tags are used there, https://w3c.github.io/html/sec-forms.html#forms-introduction).

At https://w3c.github.io/html/grouping-content.html#the-div-element we have:

> Authors are strongly encouraged to view the div element as an element of last resort, for when no other element is suitable. Use of more appropriate elements instead of the div element leads to better accessibility for readers and easier maintainability for authors.

However, in https://w3c.github.io/html/dom.html#paragraph we have:

> A paragraph is typically a run of phrasing content that forms a block of text with one or more sentences that discuss a particular topic, as in typography, but can also be used for more general thematic grouping. For instance, an address is also a paragraph, **as is a part of a form**, a byline, or a stanza in a poem.

Those two together imply the P tag should be used to separate form fields.

This issue is for the discrepancy in language in the spec. 
Either the "as is a part of a form" should be removed from the paragraph description linked above and the spec updated in all applicable places to use DIV tags (there were a few spots I noticed that was also inconsistent and P tags were being used) OR the forms introduction section updated / reverted to use P tags as it was in 5.1.

Aside, can someone point me to the discussion around the change from P elements to DIV elements for the forms introduction section, what was the rationale there? It was my understanding P would be a meaningful tag whereas a DIV element has no meaning (i.e. P elements could be used like a sub-sectioning element for thematic breaking within a sectioning element whereas a DIV can't. So an automaton could safely assume the contents of a P element are all related to each other as it can only contain phrasing content, but it couldn't with a DIV element as the content model is flow there)

**Comment by LJWatson** [comment]
Thanks for filing this @sdrumsalot

"This issue is for the discrepancy in language in the spec. 
Either the "as is a part of a form" should be removed from the paragraph description linked above and the spec updated in all applicable places to use
DIV tags (there were a few spots I noticed that was also inconsistent and P tags were being used) OR the forms introduction section updated / reverted
to use P tags as it was in 5.1.

Aside, can someone point me to the discussion around the change from P elements to DIV elements for the forms introduction section, what was the rationale
there? It was my understanding P would be a meaningful tag whereas a DIV element has no meaning (i.e. P elements could be used like a sub-sectioning element
for thematic breaking within a sectioning element whereas a DIV can't. So an automaton could safely assume the contents of a P element are all related
to each other as it can only contain phrasing content, but it couldn't with a DIV element as the content model is flow there)"

It looks like we need to clean up the definition of the `<p>` element and the examples in 5.2 (the changes were made in <a href="https://www.w3.org/TR/html51/sec-forms.html#writing-a-forms-user-interface">5.1</a>), as a result of issue #336.

When a thematic grouping is needed for fields in a form, the recommended method is to use the `<fieldset>` element (with a `<legend>` element). The definition for the `<div>` element includes this:

"For example, a blog post would be marked up using  `<article>`, a chapter using `<section>`, a page’s navigation aids using `<nav>`, and a group of form controls using `<fieldset>`."

The `<div>` element is useful for grouping form fields where there is no thematic/semantic relationship - . The definition of the `<div>` element goes on to say:

"On the other hand, `<div>` elements can be useful for stylistic purposes..."

The <a href="https://www.w3.org/TR/html-aam-1.0/">HTML AAM</a> indicates that the `<p>` element maps to a role of text in most platform accessibility APIs. The `<fieldset>` element maps to a role of group, so it offers the more accurate semantic information for a group of thematically related form fields. The `<div>` element is useful when there is no thematic/semantic meaning to the grouping.

**Comment by sdrumsalot** [comment]
Thanks for the quick feedback @LJWatson .
Certain user agent APIs could have a stricter definition for `<p>` being only text, so `<div>` becomes better suited in that regard.

fieldset is for _grouping_ fields together, but the tag usage in question here is for delineating individual fields potentially within a fieldset or at least a form, since these two examples have different semantics:

```
<label><input />
<label><input />
```

semantically different from 

```
<div><label><input />
<div><label><input />
```

In the former, the labeled inputs are related to each other in some way, in the latter, they are not (they are a part of the same form or fieldset, but aren't related to each other).

Aside from this issue here, perhaps all of this together is simply telling us we are missing a new tag `<field>` whose content model would be flow, usage context would be within a form or fieldset, and represents would be something like: "The field element represents a distinct part of a form or fieldset which contains one or more related input controls ...".

The following are the parts of the spec I've identified where the change from `<p>` to `<div>` could potentially apply:

4.4.1
https://w3c.github.io/html/single-page.html#the-p-element
Example 131

4.5.29
https://w3c.github.io/html/single-page.html#the-br-element
Example 301

4.10.1
https://w3c.github.io/html/single-page.html#forms-introduction
Multiple Examples

4.10.4
https://w3c.github.io/html/single-page.html#the-label-element
Example 464
Example 466
Example 467
Example 478
Example 479

4.10.5.3.4
https://w3c.github.io/html/single-page.html#the-required-attribute
Example 480
Example 481

4.10.5.3.9
https://w3c.github.io/html/single-page.html#the-list-attribute
Example 493

4.10.5.3.10
https://w3c.github.io/html/single-page.html#the-placeholder-attribute
Example 494

4.10.7
https://w3c.github.io/html/single-page.html#the-select-element
Example 505
Example 506
Example 507

4.10.9
https://w3c.github.io/html/single-page.html#the-optgroup-element
Example 510

4.10.15
https://w3c.github.io/html/single-page.html#the-fieldset-element
Example 521
Example 522
Example 523

4.10.18.2
https://w3c.github.io/html/single-page.html#submitting-element-directionality-the-dirname-attribute
Example 526

4.10.18.4
https://w3c.github.io/html/single-page.html#setting-minimum-input-length-requirements-the-minlength-attribute
Example 527
Example 528
Example 529
Example 531

4.10.18.8.1
https://w3c.github.io/html/single-page.html#autofilling-form-controls-the-autocomplete-attribute
Example 533
Example 534

4.10.18.8.2
https://w3c.github.io/html/single-page.html#autofill-processing-model
Example 535

4.11
https://w3c.github.io/html/single-page.html#interactive-elements
Example 550

4.12.2
https://w3c.github.io/html/single-page.html#the-noscript-element
Example 566

**Comment by stevefaulkner** [comment]
Still needs completing but won't be done before next milestone so removing it.

**Comment by LJWatson** [comment]
@stevefaulkner what remains to be done on this? Would be good to get this finished before HTML5.2 exits CR.
