### ISSUE TITLE
Try and express img width presentation hint as a css rule

### ISSUE THREAD

**Issue by henke37** [w3c/html#596]
The last paragraph of section 10.4.3. deals with how the width and height attributes are used for the rendering of images. Is it possible to provide a css rule in addition to the prose?

**Comment by jonathanKingston** [comment]
Related discussion here: https://discourse.wicg.io/t/shorthand-for-width-height-css-longhands/1160/27 I drafted a proposal from something @tabatkins wrote many moons ago and produced a demo too.

**Comment by adanilo** [comment]
Good idea, we'll draft something.

**Comment by adanilo** [comment]
On second look, this doesn't seem to be possible. The wording already explains that the attributes map to the dimension properties anyway. Adding any CSS rules isn't possible since the mapping being described is from attribute -> property, not the other way around. The related discussion in WICG is about a new CSS feature proposal, not what browsers implement now. Closing for now, feel free to re-open but I couldn't work out anything useful to add to the spec. that would clarify anything for this case.
