### ISSUE TITLE
update ARIA information for each element

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html#6]
The spec includes informative content about which ARIA role/states/properties it is conforming to use on each element. This content needs to be udpated to reflect the definitions in [ARIA in HTML](https://www.w3.org/TR/html-aria/)

**Comment by prlbr** [comment]
I agree and look forward to the role `group` being listed as allowed on `header` elements in the HTML spec, too.

**Comment by LJWatson** [comment]
@prlbr 

Thanks for your comments. Could I suggest you open a new/separate issue for this?

**Comment by prlbr** [comment]
@LjWatson 
Ah, I'm sure we had the discussion including use cases already and it was decided that `group` would be allowed on `<header>` elements in order to be able to override the implied `banner` role. Hence `group` is indeed listed as allowed on `<header>` here: https://www.w3.org/TR/html-aria/
The purpose of my comment was just to support the idea of making the HTML spec reflect this as well, because the HTML spec is not up-to-date in this case.
Thanks

**Comment by chaals** [comment]
ping?

**Comment by stevefaulkner** [comment]
fixed

**Comment by prlbr** [comment]
Thanks!
