### ISSUE TITLE
<details> "open" attribute

### ISSUE THREAD

**Issue by AndySky21** [w3c/html#600]
There's something I don't understand about the `<details>` element, I hope this is the right place to ask because it could also be fixed in the future (though I don't think it will happen because it would conflict with how the element has been defined as of now).

The spec says, and it's a behaviour commonly honored by UAs supporting the `details` element, that the `open` boolean attribute is to be set or removed when users click on the summary element.

As far as I know there aren't many situations where user interaction actually changes the DOM. Namely, when users click on checkboxes, the control state changes but no "checked" attribute is set on the element itself, though the checked IDL property changes (of course this is valid for all of the form controls, but checkboxes and radio buttons are closer to this case as checked is boolean). 

This is valid for newer tags, too. Visual UAs are expected to show a control bar for `<video>` elements when the controls attribute is present. This bar can also contain a volume control with the option to mute the video. But the spec does not say that UAs have to change the `muted` attribute, also because its presence defines the state of the `defaultMuted` IDL property.

Of course nothing bad can derive from this, but it's a sort of inconsistency. If it's just a matter of CSS, it would be more consistent to have an `:open` pseudo-class for it, corresponding to the open state. And I cannot believe it hasn't been done for legacy issues, because nobody stood against new pseudo-classes like `:required`, `:valid` and so on.

**Comment by adanilo** [comment]
That's a good point, I'm not sure why this behavior was specified. It does seem a bit weird to add attributes to the DOM from UA action rather than JS manipulation. It'd be nice to know the reasoning.

**Comment by SebastianZ** [comment]
For reference, the related description can be found here:

https://html.spec.whatwg.org/multipage/forms.html#attr-details-open

I vote for only changing the IDL property on user interaction to stay consistent with other elements' attributes like [`<input>`'s `checked`](https://html.spec.whatwg.org/multipage/forms.html#attr-input-checked).

Sebastian

**Comment by chaals** [comment]
Actually @SebastianZ the reference for this repo is
https://www.w3.org/TR/html52/interactive-elements.html#the-details-element

**Comment by SebastianZ** [comment]
> Actually @SebastianZ the reference for this repo is
> https://www.w3.org/TR/html52/interactive-elements.html#the-details-element

Yes, sorry! Thank you for the clarification!

Sebastian

**Comment by AndySky21** [comment]
I had to dive into the spec a bit deeper and now I can correct some aspects of my original message.

`checked` on checkboxes and `open` on details are quite different IDL attributes: while the former reflects the "checkedness" of the element, the latter reflects the presence/lack of the content attribute. This last fact is what makes `open` content attribute to appear/disappear from the element itself:

https://w3c.github.io/html/infrastructure.html#reflection

> Some IDL attributes are defined to **reflect** a particular content attribute. This means that on getting, the IDL attribute returns the current value of the content attribute, and on setting, the IDL attribute changes the value of the content attribute to the given value.
> [...]
> If a reflecting IDL attribute is a `boolean` attribute, then on getting the IDL attribute must return true if the content attribute is set, and false if it is absent. On setting, the content attribute must be removed if the IDL attribute is set to false, and must be set to the empty string if the IDL attribute is set to true.

This means that, whenever the script changes the value of an IDL property reflecting a content attribute, UAs are expected to act on the content attribute as well.

Now I can state it almost certainly: `<details open>` is the only known case where user interaction modifies an IDL property reflecting a content attribute. **That** is what makes no sense. It's as if the `src` attribute of an iframe kept track of the URL that the nested browsing content represented by an iframe is navigated to.

As it happens for mentioned interactive elements, the `open` IDL property should reflect `<details>` openness state, while the `open` content attribute should define the element's default openness state.

**Comment by chaals** [comment]
> This means that, whenever the script changes the value of an IDL property reflecting a content attribute, UAs are expected to act on the content attribute as well.
> [...]
>  `<details open>` is the only known case where user interaction modifies an IDL property reflecting a content attribute.

Actually, a bunch of ARIA works in roughly this way, with a near relative being `aria-expanded` - which is possibly where the pattern came from - except that doesn't allow for a "shorthand attribute" - you have to read its value. If there is a CSS pseudo-property like `::open`, then I would be happy removing this, but otherwise it's probably important to be able to do styling. I agree it seems an odd "idiom" - but as a way to provide a CSS styling hook, not obviously **terrible**.

ping @tabatkins

**Comment by AndySky21** [comment]
> Actually, a bunch of ARIA works in roughly this way

What "way"?
Consider that we're talking about an element whose user interaction is handled by the user agent directly.
Should I file an issue on CSS repository too in order to propose `:open` (I suppose the correct syntax should have only one column)?

Anyway, yes, **it is** terrible. It's so terrible that, for required form controls, the `:required` and `:optional` pseudo properties have been created, even if all the styling could be handled with a `*[required]` selector. <del>And yes, I can even understand the use case (radio button lists are required even if only one element has the `required` content attribute, so the attribute selector doesn't catch reality correctly), but it's such a marginal use case that it could arguably justify the effort.</del> EDIT: this doesn't even work, because only elements with `required` match the `*:required` selector, so that's quite useless, or at least analogue to `*[required]`.

**Comment by LeaVerou** [comment]
FWIW, I think it's great that we're moving towards attributes for these things instead of having a discrepancy between IDL values and attributes and I hope `<details>` is the first of many. This confuses novices to no end, as you can verify by a simple search on stackoverflow. It also requires new pseudo-classes for every IDL attribute, whereas if the UA manipulates the DOM, attribute selectors are sufficient. Adding this many pseudo-classes puts a toll on implementors, which could be better spending their time implementing new features and increases the amount of things novices need to learn. Furthermore, the use cases for keeping the DOM separate are very few. In my 11 years of web authoring, I have never encountered a case where the separate IDL values have been useful. I believe when consistency conflicts with usability we tend to favor the latter, right?

**Comment by AndySky21** [comment]
Well, it can be true for `<details>`, but if you just consider form use cases, such as checked checkboxes, you can imagine that content attributes are connected with the `default*` IDL property instead of the ones with the similar name, mainly for the reset algorithm.

**Comment by LeaVerou** [comment]
Checkboxes is exactly the case where I've seen people get immensely confused, and not just complete newbies either. When we added `:checked` to CSS, there were tons of people asking around why can't they just use `[checked]`. There are very few cases where you actually want the default value, and that can be solved with a separate IDL attribute. Anyway, the ship has sailed for checkboxes, but new features can be designed to prevent such confusion.

**Comment by AndySky21** [comment]
I don't actually understand how a thing which is richly documented can still be confusing.

`checked` property does not reflect the `checked` content attribute. Simple as that.

Now, a language, either in programming or in markup, solves confusion with consistency too. May it be appreciated or not, `checked` and `selected` work that way. In those cases the fact is useful for the reset algorithm. `<details>` has no such algorithm as of now, and it probably won't get it in the future, but now that authors have learned how to deal with UA-determined states and attribute, I guess introducing different behaviours increments the mess rather than solve it.

**Comment by AndySky21** [comment]
Well, it can be true for `<details>`, but if you just consider form use
cases, such as checked checkboxes, you can imagine that content attributes
are connected with the `default*` IDL property, mainly for the reset
algorithm.

**Comment by chaals** [comment]
@AndySky21 wrote:

> I don't actually understand how a thing which is richly documented can still be confusing.
> `checked` property does not reflect the `checked` content attribute. Simple as that.

Yeah, except people often don't - in many cases don't really understand how to - read that documentation to understand it. And by and large we who write the specs should be honest that our explanations aren't always that clear in the first place.

Consistency is good, all other things being equal. But they aren't. In particular, IDL attributes reflecting content is a _very_ common thing.

I said earlier:

> Actually, a bunch of ARIA works in roughly this way, with a near relative being `aria-expanded` 

What I meant was that ARIA requires changes to the actual content attribute in order to work.

On the other hand, animation - for reasons similar to form controls being more easily reset - doesn't reflect to the DOM.

We have it both ways in the platform, depending on what we're doing.

**Comment by LeaVerou** [comment]
> I don't actually understand how a thing which is richly documented can still be confusing.

If you are designing any interface that is going to be used by humans (and structured languages are part of that set) you need to stop right now and repeat after me: **People do not read documentation**. This is the first and most basic rule of usability, so get it deep in your head. **People do NOT read documentation**

Even with programming languages, where you can’t avoid it to a degree, the vast majority of people will read the absolute minimum documentation and then go off experimenting.

Documentation is a fix for poor design decisions, but a pretty bad one. Most will not see it, and you have increased the cognitive load for those who will. Do not fix bad design decisions with documentation if you can avoid making them in the first place.

**Comment by AndySky21** [comment]
Sometimes I really ask myself why we still have old useless things like documentation, specifications and the like...
`</sarcasm>`

**Comment by LeaVerou** [comment]
Feel free to complain about how users function, but the users won't change, and it will make you grumpier :)

**Comment by chaals** [comment]
Yeah, sadly Lea is right. We've learned the hard lesson several times on the Web that if you rely on people reading the documentation first, you're doomed to fail, and the price of that is whatever it means that people did things the way they were always going to do them…

So the task is to figure out - make as educated and thoughtful a guess as we can - how people are going to interpret stuff, and how to match that...

**Comment by AndySky21** [comment]
If this is the direction this thread is going to take, I suppose it would be better at this point not to change the current situation. If some authors have decided to implement `<details>`, they could have used the `open` attribute as a styling hook. Such a change would break those uses in a manner difficult to understand/maintain.

**Comment by chaals** [comment]
@AndySky21 I propose that we close this issue with no action. Any objections?

**Comment by AndySky21** [comment]
> If there is a CSS pseudo-property like ::open, then I would be happy removing this, but otherwise it's probably important to be able to do styling. I agree it seems an odd "idiom" - but as a way to provide a CSS styling hook, not obviously terrible.
> 
> ping tabatkins

Before this issue is closed and forgotten, I hoped to see what consequences it could have in the CSS selectors spec draft referenced above. I don't even know if it has been considered, apart from being labelled

The two things are strictly connected. No change is possible without a styling hook, but no CSS pseudo class will ever be inserted if the situation remains as it is now.

**Comment by tabatkins** [comment]
The CSS issue is a red herring.  `<details open>` reflecting the property has been around for years, and authors have come to rely on `details[open] {...}` being a reliable way to style a details element when it's opened.  We can't actually remove this functionality, and so adding a CSS pseudo-class that also matches an open details wouldn't provide anything new.

**Comment by chaals** [comment]
I think @tabatkins is right that developers rely on the attribute-based selector, much as they also seem to like using aria attributes as selectors.

What happens in CSS is pretty orthogonal to what we do in HTML - any follow-up should be there, but I am guessing that the input from @LeaVerou and @tabatkins gives a rough guide for what to expect.

This represents a change in the way we build things, and it **might** be appropriate to ask the TAG whether they think it's a smart one or a bad one - but in this instance I think @AndySky21 is right that the boat has sailed for this particular instance.

Consistency is a good thing. But not the only good thing - and anyway the Web platform is sadly already littered with inconsistent designs, and it seems unlikely we'll fix those while people still use HTML.

So I am closing the issue here based on a lack of support for changing.
