### ISSUE TITLE
Allow usage of `address` element in all contexts

### ISSUE THREAD

**Issue by SaraSoueidan** [w3c/html#606]
I think it would make sense to make the `<address>` element more ‘general’ by allowing it to be used to represent addresses anywhere they are presented—regardless of context; similar to the way elements like `<time>` can be used.

For example, I think it would make sense to use `<address>` to wrap a user's address in a checkout process (e.g. shipping and billing addresses). It makes the element less confusing, in my opinion.

(I know this is not data or maybe the strongest reasons out there to do this, but as an author, I think it would help make the `address` element far less ambiguous.)

Thanks!

**Comment by chaals** [comment]
I doubt that browsers care at all, since they don't seem to do more than style the element.

The question is whether it breaks other things, like search and cataloguing systems. I would personally be surprised if it did, but I think we should do some research…

**Comment by stevefaulkner** [comment]
Agree we need to do some research, will do some mailing list archeology and review pre html5 definitions, also gather some data on actual usage to see what it reflects. will get back to you @SaraSoueidan @chaals

**Comment by stevefaulkner** [comment]
HTML5 definition:

> The address element represents the contact information for its nearest article or body element ancestor. If that is the body element, then the contact information applies to the document as a whole.
> ...
> The address element must not be used to represent arbitrary addresses (e.g., postal addresses), unless those addresses are in fact the relevant contact information. (The p element is the appropriate element for marking up postal addresses in general.)
> https://w3c.github.io/html/sections.html#the-address-element

HTML 4 definition:

> The ADDRESS element may be used by authors to supply contact information for a document or a major part of a document such as a form. This element often appears at the beginning or end of a document.
> https://www.w3.org/TR/html4/struct/global.html#edef-ADDRESS

HTML 3 definition:

> The ADDRESS element requires start and end tags, and specifies information such as authorship and contact details for the current document. 
> https://www.w3.org/TR/REC-html32#address

**Comment by stevefaulkner** [comment]
HTML WG mailing list items relating to address:
https://www.w3.org/Search/Mail/Public/search?type-index=public-html&index-type=t&keywords=%3Caddress%3E&search=Search

WHATWG mailing li items relating to address:
https://www.w3.org/Search/Mail/Public/search?type-index=public-whatwg-archive&index-type=t&keywords=%3Caddress%3E&search=Search

**Comment by craigfrancis** [comment]
As Steve has mentioned, the spec has always said it's the address for the authors of the document, but I've found that many websites use it for postal addresses, in the way that Sara has used it.

Does anyone know of a way to verify this with stats? Maybe someone on the Google/Bing web crawling teams?

And if everyone did use it "properly" how many systems will use the semantics it provides to extract that information? vs if its definition was changed (to how I've seen it been used), how many systems could use it then (e.g. a browser being able to create a contact in an address book more easily, a bit like the old [vCard/hCard microformat](http://microformats.org/wiki/hcard), or the schema.org address for a [person](https://schema.org/Person)?

**Comment by AndySky21** [comment]
Talking about Schema.org, I suppose that the specific author's /
organisation address could be properly marked up with semantic markup such
as microdata or RDFa, while the address tag itself could simply be used to
indicate "this is an address". I'd like to have a look at WebDevData to see
how authors use it.
Note: if there are several pages which simply use <address> for generic
addresses, search engines have learnt not to rely upon this element to mine
organisation address details, I suppose.
Andrea Rendine

**Comment by fvsch** [comment]
Conversely, maybe deprecate the element altogether?

The arguments for allowing wider use (that it’s not currently used according to spec by either authors or UAs, especially bots), if true, would justify deprecating the element as well.

**Comment by AndySky21** [comment]
When the time element was first proposed, it allowed the 'pubdate'
attribute indicating which element was meant to mark the publication date
of an article, but this attribute was later removed.
Choosing to deprecate address now, would mean the same as deprecating time
as a whole instead of removing pubdate.

The fact is, addresses are different from any other piece of data in the
fact that they cannot be easily recognized by data mining tools and similar
technologies relying upon semantically relevant data. An address has no
pattern and can be confused with similar prose.

An address element is useful for this, as it tells the address apart for
the machine. It is semantically relevant markup, and this is exactly the
line followed throughout html5 development.

**Comment by tigt** [comment]
I strongly agree with Sara's proposal. `<address>`'s content model is some hot garbage; it can't contain general author information (such as just the name), nothing about the element's name suggests it has anything to do with authorship, and years of abuse have rendered it unfit for its designed purpose.

For example, Apache's default error documents wrap the server name/version and other information inside an `<address>`, especially if not configured with a webmaster email address. They've been this way for decades.

Web authorship is important — an `<author>`/`<creator>`/whatever element would be more obvious, and not relegate that information to easily rottable dark metadata such as `link[rel=author]` and `meta[name=author]`. (Which _really_ don't work well with web pages that contain multiple articles by different authors.)

If `<address>` is redefined to be more general, one use-case is screen-readers and auditory browsers applying a heuristic to spell out punctuation and digits for clearer comprehension. For example, in a user-agent stylesheet:

``` html
address {
  speak: digits; /* or literal-punctuation */
}
```

I know the CSS Speech properties tend on the side of useless, but [VoiceOver on iOS supports this](http://pauljadam.com/demos/css3speech.html), at least.

**Comment by AmeliaBR** [comment]
We are at the point in time where HTML has achieved wide enough usage that it is not helpful to define semantics in the spec that don't reflect actual usage.  No software can reliably use `<address>` to extract site-ownership information from web pages. So what purpose is there in defining such a restriction in the spec?

The original intended use of `<address>` (to wrap site-ownership information) has mostly been replaced by a page-wide `<footer>`, or by `rel="author"` for articles.  The current accessibility mappings reflect this: page footer gets mapped to `contentinfo`, while an [`address` is mostly treated as simple text](https://w3c.github.io/html-aam/#el-address) with only one API exposing any semantics at all.  This isn't ideal, because footer implies a placement in the source order or layout that is in addition to the semantics, but it seems to be fairly widely used in actual content on the web.

At the same time, however, and for the same reason, I don't think you can just re-define `<address>` to mean "a postal address or location": there is lots of content out there using it as currently specified, to wrap site ownership / article authorship information that might not include a postal address, or even an email address.

So I agree that the most important first step would be to assess how the element is currently being used.  From that data,  decide whether there are any consistent enough semantic patterns to make the element useful.

**Comment by jina** [comment]
In all my years of being frustrated with the super specific use of this element, it never occurred to me to simply suggest the definition be broader. Thanks Sara for taking initiative!

**Comment by stevefaulkner** [comment]
@AmeliaBR wrote:

>  there is lots of content out there using it as currently specified

data supporting this would be useful.

I did a quick grep of 7000 pages from the latest [webdevdata](http://webdevdata.org/) data set, to get a feel for how `<address>` is being used.
[Raw results](https://dl.dropboxusercontent.com/u/377471/address.html) are available for perusal.

I haven't done any analysis or drawn any conclusions as yet, happy for others to do so.

**Comment by AmeliaBR** [comment]
> data supporting this would be useful.

Thanks for starting the data fetch, @stevefaulkner.  I should have said "lots of content using it for things other than actual addresses", which may or may not fit the current spec definitions!

Quick and qualitative skim of that data dump shows three major classes of usage that show up repeatedly:
- site ownership/contact information that also includes an address  (company addresses in site footer or contact us block)
- article author information (author name with link to author page)
- copyright information (not contact information, not address, but I guess it's info about site ownership? I wonder which template/documentation led to this usage pattern?)

There may also be lots of usage for generic postal address: it's hard to tell without context whether the actual addresses are for the main site owner or not.

Not sure whether a useful semantic can be extracted from those these distinct patterns.

**Comment by AndySky21** [comment]
Well it may or may not be conclusive depending on the specific addresses
highlighted in data, but it appears to be used for a really broad concept
of "contact information", where it can also consist of a
person/organisation name (in the era of digital identity,  even a name can
be used to identify a subject).

**Comment by stevefaulkner** [comment]
Have a look at the schema.org address http://schema.org/address
It may be practical to align the definition with this.

**Comment by stevefaulkner** [comment]
In the schema for [PostalAddress type](http://schema.org/PostalAddress) 
some examples use the `address` element: example 11

```
 <address itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
    <span itemprop="streetAddress"> Unit 42, Land of Bargains Shopping Paradise, 12 Highway 101</span>,
    <span itemprop="addressLocality">Boston</span>,
    <span itemprop="addressRegion">MA</span>, <span itemprop="addressCountry">USA</span>
  </address>
```

**Comment by chaals** [comment]
I'm not sure that it is a good idea to align with Schema.org here. @SaraSoueidan suggested making this an address, which I guess _could_ mean that alignment, but I think it is clearer that it is "contact information" than **definitely** a physical address.

I'm also not sure we should remove the specified semantics that it relates to the author/owner of the page it is found in. That seems - at a first glance - to hold reasonably strongly.

**Comment by AndySky21** [comment]
In light of real world data, I agree with @chaals. Of the 2 aspects assumed by the spec, the fact that address tag contains data related to the page author or site-relevant person/organisation seems to be the most adhered upon, while the fact it is a real address seems to fade.
And this is unfortunate, as I hoped it could be used to highlight a real address which, as I said, is difficult to recognize by a machine.

I would suggest that address is used for contact information, with a guideline stating it should include as many pieces of information as possible.

**Comment by chaals** [comment]
In fact I think we would do better to put pointers into the "common microsyntaxes" section, to schema.org as a generic way to mark up postal addresses, and give examples that use address for the contact information according to the current semantic and generic elements for e.g. the location of an event.

**Comment by iandevlin** [comment]
Perhaps we should rename `address` to `contact`. Although perhaps we'd have the same issue then as people would be using it to wrap contact forms.

I also think that it should stay as it is. A lot of misuse is caused by people not reading the specification and making assumptions.

**Comment by stevefaulkner** [comment]
I have updated the [raw results](https://dl.dropboxusercontent.com/u/377471/address.html) data dump to cover 1220 matches in 190 files. 19342 files searched.

A word of caution with the results, for the most part the samples are of web site home pages only.

**Comment by unor** [comment]
Related question on Stack Overflow:  
_[Don't use <address> for address](http://stackoverflow.com/q/28054636/1591669)_

**Comment by AndySky21** [comment]
I guess Ben75's answer says all. And the question was badly formed.

The address element has been used incorrectly throughout the years? Probably yes. This is not for the spec being ridiculous about that.

Address is not meant for generic addresses. There is no blasphemy in that, because `<address>` conveys an additional piece of information: "this is part of the contact info for the subject responsible of the above content, possibly the person's/organisation address".

I will make an example of this reasoning.The `<ul>` element denotes an unordered list. It can be used for to-do listings, tables of contents, participants in a competition, topics discussed in a convention. Well, it appears I just made an unordered list. But I would have never used an `<ul>` element, because it isn't the context `<ul>` is meant for.

For what I understand, the only problem now is to identify the most common misuse and, if it seems reasonable, to incorporate that misuse into the correct use for the element.

**Comment by stevefaulkner** [comment]
Coming back to this: 
1. After searching, I could not find any implementations of the algorithm for delineating `address` information scope based on its position in the DOM. I consider this should be dropped as it adds unnecessary complication to what the address element represents without adding practical utility to its semantics. Can anyone provide any data on the algorithms use?
2. While the current definition of the address element is adhered to in some cases. I cannot see why widening its definition would have a detrimental effect on current usage as a wider definition will be a include content currently included in the `address` element. Please do provide feedback if you have information that shows it would be detrimental.
3. I suggest a much more robust and useful method of providing the desired semantics for the specifics of address information (for consumers of such) is to augment HTML markup with Microdata, RDFA etc. This advice should be included in an updated definition of the element.

Anyway I will commit a proposed updated definition to the html 5.2 editors draft for review and comment.

**Comment by chaals** [comment]
I agree that scoping `address` to a section rather than the page is something we should drop.

If we widen the semantic so it covers any address, as well as "information about the owner of the page" - a lot of which is _not_ a physical address, I think we will unhelpfully overload the semantics, making the element ambiguous. I think that's actually a bad idea.

I agree we should point to RDFa/microdata/etc for specifying a physical address. Even where that's the address related to the page owner, e.g. for a restaurant website, it's helpful to provide the more detailed information for data crawlers such as search engines.

**Comment by patrickhlauke** [comment]
Perhaps a bit radical, but: what about dropping `address` altogether? Is there any real-world advantage at the moment to the use of the element in its vague current form that is not better fulfilled by more strict/structured RDFa/microdata/etc ?

**Comment by stevefaulkner** [comment]
> If we widen the semantic so it covers any address, as well as "information about the owner of the page" - a lot of which is not a physical address, I think we will unhelpfully overload the semantics, making the element ambiguous. I think that's actually a bad idea.

a bad idea for who?

**Comment by stevefaulkner** [comment]
I have sketched out a modified `address` element definition: https://stevefaulkner.github.io/address-element/index.html
review at your leisure

**Comment by AmeliaBR** [comment]
Thanks for getting this to the next stage @stevefaulkner. 

I like your overall broad definition, it covers most existing uses and the common understanding of what an "address" is.  And any example that involves Lola the Cat is A+ for me.

However, it doesn't cover the common use of `<address>` to mark up copyright attribution without contact information (as detected from your [data dump](https://github.com/w3c/html/issues/606#issuecomment-250981769)).  I don't necessarily consider that an objection, but it is something to be aware of.

What did you think about explicitly mentioning address-related metadata schemes (& linking to more info)?  An extra paragraph like: "The parts of the address can be further identified for processing by adding metadata attributes to child elements…".  And then show one of the examples marked up.

Might also want to link to the section about `rel="author"` for replacing the old understanding of `<address>` as authorship/ownership information.

Finally, some copy editing: 

- "a person, people or organization" is confusing. It expands as "a person, a people, or a(n) organization".  "A people", aka a national/cultural group, isn't something that has a contact address.  "A person, group of people, or an organization" would be explicit. But at the very least add "an" in front of "organization", so the article "a" isn't shared by every item in the list.

- The bit about a "living entity" is unnecessary obfuscation.  How about "a means of identifying the person(s) or organization".

- The "W3C on Twitter" example seems to have some extra text (plain text URL outside of the link) that shouldn't be there.

**Comment by ghost** [comment]
Like @SaraSoueidan, my answer doesn't necessarily represent data but personal experience.

Every country has its own formats (yes, plural) for postal addresses. Plus, there are many kind of addresses (IP addresses, P.O. Box addresses, office numbers inside an organisation, etc...). An address is a very common piece of information. Having an element named `<address>` for what we humans call an address just makes sense. Limiting its current intended use to information about an author might make any other addresses look contrived and/or misrepresented in markup.

I would suggest to use `rel=""` to specify the relation between an address and the piece of information it belongs to. (Not sure if I would limit it to _author_, as I also thought about `rel="shipping"`, `rel="destination"`, or `rel="office"` as examples).

Regarding the usage of an `<address>` element for grouping form controls, I think it is not a good idea because there is already another element for that: `<fieldset>`.

**Comment by kevinmarks** [comment]
Sara's original use case is covered well by h-card, which maps the fields of vcard and so can be used for physical address, contact info and so on. The de minimus form allows name and URL with a single class. 
Scoping works with other microformats, so the author of an h-entry can be a h-card, or the location of an h-event. 

Marking up address with h-card works too, as microformats are class based and so orthogonal to elements. 

http://microformats.org/wiki/h-card

**Comment by stevefaulkner** [comment]
@AmeliaBR 
> However, it doesn't cover the common use of <address> to mark up copyright attribution without contact information (as detected from your data dump). I don't necessarily consider that an objection, but it is something to be aware of.

right, this usage seems to have little to do with location/contact info and should be discouraged.

> What did you think about explicitly mentioning address-related metadata schemes (& linking to more info)? An extra paragraph like: "The parts of the address can be further identified for processing by adding metadata attributes to child elements…". And then show one of the examples marked up.

I had intended to do so, but couldn't get the right words together at the time, so left it off for now, you are anybody please feel free to provide some verbiage.

> Might also want to link to the section about rel="author" for replacing the old understanding of <address> as authorship/ownership information.

agreed

will fix edit issues you raised.

**Comment by stevefaulkner** [comment]
Have commited changed definition to editors draft, further feedback welcome!
https://w3c.github.io/html/grouping-content.html#the-address-element

**Comment by stevefaulkner** [comment]
closing as fixed, feel free to re-open or add further comments on closed bug

**Comment by chaals** [comment]
I'm uncomfortable losing the semantic that this is contact information for *the page* or *owner of the page* - as fluid as that statement is. If I'm the only one, I won't reopen, but if someone else is uncomfortable about this I'd encourage you to say so and discuss further...
