### ISSUE TITLE
Continue to define xml:base as [not] for HTML docs?

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#748]
Do we need to continue to define xml:base? It is [already] expressly **not** for HTML documents, only HTML-in-XML elements, and at that point you're in XML land where [of course] the attribute is supported

This [short] section is also not in the WHATWG version...

Would love to get a WG decision on this.

**Comment by travisleithead** [comment]
My inclination is to drop the section. For reference this is all it says:

> The xml:base attribute is defined in XML Base. [XMLBASE]
>
>The xml:base attribute may be used on HTML elements of XML documents. Authors must not use the xml:base attribute on HTML elements in HTML documents.

**Comment by zcorpan** [comment]
whatwg/html@56f4346ec71b2dc138038ce6512b626d6c563e00

The point was to remove support in XML land as well.

**Comment by chaals** [comment]
So we should probably look at what people do in XML land… @liamquin do you happen to have an idea about where we should look?

**Comment by liamquin** [comment]
On Mon, 2017-02-13 at 17:42 -0800, chaals wrote:
> So we should probably look at what people do in XML land… @liamquin
> do you happen to have an idea about where we should look?

xml:base is supported in XML (outside of XHTML), and the base-uri
property is supported e.g. in (at least modern versions of) XPath to
access the base URI of any node, whether set normally or overridden
with xml:base.

I suspect most people using XML in an HTML environment think of HTML as
a rendering technology and won't care what a Web browser does with
xml:base. The spec doesn't seem to say what happens but implies that
the XML Base spec is to be supported (with a normative reference). I
don't see any value in saying it MUST not be used on HTML documents
rather than saying it's ignored, but the spec doesn't seem to say what
should happen if someone does use xml:base in HTML -- is xml:base
processing to be performed? I'm guessing not. So that at least should
be stated explicitly.

DOM Level 3 does require support for XML Base. So deprecating or
ignoring or forbidding it altogether would presumably be a "wilful
violation" of DOM - https://www.w3.org/TR/DOM-Level-3-Core/

**Comment by travisleithead** [comment]
Followed @zcorpan's above link to this thread with the details on the removal from DOM. Seems like it had implementor agreement: https://www.w3.org/Bugs/Public/show_bug.cgi?id=20976

I (or someone) should add test to see how this behavior change is going in implementations. It might be nice to at least change the note to mention the reality of what implementations are attempting, and note what processing is done, if anything. Not urgent, moving milestone.

**Comment by chaals** [comment]
[Simple test](http://chaals.github.io/testcases/xml-base-manual.html) suggests that `xml:base` is not supported in HTML by Blink/Edge/Firefox/W3C validator... **If** the test is sound, I think it would make sense to remove the section from the HTML spec. Alternatively, we should say it **must** not work in (non-xml) HTML.

What happens in real XML seems beyond the scope of this spec. @liamquin ?

**Comment by zcorpan** [comment]
@chaals your test is using an attribute with local name "xml:base" in no namespace, which is different from local name "base" in namespace "http://www.w3.org/XML/1998/namespace". You need `setAttributeNS` to get the xml:base that potentially has an effect on processing.

See https://html.spec.whatwg.org/multipage/dom.html#the-lang-and-xml:lang-attributes for analogous attempts at making this confusing topic clear for lang/xml:lang :-)

What happens in XML is in scope for WHATWG HTML at least.

HTH

**Comment by chaals** [comment]
@zcorpan:

> You need setAttributeNS to get the xml:base that potentially has an effect on processing.

Oh. Yes - thank you.

I will look at this again next week, if nobody beats me to it.

Thank you for the correction :)

**Comment by liamquin** [comment]
On Mon, 2017-12-18 at 07:01 -0800, chaals wrote:
> [Simple test](http://chaals.github.io/testcases/xml-base-manual.html)
> suggests that `xml:base` is not supported in HTML by
> Blink/Edge/Firefox/W3C validator... **If** the test is sound, I think
> it would make sense to remove the section from the HTML spec.
> Alternatively, we should say it **must** not work in (non-xml) HTML.
> 
> What happens in real XML seems beyond the scope of this spec.
> @liamquin ?

It's fair to define what happens in an HTML agent if xml:base is seen
in both the HTML and XML syntax, and what if base and xml:base are both
given. It'd be unhelpful to define anything that conflicts with the XML
Base specification itself of course.

-- 
Liam Quin, W3C, http://www.w3.org/People/Quin/
Staff contact for Verifiable Claims WG, SVG WG, XQuery WG

Web slave for http://www.fromoldbooks.org/

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
