### ISSUE TITLE
HTML 4 system identifiers are accidentally non-conforming in HTML 5.1

### ISSUE THREAD

**Issue by tstarling** [w3c/html#754]
Someone has replaced all the http URLs with https URLs in the syntax section of the HTML spec, which is presumably an error when applied to matching legacy system identifiers.

https://www.w3.org/TR/2016/REC-html51-20161101/syntax.html#the-doctype
https://www.w3.org/TR/2016/REC-html51-20161101/syntax.html#the-initial-insertion-mode

There is also an incorrect reference to the HTML namespace as having an https URL in a non-normative box in https://www.w3.org/TR/2016/REC-html51-20161101/syntax.html#parsing-html-documents

Two of these three sections were fixed in June in 62e07769f9bd1a2f934439b14a37ae82338e4b3d but this was not backported to HTML 5.1.

**Comment by tstarling** [comment]
Also, in the O'Reilly public identifiers, the ASCII apostrophe was replaced with U+2019

**Comment by travisleithead** [comment]
@Chaals, all this feedback from the 5.1 spec is addressed in the editor's draft. AFAIK, we shouldn't be modifying the 5.1 recommendation. What's your take on back-porting these changes and re-publishing? (Or issuing errata or something?)

**Comment by tstarling** [comment]
The spec says "Errata for this document are recorded as [issues](https://github.com/w3c/html/issues).". The [W3C process document](https://www.w3.org/2017/Process-20170301/#errata) says 

> Readers of the Recommendation should be able easily to find and see the errata that apply to that specific Recommendation.

A list of issues open which has not been reviewed by the WG, with no indication as to what version of the document they apply to, and in which issues closed in the editor's draft are removed from the list, does not meet the W3C requirements for an errata page.

Once a proper errata page is created, you then have to create an edited recommendation. Since this is a substantive change, you have to "show that the changes to the document have received wide review" before it can be republished as the new HTML 5.1 recommendation.

That's what I'm suggesting that you do. It's my understanding that the reason W3C continues to publish HTML specifications is because it believes that, by having a review process, it can produce a higher quality of document than what you get from the nightly WHATWG snapshot. It would be a bit of a joke if W3C can't even correct the most glaring substantive errors in the current HTML recommendation.

It doesn't really matter to me that it's fixed in the editor's draft, since the editor's draft is not making a claim of high quality. If I wanted something that was published daily without review, I would use the WHATWG specification.

**Comment by chaals** [comment]
This doesn't match an HTML 5.2 milestone because the only issue is whether the HTML 5.2 spec is sufficient for people to refer to or whether there is value in publishing an update of an old version in the interim.

**Comment by ZoeBijl** [comment]
Is it a breaking issue? In other words, are those system identifier now invalid? If not, I don’t see why the WG should go through the trouble of publishing a 2nd edition (with all the new links associated with that) instead of waiting another 5-6 months.

**Comment by agcolom** [comment]
I'd be inclined to address the issue as part of the 5.2 recommendation, unless it is crucial to have it fixed in the 5.1 recommendation via a 2nd edition.

**Comment by agcolom** [comment]
Also, I'm not actually seeing any broken link... Could someone please point out what actually is broken (or is it that https is now supported and this is no longer an issue?). Thank you

**Comment by LJWatson** [comment]
@agcolom I believe the problem is that in 5.1 the system identifiers included in examples (like the doctypes) use https:// instead of http://. The concern is that people reading this section could end up using an incorrect system identifier - though I'm not sure what the real-world implications of doing so would be (an invalid system identifier doesn't trigger quirks mode AFAIK). 

It's definitely an error and it is one we should fix. But I don't know whether the real-world impact is sufficient to require an update to 5.1 (which is likely to land two/three months ahead of 5.2). On the flip-side, publishing an update to 5.1 would probably take minimal work.

**Comment by arronei** [comment]
We should always be moving forward. I think we should publish a 5.2 and let 5.1 be replaced. If we go back to 5.1 where do we stop? There are many other issues with 5.1 that we probably should consider fixing but we decided to move to 5.2.

**Comment by aardrian** [comment]
Is there any evidence since these were published in November what the impact has been?

And then, based on that evidence, is W3C willing to risk an even greater impact (at the existing rate) by the time 5.2 is released?

I do not have enough information to have an informed opinion, but as far as uninformed opinions go I suspect this can be tabled for the 2-3 months between publishing an update and 5.2 being released. Unless, of course, the total effort to update 5.1 is less than the effort expended here already.

**Comment by tstarling** [comment]
There's no real-world impact because nobody uses this standard anymore, for reasons that are becoming increasingly obvious. Apparently nobody even bothered to review a 5.0 -> 5.1 diff before I did so in December, and there's no evidence that anyone has done so since then. I've always found that working with an upstream on a minor bug is a good way to get a feel for how the project works, and on that basis, I don't plan on using HTML 5.2 in my library. The next update will be a switch from 5.1 to the WHATWG spec. The reason is that you're not attempting to achieve a higher quality in the recommendations than in the drafts, so there's no point in using the recommendations.

**Comment by aardrian** [comment]
> There's no real-world impact because nobody uses this standard anymore, for reasons that are becoming increasingly obvious.

Well, the first statement is demonstrably not true (as I see non-zero numbers of people reference it often) and so the second part of the statement, being dependent on the first, is not obvious.

If you have *evidence* of impact (per my request above), please share.

**Comment by agcolom** [comment]
@tstarling I don't want to be running off topic here, however, I can assure you that I am in the process of reviewing the 5.2 documentation... with planned call with the core editors as soon as the review is completed (hopefully another 2 weeks max).

**Comment by IanPouncey** [comment]
I am in agreement with @LJWatson. If this is something that can be changed with minimal effort then it should be; accuracy is important. However, the lack of real world impact means that if it takes more than publishing drafts and sending uncontested emails at the right time in the process it probably isn't worth it.

**Comment by jasonkiss** [comment]
I'd like to take up the other question that @tstarling raised of how errata are recorded and presented.

As has been noted, the spec states, in its very top section, that "Errata for this document are recorded as issues." This is repeated in the "Status of this document" section where it's additionally noted that "The latest HTML editors' draft shows the current proposed resolution of errata in situ." This is a helpful addition. 

However, in order to understand what errata have officially been acknowledged and how they've been resolved, as best as I can tell, the onus is on readers of the specification to review all issues filed against the spec in GitHub, of which there can be very many, and then review the latest editors' draft to see if and how any of those issues have been addressed. 

I have to agree that this is not a way to easily find and see the errata that apply to the Recommendation.

I'm not sure what the best solution is, but perhaps something of a living errata document could be maintained, and at appropriate intervals finalised and incorporated in an updated edition of the spec?

**Comment by LJWatson** [comment]
@jasonkiss 
When changes are made to the spec, we note them in the [Changes](https://www.w3.org/TR/html51/changes.html#changes) section. If we publish HTML5.1 2nd Edition, the change to correct this issue would be noted there.


That said the blurb in the header of [HTML5.1](https://www.w3.org/TR/html51/) should point to an Errata section in the spec (as it does in [HTML5](https://w3.org/TR/html5/).

So if the WG decides to publish the update to HTML5.1 (#874), I suggest that we:
* Include the change in the Changes section;
* Add an Errata section to the spec;
* Change the header text to point to the Errata section.

**Comment by jasonkiss** [comment]
Thanks @LJWatson.

**Comment by cynthia** [comment]
I got a bit too trigger happy with this one - until I know exactly what I should and should not touch I've reverted the commits for the time being. (I can revert the revert [...] if the patch looks good enough - I'm not sure what the process is for updating an already frozen spec.)

**Comment by siusin** [comment]
With the updates in the current Editors' Draft (ED) of [HTML5.1 2nd edition](https://rawgit.com/w3c/html/html5.1-2/single-page.html), this issue has been addressed. We will publish a new CR of HTML5.1 2nd edition this week to make sure the stable version of HTML 5.1 does not include this error.

**Comment by LJWatson** [comment]
#971 has the CFC to move HTML5.1 2nd edition to Proposed Recommendation.
