### ISSUE TITLE
add warning about use of autofocus attribute

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html#762]
https://w3c.github.io/html/sec-forms.html#autofocusing-a-form-control-the-autofocus-attribute

**Comment by ZoeBijl** [comment]
- “assitive technology” → “assistive technology”
- “disabilites” → “disabilities”

Furthermore, this sentence is a bit odd (and 39 words long):

> Users of assitive technology can be adversively affected because its use overrides the default behaviour of assistive technology to display content at the top of a document in the viewport or announce content from the start of the document.

Maybe something like this:

> Its [autofocus attr] use overrides the default behaviour of assistive technology to display content at the top of a document in the viewport or announce content from the start of the document. This can adversively affect users of assistive technology.

Or something like this:

> Its use overrides the default behaviour of assistive technology (AT) which can adversively affect users. By default, AT displays content at the top of a document in the viewport _or_ announce content from the start of the document.

**Comment by yatil** [comment]
I wonder if browsers should be required to provide an user option to disable autofocus. It might be useful to list some of the (more) in  valid use cases for autofocus, like a page who only displays a search form or selecting the username field after clicking a login link to help developers/ux designers decide if they want to use it.

**Comment by stevefaulkner** [comment]
@MichielBijl thanks have now fixed the typos and added punctuation to try to make the text more palatable.
@yatil have added following:

> User agents should provide a method for users to disable the autofocus attribute behaviour.
https://github.com/w3c/html/commit/a8f8406faa078c60e845dd4e397a2875cd0b49a6

> It might be useful to list some of the (more) in valid use cases for autofocus, like a page who only displays a search form or selecting the username field after clicking a login link to help developers/ux designers decide if they want to use it.

working on it.

**Comment by fuzzbomb** [comment]
Having advice like this in the HTML rec would be very useful indeed for web application maintainers.  Requests for autofocus on text fields <a href="https://www.drupal.org/project/issues/search?issue_tags=keyboard%20focus">crop up time and again in the Drupal project</a>, and we keep having to justify our objections to it.

The part about "User agents should provide a method to disable the autofocus" is especially useful, because we'll be able to review which UAs have implemented it.  If enough A-list browser/AT combinations let users disable it, then we'd be able to say "fine, let's use the autofocus attribute".
