### ISSUE TITLE
Add practical restrictions to location.replace to match implementations

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#780]
(Edge is now aligning on this--previously it matched the spec--so I figured it was time to get this documented in the HTML spec to match...)

@Domenic @bzbarsky

The spec currently says that `location.replace` does no security checks. However, this is not strictly true. In Chrome and Firefox, I observe that these browsers seems to be somewhat following the rules for **allowed to navigate** (sans the presence of the sandbox flags). E.g.,

The *entry settings object's browsing context is **allowed to navigate** (ignoring the sandbox related flags) the Location object's associated Document object's browsing context.

I'm not sure **allowed to navigate** (ignoring sandbox related flags) wholly captures what I've tested, so here are the specifics:

<ul>
<li>when same-origin anything goes
<li>when cross-origin:
    <ul>
     <li>an auxiliary browsing context is allowed to be navigated (but not any of the auxiliary browsing context's descendant browsing contexts)
      <li>a descendant browsing context is allowed to navigate the top-level browsing context, but none other of its ancestor browsing contexts
      <li>a browsing context is allowed to navigate any of its descendant browsing contexts.
     </ul>
</ul>

(* I'm using entry settings object above, which I think is correct as there should be no difference between incumbent and entry when trying to manipulate cross-origin browsing contexts... 'course I'm still new to this terminology, so I might not have it right yet...)

**Comment by bzbarsky** [comment]
Hmm.  So what Gecko apparently has (and I had completely forgotten about this, actually, even though I've obviously seen it before based on blame!) is that any attempt to navigate a browsing context goes through the following algorithm (which is in fact independent of "allowed to navigate" and "familiar with"):

1.  If the browsing context being navigated is toplevel, allow.
2.  If the hidden "browser.frame.validate_origin" preference is set to false, allow.
3.  If there is no current settings object allow.  This part is moderately nuts, because it uses _extremely_ non-local state: this check is in code that can be called from any navigation for any reason, and whether there is a current settings object or not depends on ... stuff.  In practice, when under a call to `location.replace` there is one.
4. If the origin of the current settings object matches the origin of the active document in the browsing context being navigated, or the active document in any of its ancestor browsing contexts, allow.
5. If we got here, deny.

Step 1 explains the "auxiliary browsing context can be navigated" and "descendant can navigate its toplevel" bits.  It would also explain why you can navigate your opener (or your ancestor's opener), if it's toplevel, etc.

Step 4 explains why same-origin navigations work, as well as why a browsing context can navigate any of its descendants (because it matches itself during the ancestor walk).  Note that the actual behavior is not quite the same as what @travisleithead describes (e.g. you can navigate a non-top-level ancestor, as long as it has an ancestor that's same-origin with you).

So really, this is more like the "familiar with" rules than the "allowed to navigate" bits, I think, but a bit less restrictive.

Two comments from this code that might be relevant.   First, the ostensible purpose of the code (slightly edited into spec terminology):

    // This method checks whether the caller may load content into
    // this browsing context . Even though we've done our best to hide windows
    // from code that doesn't have the right to access them, it's
    // still possible for an evil site to open a window and access
    // frames in the new window through window.frames[] (which is
    // allAccess for historic reasons), so we still need to do this
    // check on load.

This comment is a more recent addition than the code itself, added when we added the 
equivalent of "familiar with" in <https://bugzilla.mozilla.org/show_bug.cgi?id=103638>.  The original source of the code was fixes for https://bugzilla.mozilla.org/show_bug.cgi?id=246448 which does seem to be what the comment is describing.  So the goal is in fact to prevent navigation of subframes of a cross-origin auxiliary browsing context.

Second, the part about checking the current settings is commented with:

    // Note - This check is not necessarily sensical.

Anyway, the current settings thing can be solved in the spec by having location.replace just examine its current settings.  So that part is not a problem.

One question, @travisleithead: you mention location.replace, but what about the location.href setter?  In Gecko, it's subject to the same restriction, for the same reasons...

Also, these checks in theory apply to targeted links, but in practice that happens async in Gecko and has no current settings anyway, so isn't affected by this check.  The check also applies to window.open() calls, including targeted ones, and I expect it may be relevant there, except those are also subject to "familiar with" checks on the targeting, and I think anything that passes "familiar with" will also pass the checks I describe above.  So I _think_ in practice location.href setter and location.replace are the only ways to observe this check...

**Comment by domenic** [comment]
I think the important first step here is to write web-platform-tests. Those will be required for any spec change anyway, and will clarify what we should spec. I am especially skeptical that we should introduce another entry settings object dependency here.

I'd suggest working on compiling a list of test cases where you think the result should be allow/deny. Then we can review them for completeness. Then you can work on turning them into web-platform-tests. Then we can compare the results with all browsers and find an appropriate intersection semantics. Only then should we contemplate updating the HTML Standard.

It sounds like the list of test cases might be a matrix of:

- Same-origin vs. same-origin-domain but not same-origin vs. not-same-origin
- Origin check is applied to the Window being navigated against the entry settings object vs. incumbent settings object vs. current settings object vs. relevant (I believe they can all be different)
- Auxiliary vs. descendant vs. auxiliary's descendant vs. non-top-level ancestor vs. top-level ancestor
  - These may involve additional tests where some browsing contexts in the chain are same-origin and others are cross-origin

Is that missing anything?

**Comment by bzbarsky** [comment]
> I am especially skeptical that we should introduce another entry settings object dependency here.

Agreed.  In particular, entry != incumbent, unlike what @travisleithead said.  I _think_ for cross-origin objects incumbent == current, generally.  In the document.domain case you can be in the "same-origin" case but _still_ fail this check in Gecko, I think, because Gecko uses current here.  It would involve calling your "replace" method on the "location" object from the other page which is not-same-origin with you but is same-origin-domain...

**Comment by travisleithead** [comment]
I'll see about generating these test cases. 

Note: Edge 15 will be different from Edge 14, as we've already implemented some of these restrictions over our prior permissive behavior.

**Comment by mikewest** [comment]
This came up again in the context of https://github.com/whatwg/html/issues/2757. I'd note briefly that both WebKit and Blink do "same origin-domain" checks when assigning to things like `location.href`. I slapped together some WIP tests at https://github.com/w3c/web-platform-tests/pull/6243 to show that behavior.

**Comment by bzbarsky** [comment]
> I'd note briefly that both WebKit and Blink do "same origin-domain" checks when assigning to things like location.href

At least in some cases.  But not other cases.  What's needed here is a spec; a good start would be clear descriptions of what various UAs actually do, like the one I provided for Gecko above.

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
