### ISSUE TITLE
idea:appendchild can directly append childNodes or html code

### ISSUE THREAD

**Issue by annopnod** [w3c/html#813]
# Exsimple
**Old**
var container = document.getElementById("app-data");
var childNodes = toDom(songlist);

for (var i = 0; i < childNodes.length; i++) {
    container.appendChild(childNodes[i])
}
var toDom = function(str) {
  var tmp = document.createElement("div");
  tmp.innerHTML = str;
  return tmp.childNodes;
};
**New**
var container = document.getElementById("app-data");
var childNodes = toDom(songlist);
container.appendChild(childNodes);
var toDom = function(str) {
  var tmp = document.createElement("div");
  tmp.innerHTML = str;
  return tmp.childNodes;
};

**Comment by ghost** [comment]
I think the recommended solution to your use-case is to use document fragments.

**Comment by chaals** [comment]
Besides, it isn't clear what problem this proposal actually solves, but it does seem to require a change in behaviour.

Closing this for now - if you think it is worth pursuing, please develop the idea a bit more, explaining why we need it, who is committing to do the work required, and more precisely what that work is - i.e. how would this behave, what sort of input would be allowed, what happens if you provide something else, and what changes from existing implementation.
