### ISSUE TITLE
is td in thead a header?

### ISSUE THREAD

**Issue by chaals** [w3c/html#819]
The [`table` chapter](https://w3c.github.io/html/tabular-data.html) seems to be inconsistent. In [the description of `thead`](https://w3c.github.io/html/tabular-data.html#the-thead-element) it says its cells are headers, but elsewhere in the chapter, including the [table model](https://w3c.github.io/html/tabular-data.html#table-model), only `th` cells are described as header cells.

What do screenreaders report as headers for the cells in the middle column of the tables in http://chaals.github.io/testcases/table-rtl-manual.html - which are in all cases `td` cells in a `thead`
(Note that Firefox and Blink/Webkit lay out the tables differently, and I haven't tested IE/Edge yet)
/@LJWatson @stevefaulkner

**Comment by chaals** [comment]
Safari 10 in VoiceOver on MacOS 10.10 reports a `td` within a `thead` element as a header for a column.

**Comment by stevefaulkner** [comment]
@chaals you need to be careful in inferring semantics exposed in browsers from screen reader output. For example some screen readers in the absence of correctly marked up tables will report the top cell in a column as the col header, and left most cell in a row as the row header.

**Comment by chaals** [comment]
> you need to be careful in inferring semantics exposed in browsers from screen reader output

Yes, I know. I did in fact check the "false negative" cases - Safari/VO reports headers for `th` cells and `thead` cells that fit the algorithm for finding headers.

Common browsers failed to do anything useful with tables beyond layout: no sorting, they don't fix headers when scrolling, they don't expose header information to users themselves, etc etc. So screen readers are the main class of implementation I know for [the algorithm to determine headers](https://w3c.github.io/html/tabular-data.html#forming-relationships-between-data-cells-and-header-cells).

**Comment by chaals** [comment]
OK, I'll do a bit more testing with other screenreader/browser combos. Looking for import/export tools and printing tools might be relevant too, if they have some special treatment for headers.

**Comment by chaals** [comment]
See also #583

**Comment by LJWatson** [comment]
This issue seems to be moot now. The [definition for the ```<thead>``` element](https://w3c.github.io/html/tabular-data.html#the-thead-element) now reads:
>"The thead element represents the block of rows that consist of the column labels (headers) for the parent table element.">

This matches the table algorithm, and also the expectation that ```<thead>``` is a container for one or more rows.

Suggest we close this issue. Although browsers and screen readers have their own (and extremely varied) heuristics for handling data tables in the accessibility layer, that doesn't seem to be relevant to this issue.

Note: the example table in this section has been [cleaned up](https://github.com/w3c/html/commit/63306270623cb6742032e2fb11bd270269e314c3), but isn't showing up because the publishing pipeline is temporarily borked.

**Comment by chaals** [comment]
I don't think it is moot - the question is still:

Does a `td` within a `thead` block represent a column label or header?

The reason it is not entirely esoteric is that it represents guidance to a tool developer.

## If the answer is "no"

While any tool is authorised to add the information in such a cell to what it provides as a heading for a column, it would be applying a heuristic that runs counter to the specification - and therefore authors may rightly be surprised to find that information presented to users in such a way.

There is a rational argument that such cells within the `thead` may be used to add information, treating the `thead` as effectively a distinct sub-table if that is what the user is exploring.

## if the answer is "yes"

Tools **should**, according to the specification, be presenting the contents of such cells as part of what they consider to be the header for a column.

I don't think we have an obvious answer. I'm also not going to get the research into tools done before CR, but as well as screen readers, relevant tools seem to include table formatting tools for print, which repeat headers over multiple pages, and tools that export table information to something else like a spreadsheet where there is a concept of headers.

**Comment by chaals** [comment]
I cleared the milestone. While this is IMHO a real issue that we should answer I don't think it is a burning priority.

**Comment by programmer3000** [comment]
Almost a year passed. Need something to do with it. It's problem just one question - `<td>` possible or not?
IMHO, if you don't know what to do, one of way for resolve it remove `<th>` from HTML specification. So it will remains only `<td>` inside `<tr>`<--`<thead>`. Because logically, all what inside `<thead>` - header.

**Comment by chaals** [comment]
removing `th` makes little sense. It seems fairly widely and well-used, although that is an observation not proper data.

One reason this question has not been answered is that it doesn't appear to matter a lot what the answer is. Which makes it less of a priority.

**Comment by liamquin** [comment]
On Mon, 2018-04-09 at 12:03 +0000, programmer3000 wrote:
> Almost a year passed. Need something to do with it. It's problem just
> one question - `<td>` possible or not?
> IMHO, if you don't know what to do, one of way for resolve it remove
> `<th>` from HTML specification. So it will remains only `<td>` inside
> `<tr>`<--`<thead>`. Because logically, all what inside `<thead>` -
> header.

Older browsers might automatically end a thead and start a tbody if
they encounter a TD, i think, based on tag ommissibility rules. I'm not
sure.

Allowing td in the header might in other words mean that
  <table><tr><td>what is this</td></tr></table>
would become a table header instead of table body.

In addition, th is needed for headers within a 2-dimensional table that
had headers at the start of each row. This allows e.g. a Braille
renderer to transpose the table.


-- 
Liam Quin, W3C, http://www.w3.org/People/Quin/
Staff contact for Verifiable Claims WG, SVG WG, XQuery WG
Improving Web Advertising: https://www.w3.org/community/web-adv/
Personal: awesome vintage art: http://www.fromoldbooks.org/

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
