### ISSUE TITLE
How should RTL tables be processed?

### ISSUE THREAD

**Issue by chaals** [w3c/html#820]
[My quick test of RTL table layout](http://chaals.github.io/testcases/table-rtl-manual.html) shows that there are two behaviours - in Blink and Webkit, `dir="rtl"` has the expected effect, whereas in Gecko/IE/Edge it is only applied to a `table` or to the **individual cells** in a `thead` or `tbody`.

Should we try to get convergence on one behaviour or the other, or just note that in practice this will cause issues?

What do screenreaders do in navigating the various tables?

In everything I tested `<tr dir="rtl">` only applies the rtl directionality to the individual cells...

**Comment by matial** [comment]
One thing is specially important IMO: if <dir="rtl"> is specified at a level higher than a table (e.g. on the HTML, BODY or DIV elements), the table and everything within it should inherit the rtl direction, unless the direction is re-specified at a lower level.

This is very important for translating pages from a LTR written language to a RTL written language, because all the mirroring can be cared for in one place.

**Comment by chaals** [comment]
Yup. In my testing a table inside a `<div dir="rtl">` was laid out RTL by all browsers...

The question here is what should happens when something inside a table - especially `thead` or `tbody` because those are the cases where there is divergent behaviour - is marked in a different direction.

Aside:
Screenreaders running in english maintain the same navigation across the table, as if it were laid out LTR. For a monolingual blind user, this makes sense, since they don't know the layout changed anyway. There is some scope for confusion, among people who use a screenreader to support visual reading as with dyslexia. 

The use case for RTL table layout in non-RTL languages or vice versa isn't clear to me, but the use case for bilingual people swapping between languages is likely to be very large.

The same thing happens in braille, but braille for RTL languages is written LTR in any event, so laying out tables LTR could well be reasonable.

 On the other hand, I think it's probably a user agent implementation issue out of scope for the spec.

I'm curious whether screenreaders in a natively RTL language like arabic or hebrew navigate tables as if they were laid out RTL - either when they are, or always.

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
