### ISSUE TITLE
<body>: Add sectioning content to its categories

### ISSUE THREAD

**Issue by alrdytaken** [w3c/html#830]
https://www.w3.org/TR/html51/dom.html#heading-content
> Heading content defines the header of a section (whether explicitly marked up using sectioning content elements, or implied by the heading content itself).

This part of the specification implies that sectioning content is needed to define a section _explicit_.

https://www.w3.org/TR/html51/sections.html#the-body-element
> 4.3.1. The body element, Categories: Sectioning root.

This part defines &lt;body&gt; as non-sectioning content but sectioning root.

https://www.w3.org/TR/html51/sections.html#example-d42b7aaf
> Foo (heading of explicit body section, containing the "Grunt" paragraph)

Now in this example 27 according to the specifications &lt;body&gt; is an _explicit_ section

https://www.w3.org/TR/html51/sections.html#example-c94b2d39
> Authors are also encouraged to explicitly wrap sections in elements of sectioning content, instead of relying on the implicit sections generated by having multiple headings in one element of sectioning content.
> &lt;body&gt; &lt;h1&gt;Apples&lt;/h1&gt;

And if this example fulfills its advice to wrap headings in sectioning content &lt;body&gt; must be sectioning content.

So to me this is contradictory. I don't know if this statement is true.
_"… for each sectioning content we shall have a heading. Sectioning roots don't. What they do is reset the headings of the contained sections to start with &lt;h1&gt;… "_
This would be true to all elements but &lt;body&gt; which seems to be a hybrid of sectioning content and sectioning root. But this isn't documented anywhere explicitly. 

The other possibility would be that all sectioning roots shall have there own headings just like sectioning content do, but this also isn't documented anywhere. And also in the examples none of the sectioning roots, except of &lt;body&gt; are marked up using headings.

**Comment by rehierl** [comment]
[From the 5.1 spec](https://www.w3.org/TR/html51/dom.html#heading-content): *""Heading content defines the header of a section (whether explicitly marked up using sectioning content elements, or implied by the heading content itself).""*

**(1)** - To be more clear, it should probably state: "(whether **the section is** explicitly marked up using sectioning content elements, **sectioning root elements**, or implied by the heading content itself)."

The reason for the second bold part lies within the definition of sectioning root elements:

[From the 5.1 spec](https://www.w3.org/TR/html51/sections.html#headings-and-sections): *""Certain elements are said to be sectioning roots, including blockquote and td elements. These elements can have their own outlines, but the sections and headings inside these elements do not contribute to the outlines of their ancestors.""*

Continuing an existing section, when a sectioning root element is entered, would mean that a sectioning root element would contribute to the outline of an ancestor. As a consequence, a new section must be created each time such an element is entered (begins). And, in order to make any sense, this new section must also end when the sectioning root element is exited (ends).

So because a sectioning root element defines the beginning of a section, and a point beyond which that section cannot reach, you can state that, in addition to sectioning content elements, **sectioning root elements also define/create explicit sections** - the spec is just not too clear about that.

The most consistent part about HTML4 heading elements is that they define the label of a heading. They merely imply that a new section begins with each element of heading content. And that is what makes them difficult to deal with: They don't really define where these sections end. The only immediate conclusion that one can draw is: If a new section begins, then the previous one must end (or at least be suspended) ... these kind of sections can therefore be seen as **implied sections**.

**Comment by rehierl** [comment]
[From the 5.1 spec](https://www.w3.org/TR/html51/sections.html#headings-and-sections): *""Authors are also encouraged to explicitly wrap sections in elements of sectioning content, instead of relying on the implicit sections generated by having multiple headings in one element of sectioning content.""*

If you have something like this, ...

```
<section>
  <h1>A</h1>
  <h2>B</h2>
</section>
```

... then it does not make sense to surround heading `<h2>B</h2>` with a sectioning root element, because that would break your outline into two separate parts (see above - *do not contribute to the outlines of their ancestors*). That is most likely not what you would want to do. So, from my point of view, **this paragraph does not have to mention sectioning root elements**.

The actual intention behind this statement seems to be: Explicitly mark the beginning and the end of your sections. Do not trust that an outline reader will split your document into sections the way you imagine that it will be done. Some outline reader might do it differently, because where an implied section ends is not always that obvious.

So **this paragraph, by itself, does not state that `<body>` is (also) a sectioning content element**.

**Comment by rehierl** [comment]
[From the 5.1 spec](https://www.w3.org/TR/html51/dom.html#sectioning-content): *""Each sectioning content element potentially has a heading and an outline.""*

**(2)** - When I read both definitions, I simply ignore the "can have" (root elements) and "potentially has" (content elements) parts, because the algorithm will always start a new outline/section when entering a sectioning root element, *or* a sectioning content element. **It should be stated as a fact**, not as a possibility.

**(3)** - What I am missing here is the clarification that **sections and headings of sectioning content elements *do* contribute to the outlines of their ancestors**.

The definition of sectioning content *and* the definition of sectioning root elements *both* state that these elements have an outline. This is consistent with the definition of an outline:

[From the 5.1 spec](https://www.w3.org/TR/html51/sections.html#outline): *""The outline for a sectioning content element or a sectioning root element consists of a list of one or more potentially nested sections ...""*

Both groups of elements have at least one common characteristic: **Any element of sectioning content, and any sectioning root element, has an outline**. This common characteristic is what made you, alrdytaken, believe that the `<body>` element could be *"a hybrid of sectioning content and sectioning root"*.

Unfortunately, this point of view ignores the other characteristic of those elements, which clearly distinguishes them from one another: **The outline of a sectioning content element contributes to that of an ancestor, the outline of a sectioning root element does not.** As a consequence, **the `<body>` element can not be both at the same time**.

The way I see it, a sectioning root element (in general) marks content that is (more or less) self-contained and somewhat loosely connected to the content that surrounds it. A sectioning content element on the other hand extends its surrounding content.

With that in mind, the `<body>` element has more in common with a sectioning root element: Because it is the topmost element, there is no content surrounding it, that a `<body>` element could extend. As a result, **the `<body>` element can not be a sectioning content element** (instead of a sectioning root element).

**Comment by rehierl** [comment]
@stevefaulkner - I think I see why you self-assigned alrdytaken's issue and why you responded with "sounds interesting" to mine (#972).

I still believe that properly defining the common characteristics of both element types, and maybe even including the heading content type (crazy talk, I know), could be the key to move forward. The question is, how far would you be willing to take it, because a proper definition will, without a doubt, require changes that could no longer be seen as non-substantive.

**Comment by alrdytaken** [comment]
Okay, so I took a new approach to this.

# Makes sense to me
Now I assume that this is true:
- A ```section``` is invoked by the appearance of either a ```sectioning content``` or a ```sectioning root```.
- A ```section``` potentially has a ```heading``` associated with it.
- A ```section``` defines the scope of an optional ```<heading>``` and ```<footer>```.

This makes perfect sense and corresponds with all example codes.

# Needs rework in my opinion, proposal A
Though, I propose to update some explaining text, which I feel is misleading:

> The first element of heading content in an element of sectioning content **or sectioning root** represents the heading for that section.
https://www.w3.org/TR/html51/sections.html#sectioning-roots

> Certain elements are said to be sectioning roots, including blockquote and td elements. These elements can have their own outlines, but the sections and headings inside these elements do not contribute to the outlines of ~~their~~ **the sectioning root's** ancestors.
https://www.w3.org/TR/html51/sections.html#sectioning-roots

> Authors are also encouraged to explicitly wrap sections in elements of sectioning content **or sectioning root**, instead of relying on the implicit sections generated by having multiple headings in one element of sectioning content **or sectioning root**.
https://www.w3.org/TR/html51/sections.html#sectioning-roots

> Heading content defines the header of a section (whether explicitly marked up using sectioning content **or sectioning root** elements, or implied by the heading content itself).
https://www.w3.org/TR/html51/dom.html#sectioning-content

Also, I suggest to add ```sectioning root``` to [kinds of content](https://www.w3.org/TR/html51/dom.html#kinds-of-content).
Personally I'd rename _3.2.4.2.3. Sectioning content_ to _3.2.4.2.3. Sections_ and add _3.2.4.2.3.1 Sectioning content_ and _3.2.4.2.3.2 Sectioning root_, knowing that it breaks the consistency of all _kinds of content_ being named _boo content_ at the moment.

# Needs rework in my opinion, proposal B
Another option of course would be to add ```sectioning content``` to ```Categories:``` of each ```sectioning root``` and reducing the definition of ```sectioning root``` to no more more as
> Creates a new outline whose sections don't particpate in its ancestors outlines.

We only need to adjust one explaining text now:
> Sectioning content elements **which are not sectioning root elements** are always considered subsections of their nearest ancestor sectioning root or their nearest ancestor element of sectioning content, whichever is nearest, regardless of what implied sections other headings may have created.

Thx @rehierl for the input.

**Comment by chaals** [comment]
(Assigned two people. Whoever decides to take it should unassign the other)

**Comment by LJWatson** [comment]
Per recommendation from @stevefaulkner, moving this out pending the outcome of discussions happening in the WHATWG regarding the outline algorithm.

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
