### ISSUE TITLE
4.11.7. dialog element - There is no HTML markup to distinguish open as a modal or non-modal

### ISSUE THREAD

**Issue by dance-cmdr** [w3c/html#860]
[4.11.7. The dialog element](http://w3c.github.io/html/interactive-elements.html#the-dialog-element
)

The dialog element supports two ways to open it. `dialog.show()` and `dialog.showModal()`. 

However, in HTML markdown we have only one way to define that a dialog element is open and that is by using the boolean attribute `<dialog open>`. 

The problem occurs when we want to reproduce this `open as modal` state in a declarative way from HTML. in most implementations it appears that open would react as `dialog.show()` 

A use case that I came up was was when I tried to reproduce the markup using a state, for example in react or moustache template engines. But it could be also a problem if, for example, you want to initialise a page with a dialog open in modal mode with plain HTML.

**Comment by chaals** [comment]
@alexandros-s do you have test cases, and/or results broken down by implementation?

I changed the title slightly to try and be clearer what this is asking for...

**Comment by dance-cmdr** [comment]
The test case could be a page with a modal disclaimer that is necessary to be dealt with before we actually use the document. 

Another user case is that in react you have to use antipattern, to change the state of a modal. You can't just do it by adding or removing a property like open or it's value. You instead have to invoke `dialog.showModal()`. I guess it will cause the same problem to other ui tools as well.

Another example is chrome's implementation. There is no way to replicate the result of `dialog.showModal()` with html. If you add an `open` property of a dialog element it behaves as if you invoked `dialog.show()`, there is no backdrop to block interaction with the document. And it kind of makes sense, because there is no property defined, that could be used to declare that the dialog is in modal mode (as if it was opened with `dialog.showModal()`) .

What I'm trying to understand is if the current specification answers this two questions. 
- How can we get a dialog with a backdrop, using only html markup?
- What's the difference between the HTML markup of  a `<dialog open>` element with backdrop = a modal that is the result of a `dialog.showModal()` to a `<dialog open>` element that doesn't have one, the result of a `dialog.show()`.

**Comment by chaals** [comment]
Hi @alexandros-s I think that in this case the first thing we need is to demonstrate that there is a real need for this feature. There are various possible ways to do that, including:

- find a **lot** of sites are already trying to achieve this using e.g. `data-*` attributes or web components.
- show that the question is repeatedly raised on help forums
- show that a couple of library functions that achieve this are very widely used.

At that point, it's worth talking to browser developers to see what they think about the feature. While that can happen here, it's also one of the reasons we have http://discourse.wicg.io where you might want to develop the idea...

**Comment by Dan503** [comment]
I like this idea of being able to distinguish between being an open modal and an open popup in the html.

This is how I see it working:

* `<dialog open="true">` or just `<dialog open>` is the equivalent of calling `dialog.show()` on page load.
* `<dialog open="modal">` should be the equivalent of calling `dialog.showModal()` on page load.
* `<dialog open="false">` should be equal to no `open` attribute at all.

I'm not sure about use cases but it's definitely a logical direction to go in.

**Comment by dance-cmdr** [comment]
Hi @chaals, 
Sorry for taking ages to answer back.

I came across this scenario quite a few times last year.  In most cases, because we were loading javascript at the bottom of the page we had to treat this case separately because in slow connection the modal was popping up too late.

I have to make a case study on how other projects are implementing modals. This will take some time to compete, but, as far as I can see, most implementations and libraries are either too big for the problem, or ignore the dialog standard completely and do everything with js. 

@Dan503 I disagree with `<dialog open="modal">` as it would make the `open` attribute inconsistent. 

I'd personally go with `<dialog open modal>`. A modal feels more like a binary state to me. We either display a dialog as a modal, or not.

**Comment by OmidHekayati** [comment]
Due `dialog` is standard tag and `menu` tag is deprecated in the last version of HTML and as I believe `menu` is kind of dialog, So I think we can have a `type` attributes with these values:
- `<dialog>` or `<dialog type="">`: means default dialog
- `<dialog type="modal">`: means dialog act as modal and background not accessible until close dialog
- `<dialog type="menu">`:  means dialog is a menu with multi-action choice. e.g. hamburger menu, video quality menu, ...
- `<dialog type="alert">`:  means dialog alert something to user interaction and almost always with the "dismiss" button to hide it from screen
- ...

and due to accessibility dialog must always control by an HTML element like a `<button>` to open||close it not just by javascript. So I think we need another attribute like `control-by` just like `aria-owns` or `aria-controls` for the dialog element.

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
