### ISSUE TITLE
Problem with daylight saving time and date-time input element.

### ISSUE THREAD

**Issue by imkremen** [w3c/html#866]
When developing a project where the accuracy of the entered time is very important, we are faced with the fact that in modern browsers elements for entering the date and time do not take into account one of the possible scenarios associated with the transition to daylight saving time.
In most world locations, there have been and will be times when local clocks are moved back. In those times, intervals are introduced in which local clocks show the same time twice in the same day. In these situations, the time that set by input is insufficient to identify a particular moment in time. The user must be able to specify which value he wants to enter, before switching to daylight saving time or after.

I think it would be appropriate to add a mention or warning about this problem in the "semantics-forms" section.

Here you can see more details about this problem https://www.python.org/dev/peps/pep-0495/

**Comment by LJWatson** [comment]
Thanks @imkremen

Do you suggest we put the warning in [4.10.1.8 Date, time and number formats](https://www.w3.org/TR/html52/sec-forms.html#date-time-and-number-formats), [4.10.5.1.7 Date and time state (type="datetime")](https://www.w3.org/TR/html52/sec-forms.html#date-and-time-state-typedatetime), [4.10.5.1.1.11 Time state (type="time")](https://www.w3.org/TR/html52/sec-forms.html#date-and-time-state-typedatetime), or somewhere else?

In any case if you have time to create a PR with your suggested changes, or can suggest some words for the warning here, that'd be really helpful. Thanks.

**Comment by chaals** [comment]
Yes, this would be good to describe, and again, if you have the time to make a suggestion I would also be grateful - and Steve (whom I just made the owner of this issue in the editorial team) probably even more so :)

Note that where timezones are specified as an offset from GMT, this is unambiguous - because when e.g. Melbourne switches from summer to standard time (as it just did), the offset goes from GMT + 11 hours to GMT +11 - so T02:25+1100 isn't the same as T02:25+1000 ... 

But in datetime-local, we don't specify the difference, which is one reason why implementing datetime input would be nice to see - and why it's not that easy :)

**Comment by chaals** [comment]
fixed by #947
