### ISSUE TITLE
Filtering can break usefulness of datalist for long lists

### ISSUE THREAD

**Issue by r12a** [w3c/html#888]
4.10.5.3.9. The list attribute
https://www.w3.org/TR/2017/WD-html52-20170406/sec-forms.html#the-list-attribute

> User agents are encouraged to filter the suggestions represented by the suggestions source element when the number of suggestions is large, including only the most relevant ones (e.g., based on the user’s input so far). No precise threshold is defined, but capping the list at four to seven values is reasonable. User agents that perform filtering should implement substring matching on the label attribute.

The datalist element as it currenlty works provides a very useful tool for finding items in long lists. Take the example of selecting Unicode blocks in UniView. It allows the user to find New Tai Lue quickly when typing 'tai' even though the option name doesn't start with 'Tai'. It also brings together items that are not displayed alongside each other. (There are other examples than tai which are more scattered in the list, so the benefit is greater, but 'tai' lends itself to simple illustrations.)

![screen shot 2017-04-26 at 14 39 16](https://cloud.githubusercontent.com/assets/4839211/25437630/e881b1a6-2a8e-11e7-84d9-0bb5461a9259.png)

Here's what you get if you type 'Tai' in the input field using datalist.

![screen shot 2017-04-26 at 14 40 22](https://cloud.githubusercontent.com/assets/4839211/25437660/00d2e810-2a8f-11e7-871e-fb73f6cf1704.png)

There are nearly 300 block names you can choose from in the selection list, so this is really helpful.

However... the benefit of using datalist for this relies on being able to show all values that match 'tai'.  If the browser filters out some of the options using some undefined algorithm for 'relevance' the user may not be able to find the specific option they are looking for.  This makes datalist unusable for this use case, which is a massive shame.

If we are recommending filtering, can we not have an attribute such as `nofilter` to prevent browsers arbitrarily winnowing the results?

**Comment by chaals** [comment]
@r12a I marked this as a feature request for the attribute. Note that we already added [text that browsers should implement substring matching if they allow filtering](https://github.com/w3c/html/commit/e205f9d142ea0870ddf8bccc2d8a31f9b5abe3df).

I suggest that a `nofilter` attribute or equivalent is a candidate for incubation... what do you think?

**Comment by Malvoz** [comment]
Most likely, authors would expect the behavior of the `nofilter` attribute to be the default behavior. If nothing else, having this features at least enables authors to have `<datalist>` meet those expectations.

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
