### ISSUE TITLE
HTMLMediaElement.prototype.play() should return Promise

### ISSUE THREAD

**Issue by saschanaz** [w3c/html#906]
#368 listed https://github.com/whatwg/html/commit/be8edde20ac46786af968d4de23e90801d4c7213 but it seems there still is no change. Now both Firefox and Chrome stable channel return Promise here, will W3C spec reflect this change?

(Several 'syncing with WHATWG' issues said "closed because of process change", how can I track the syncing issues?)

**Comment by chaals** [comment]
Assuming this is the direction of implementation, then yes we will reflect that.

(collecting every commit to see if we should copy it was unmanageable. Opening issues for things that actually affect someone is the way to track specifics. Otherwise, the current process is for editors to compare sections and see if there are important incompatibilities that should be resolved)

**Comment by cynthia** [comment]
This seems like a pretty serious bug. I'll take it if @travisleithead is swamped. (Pretty sure he is.)
