### ISSUE TITLE
Multiple names for 'name' attribute? (And specify that names may not contain spaces?)

### ISSUE THREAD

**Issue by unor** [w3c/html#907]
The definition of the [`meta` element](https://w3c.github.io/html/document-metadata.html#the-meta-element) doesn’t seem to specify if the `name` attribute can only take one name, or if multiple names are allowed.

If multiple names are allowed, I would have expected to find something similar to what is specified for the [`rel` attribute](https://w3c.github.io/html/document-metadata.html#element-attrdef-link-rel):

> […] must have a value that is a [set of space-separated tokens](https://w3c.github.io/html/infrastructure.html#set-of-space-separated-tokens). The allowed keywords and their meanings are defined in a later section.

Does this omission mean that only one name is allowed, or is it an oversight? Am I missing something?

----

Test case:

```html
<meta name="author dcterms.publisher designer" content="Alice" />
```

The [Nu Html Checker](https://validator.w3.org/nu/) doesn’t complain, but I don’t know if it considers `author dcterms.publisher designer` to be *one* name or three names, because it no longer reports when unregistered names are used, and because the spec doesn’t seem to state that names cannot contain spaces. 

----

Proposal:

* specify that the `name` attribute can take a set of space-separated tokens, referencing the lists of allowed tokens (i.e., the names defined in the spec and the names registered in the wiki) 
* add to [*Other metadata names*](https://w3c.github.io/html/document-metadata.html#other-metadata-names), under "Keyword", which characters a name may consist of, and don’t allow spaces

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
