### ISSUE TITLE
Deprecate or obsolete plugin API?

### ISSUE THREAD

**Issue by mavgit** [w3c/html#928]
There's been lots of activity for a few years now removing plugins from browsers:
- Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=615738
- Mozilla:  https://developer.mozilla.org/en-US/docs/Plugins
- Safari:  https://webkit.org/blog/6589/next-steps-for-legacy-plug-ins/
- Edge:  https://blogs.windows.com/msedgedev/2016/12/14/edge-flash-click-run/#riXOl0tb6u7SRBO8.97
 
Given all this activity, it would seem that deprecating or obsoleting the plugin API from the HTML5 spec is overdue. We don't want new browsers or new app code being written to this API.

**Comment by LJWatson** [comment]
Note these co-ordinated announcements from [Microsoft](http://blogs.windows.com/msedgedev/2017/07/25/flash-on-windows-timeline/), [Google](https://www.blog.google/products/chrome/saying-goodbye-flash-chrome/), [Apple](https://webkit.org/blog/7839/adobe-announces-flash-distribution-and-updates-to-end/), and [Mozilla](https://blog.mozilla.org/futurereleases/2017/07/25/firefox-roadmap-flash-end-life/) indicating their respective roadmaps for ending Flash support in their various browsers. The announcement from [Adobe](https://blogs.adobe.com/conversations/2017/07/adobe-flash-update.html) is the lynchpin.

**Comment by swickr** [comment]
I suggest that the next step be to obsolete the feature; it is premature to remove it in this version.
I see that the 18 July Working Draft marks it "at risk" which is a label conventionally applied to new features unsure of passing through CR.  That label doesn't feel appropriate for this case.

**Comment by LJWatson** [comment]
@swickr >"I suggest that the next step be to remove the feature; it is premature to remove it in this version.">

We discussed this on the [HTML call](https://www.w3.org/2017/07/25-html-minutes.html#item05) this week, and decided to move this feature to "obsolete but conforming" in this version.

We've typically used the "at risk" label to indicate `any` features that are at risk of removal due to lack of interop. With hindsight it might not have been the most suitable label for this feature, but at the time we didn't know what timeline either Adobe or the browser implementors would put on ending Flash support, but wanted to give ourselves flexibility to respond appropriately if that became known in time for us to do so.

**Comment by travisleithead** [comment]
Hey folks, take a look at the PR and let me know what might need adjusting. Thanks!
