### ISSUE TITLE
Tracking errata?

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#931]
We could do with a mechanism for tracking errata over multiple versions of the spec. We currently have an "errata" label, but it isn't version specific.

Possible options...

* We create version specific errata labels ("5.1 errata", "5.2 errata" etc.).
* We create (repurpose) an "Errata" Github project, with columns for each version of the spec.
* Other?

**Comment by siusin** [comment]
An "Errata" project sounds great!

**Comment by chaals** [comment]
Projects seems a reasonable approach. In my wishes I would have a more powerful labelling system that allowed for class hierarchies and things. But we don't.

**Comment by LJWatson** [comment]
If we use a Project, should each column be the name of the spec that contains the corrections (5.1 2nd ed for example), or the name of the spec that had the errors in the first place (5.1 for example)?

**Comment by travisleithead** [comment]
Another idea: just create a *.md or *.html file that describes the errata. Once these are created, we'd seldom ever need to see them again. I don't like the idea of mixing errata with other issues.

**Comment by chaals** [comment]
I don't mind mixing errata - because we can always close them as wontfix and drop the project if, e.g. we make the version they correspond to obsolete... and if an issue is an erratum on the current spec and applies to the new one, that seems reasonable.

I hope we will start moving old specs replaced by later versions to Obsolete status...

**Comment by LJWatson** [comment]
Ping @ArronEi, @SteveFaulkner, @ADanilo, and @Cynthia for thoughts please.
