### ISSUE TITLE
Support <optgroup> in <datalist>

### ISSUE THREAD

**Issue by jpdevries** [w3c/html#932]
`<optgroup>` is useful for displaying options to users, but browsers don't support it with `<datalist>`.

4.10.9 The optgroup element has only one context specified for `<optgroup>`
 - As a child of a select element.

This issue suggests adding another
 - As a child of a datalist element.

or in some other way specifying that browsers should support `<optgroup>` when displaying options on a `<datalist>` 🙏

<details>
<summary>Screenshots</summary>
<h3>Current Experience (Chrome)</h3>
<p>Options are not grouped</p>
<img src="http://j4p.us/0E2u2013232t/Screen%20Shot%202017-05-26%20at%2012.14.31%20PM.png" alt="Datalist without optgroup labels">

<h3>Suggested Experience</h3>
<p>Options are grouped</p>
<img src="http://j4p.us/3R3O282H2E2M/Screen%20Shot%202017-05-26%20at%2012.25.40%20PM.png" alt="Datalist with optgroup labels">

</details>

**Comment by chaals** [comment]
I like this idea. I hope browser developers will like it too, enough to implement it. Or maybe someone can polyfill this to show what sort of uptake it gets. Which, as something like "fraction of datalists long enough for it to make sense that use this" would demonstrate that it solves a real problem...

**Comment by jpdevries** [comment]
Glad to hear it @chaals. I've thought about taking a swing at a polyfill. The only bummer about a polfyill of course is it wouldn't use browser chrome. But if it would help move this along I'm game!

**Comment by jpdevries** [comment]
@chaals I started [working on a polyfill in this Codepen](https://codepen.io/jpdevries/pen/MoROzK). Eventually I'll move it to a repo of its own.

`<optgroup>` is coming!

<details open><summary>GIF Preview</summary><img src="http://j4p.us/390m3l1P4433/poly.gif" alt="Demo of Codepen" /></details>

**Comment by siusin** [comment]
Thanks @jpdevries .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
