### ISSUE TITLE
Parsing of table cells (calculated height)

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#935]
Migrated from [Bugzilla 26464](https://www.w3.org/Bugs/Public/show_bug.cgi?id=26464).

From the original issue:
>"Presently in Google Chrome the calculated CSS height attributes of all table cells within a table row are equal with each table cell having a height attribute equal to the height of the tallest cell in the table row. In Internet Explorer and Firefox the calculated CSS height attribute of each table cell within a table row is different with each table cell having a height attribute reflective of the height of the content contained within the cell. Perhaps going forward it would be preferable to follow Google Chrome's lead. Then each cell within the row would allow for child elements contained within the cells to be fitted to the available space by setting the table cell's CSS position attribute to relative and then the CSS position attribute of the contained child element to absolute such that the child can take on it's parent table cell's CSS width and CSS height attributes. This seems like a sensible course to take considering that users seeking the CSS height value of the content contained within a cell could simply wrap the content in a div wrapper. Perhaps there could even be a CSS content-height attribute?
>
>As I say Google Chrome already has taken-on this approach, and the benefit is as set-out in the above paragraph, namely that after a long time there finally is a solution in Google Chrome to getting child elements to fill-out the available space within a parent table cell."

**Comment by pavankjois** [comment]
ha

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
