### ISSUE TITLE
Indicate required state on checkboxes

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#936]
Migrated from [Bugzilla 26555](https://www.w3.org/Bugs/Public/show_bug.cgi?id=26555)

From the original issue:
>"There appears no logical place to indicate that some input is "required" for a group of checkboxes. If you inserted "required" into each checkbox, it would require that each checkbox be checked.
While checkboxes may be either checked or unchecked, a scenario is possible in which at least one checkbox would be required, such as asking the User which language she/he speaks. (Ostensibly this is at least one, as they are interacting with the form).
```<select>``` multiple> offers an alternative, but can be visually daunting; checkboxes provide an elegant method for the User to review his/her selections, at-a-glance.
Thank you for reviewing my bug submission.">

**Comment by LJWatson** [comment]
Ping @Hober, @JacobRossi, @JakeArchibald, @Tantek. Thoughts?

**Comment by jakearchibald** [comment]
Hmm yeah, I'm kinda surprised that checkboxes behave differently to radios in this case, but it's too late to change now.

We could introduce something like `<fieldset requireone>` which asserts that at least one descendant input passes a "required" check.

This allows you to express a fieldset that contains 10 checkboxes and an "Other" text input, where you must select at least one checkbox or enter something into the "other" field.

**Comment by chaals** [comment]
Since we're apparently speculating here, because we don't have a concrete solution, an alternative may be to state that validity of a particular input satisfies a scoped validity, and allow fieldset to automatically act as that scope.

This would enable chaining, which I think is important.

The case where I run across this regularly is sites that require *some* form of contact - be it email, telephone, or in some cases other things, and have special magic to tell when you got at least one of them filled in "right" - which in some cases means actually validating postal addresses before that's considered satisfactory.

Is there any appetite for implementation of something to solve this problem in a browser, assuming we can agree on a proposed solution?

**Comment by prlbr** [comment]
I think the proposal by @jakearchibald is good. I would prefer reusing the `required` attribute name on the `<fieldset>` element to introducing a new name though. The `disabled` attribute is a parallel: it works both with fieldset and with other form elements.

I hope there is implementor interest.

**Comment by jakearchibald** [comment]
@prlbr I considered `required`, but that may suggest that all are required.

**Comment by prlbr** [comment]
Ah, I see. But

- `required` on `<select>` does not mean that all `<option>`s need to be selected.
- `required` on each `<input type='radio'>` in a group of radio buttons that share a common `name` means that just one radio button must be selected. (We can only select a single one anyway.)
- Maybe even more confusingly, a `required` on a single radio button from a group of radio buttons that share a common `name` means that one of the group must be selected, [but it does not need to be the one with the `required` attribute](https://www.w3.org/TR/html5/forms.html#attr-input-required).

The pattern seems to be to reuse the `required` attribute even if its exact function is not necessarily obvious from the attribute name.

**Comment by jakearchibald** [comment]
I don't see `<select required>` in the same way, as the select is the form field and you're requiring a value from it.

The radio case is the exception, and in retrospect seems like a design mistake.

I don't have strong feelings here, but we should be wary that `required` currently applies to a single form element (with the exception of radios), and giving it different behavior on non-form elements may cause problems down the line should we allow developers to define their own form elements.

**Comment by LJWatson** [comment]
Given that ```<fieldset disabled>``` disables all the fields in the set, using ```<fieldset required>``` would presumably make all fields in the set required. Using `requireone` seems like a good approach.

@JakeArchibald do you think this is something that Google might consider for Chrome implementation?

**Comment by jakearchibald** [comment]
I'll reach out to someone who owns the forms implementation.

**Comment by chaals** [comment]
Presumably 

```
<fieldset requireone>
   <!-- ... some form controls -->
   <fieldset requireone>
      <!-- a nested set of form controls -->
   </fieldset>
   <fieldset requireone>
      <!-- another set of nested controls --> 
   </fieldset>
 </fieldset>
```

Would be satisfied if any of the nested fieldsets were satisfied, no?

ping @asurkov, @bkardell

**Comment by jakearchibald** [comment]
There isn't a case where an outer `<fieldset requireone>` could fail while an inner `<fieldset requireone>` could pass.

**Comment by chaals** [comment]
@jakearchibald sorry to be dense, but I am not certain what you are saying. I **think** you mean that in an example like mine above, if one of the controls in the outer `fieldset` is valid - which may be one of the inner `fieldsets` being satisfied based on whatever is nested inside it - then the outer `fieldset` will be satisfied.

Did I understand correctly?

**Comment by jakearchibald** [comment]
If the rule for `requireone` is "One of the descendant form fields must satisfy its 'required' constraint", we don't have to consider nested `<fieldset requireone>`s specifically, they just work.

**Comment by chaals** [comment]
I wonder when we will get the request to require any 2...

I can see use cases for making the attribute an integer rather than a boolean -  with default value being 1. Without looking at a lot of actual content I don't know how common this is, and I have not thought about whether it complicates the proposal or implementation much.

IMHO it's reasonable to leave this to be done in script - but I don't produce a whole lot of forms so MHO may not be the best informed.

**Comment by siusin** [comment]
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
