### ISSUE TITLE
Attribute to reset viewport in specific contexts

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#938]
Migrated from [Bugzilla 29731](29731).

From the original issue:
>"I have been thinking about element queries and math-based css selectors to enhance modular web development and presentation of html fragments in different scenarios.
>
>The most simple method (in terms of backwards compatibility and complexity) i came up with is the following approach:
>
>Introduce a new html attribute or css property that can be applied on certain html tags to reset the viewport (base for media query calculations). Once media queries are evaluated the viewport root is used for calculation instead of the screen. As a fallback (height for example) the screen/media will be used.
>
>That way you could style widgets/html fragments for the context they are displayed in (instead of the media they are rendered on).
>
>A css property (like: `viewport:reset` or `media:reset-viewport`) or a html attribute (`<section resetviewport></section>`) would be necessary.
>
>I think many other approaches (element query or math-based selectors) to handle the problem of "adaptive layouts" have massive downsides.
>
>let me know what you think about this."

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
