### ISSUE TITLE
Proposal: allow servers to suggest alt tags for images, and possibly other content.

### ISSUE THREAD

**Issue by frederikcreemers** [w3c/html#961]
I'm sorry if this is not the right place for suggestions like this.

Many images on the web today are generated dynamically. The page author can often not write a useful alternative text because of this. What if servers could send a header along with the media, that suggests alternative text?

Some examples where this could be useful:

 - project [badges](https://github.com/badges/shields) on open source projects
- [Stack overflow Flair](https://stackoverflow.com/users/flair)
- 90's/00's style [visitor counters](http://www.reliablecounter.com/)
- Server-generated charts

Is there anything I can do, except posting it here, to submit this proposal for consideration?

**Comment by LJWatson** [comment]
Thanks @BigBlind. It's always good to hear new ideas, so there's no need to apologise for posting here.


That said, I don't think this is something that could be addressed in the HTML specification. Browser headers are defined as part of HTTP rather than HTML, so that's the spec that would need to be revised.

Typically browser headers are metadata (information about content, rather than content itself) though, so sending content in the form of alt texts would be a departure from the current way of doing things. This would need buy in from the browser vendors at the very least, so one possibility is to post your idea to the [Web Incubator Community Group](https://www.w3.org/community/wicg/) for wider discussion.

It might be worth taking a different direction to solving this though. Perhaps looking at the different AI APIs for automatically generating alt texts, and how they can be used to solve the problem case you outline?

**Comment by chaals** [comment]
HTML doesn't define headers - that happens in the IETF HTTP Working Group.

It is also not clear how a header would get incorporated, and this proposal would need to explain that. It could be done in a way analagous to dictionary compression, and it actually feels a fair bit like a use case for a tweak to SDCH...

As an alternative approach, most image formats can carry metadata in the image itself. If there were an API for a page to get that data, it could be used to dynamically update the page content on load.

But so far, browsers have not provided that kind of access (except in the case of SVG). There have been proposals, but I am going to close this issue sadly for now as needing incubation. If you ping me I'll try to find some of the older work in this area.
