### ISSUE TITLE
dl specification: is the description contradictory?

### ISSUE THREAD

**Issue by alrdytaken** [w3c/html#977]
https://www.w3.org/TR/html51/grouping-content.html#the-dl-element

In `Content Model` it states:
`Zero or more groups each consisting of one or more dt elements followed by one or more dd elements …`

I think this must be corrected to:
`… followed by zero or more dd elements …`

Reason herefore is that further down it has an use case for dt elements without following dd elements:
`… If a dl element has one or more dt element children, but no dd element children, then it consists of one group with terms but no descriptions. `

And the dt specification's `Contexts in which this element can be used:` states:
`Before dd or dt elements inside dl elements.`

**Comment by prlbr** [comment]
I don’t think that’s a contradiction. I think that …

`If a dl element has one or more dt element children, but no dd element children, then it consists of one group with terms but no descriptions.`

… just describes an invalid state. Sometimes it makes sense to describe things that can be encountered in the real world, so that we know how to interpret them, even if they are not valid.

The `<dt>` specification you quote isn’t contradictory either. Here’s an example that matches the spec and where `<dt>`s precede both `<dt>` and `<dd>` once:

```
<dl>
<dt>dog</dt>
<dt>pooch</dt>
<dd>furry four-legged domestic animal, also called man's best friend</dd>
</dl>
```

**Comment by alrdytaken** [comment]
Well, that would make sense, too.

**Comment by LJWatson** [comment]
That spec text doesn't really make it clear that a ```<dl>``` with ```<dt>``` but no ```<dd>``` elements is invalid. It could probably do with improving for clarity.

**Comment by chaals** [comment]
See also #1116 - another editorial issue for the `dl` element
