### ISSUE TITLE
Requirements for (X)HTML in 'script' data blocks?

### ISSUE THREAD

**Issue by unor** [w3c/html#978]
For using [`script`](https://w3c.github.io/html/semantics-scripting.html#the-script-element) as data block, the spec says:

> […] the contents of the `script` element must conform to the requirements defined for the format used.

Are such requirements for (X)HTML in `script` data blocks defined anywhere in the spec? If not, this would mean that the content has to be a full document, correct? Is this intended or should a snippet be allowed, too?

```html
<script type="text/html">
  <p>snippet</p>
</script>
```

If a snippet should _not_ be allowed, is the `title` element required, or would "title information is available from a higher-level protocol" apply here (as defined in [`head`](https://w3c.github.io/html/document-metadata.html#the-head-element)’s content model)?

Nearby: 

* [`template`](https://w3c.github.io/html/semantics-scripting.html#the-template-element) allows "fragments of HTML"
* for [`iframe`-`srcdoc` documents](https://w3c.github.io/html/semantics-embedded-content.html#an-iframe-srcdoc-document), the DOCTYPE and the `title` element is not required

**Comment by siusin** [comment]
Thanks @unor .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
