### ISSUE TITLE
'Media element' should be a category

### ISSUE THREAD

**Issue by shepard8** [w3c/html#980]
The context of the [track element](https://www.w3.org/TR/html5/embedded-content-0.html#the-track-element) contains a reference to [media element](https://www.w3.org/TR/html5/embedded-content-0.html#media-element).

The two only elements that can be media elements are audio and video. I think that media elements should be a category, and that both audio and video elements should have media-element listed in their categories.

The reason is that contexts are all defined in terms of category names, element names, attribute names and attribute values. Except for two elements, [track](https://www.w3.org/TR/html5/embedded-content-0.html#the-track-element) and [source](https://www.w3.org/TR/html5/embedded-content-0.html#the-source-element) which make reference to media element. This complicates any try to create a logical model representing what an HTML5 document is.

However, if there is a reason media elements are not a category, please let me know.

**Comment by scottaohara** [comment]
While I agree that this issue should be addressed in the future, I think there's a lot of overlap with embedded content that media elements could also potentially just be considered a sub-category of embedded content.

Would we then also want to consider elements, like `picture`, which also allows `source` as a child, to be considered media elements?

**Comment by siusin** [comment]
Thanks @shepard8 .

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.
