### ISSUE TITLE
adjust description of header element to ARIA banner role meaning

### ISSUE THREAD

**Issue by prlbr** [w3c/html#981]
The `<header>` [element discription](https://w3c.github.io/html/sections.html#the-header-element) contains the following paragraphs:

> When a header element’s nearest ancestor sectioning root element is the body element, and it is not a descendant of the main element or a sectioning content element, then that header is scoped to the body element and _represents introductory content for the **page** as a whole_.
>
> Assistive Technology may convey to users the semantics of the header element _when it applies to the whole *page*_. This information can provide a hint as to the type of content. For example, _the role of the element, which in this case is "banner"_, can be announced by screen reader software when a user navigates to a header element that is scoped to the body element.

(Emphasis added by me.) On the other hand, the [ARIA description](https://www.w3.org/TR/wai-aria-1.1/#banner) of the banner role is:

> A region that _contains mostly *site*-oriented content, rather than page-specific content_.
>
> Site-oriented content typically includes things such as the logo or identity of the site sponsor, and a site-specific search tool. A banner usually appears at the top of the page and typically spans the full width.

This may not be a hard contradiction, because site-oriented content does usually also apply to each page as a whole, but the description of HTML `<header>` is definitely not clear that `<header>` “scoped” to `<body>` is not for page-specific content, but for site-oriented content.

My suggestion would be to reuse the ARIA wording in the HTML description to make it clearer.

> When a header element’s nearest ancestor sectioning root element is the body element, and it is not a descendant of the main element or a sectioning content element, then that header is scoped to the body element and represents _mostly site-oriented content, rather than page-specific content_.
>
> Assistive Technology may convey to users the semantics of the header element when it _is site-oriented_.

**Comment by unor** [comment]
While it’s certainly the most common case, not all HTML documents are part of a site. 

If this gets changed, I think we should include all cases / not exclude cases.

Maybe it would be possible to add an explanation somewhere (and refer to it where applicable) that "content for the page as a whole" can mean for HTML documents which are part of a website that it’s site-oriented content.

**Comment by LJWatson** [comment]
Changing the first paragraph as @prlbr suggests, seems like a good idea to me. 

<When a header element’s nearest ancestor sectioning root element is the body element, and it is not a descendant of the main element or a sectioning content element, then that header is scoped to the body element and represents mostly site-oriented content, rather than page-specific content.<

Noting @unor's concern, I don't think it's helpful in this situation to call out the less common example. If we do, we risk losing the distinction being drawn between site-wide content and page specific content, and I think that's the more important thing to convey here.

We can't change the second paragraph though. An AT will convey the semantics of the ```<header>``` element, only when it's scoped to the ```<body>``` element. That means the second paragraph is accurate in its current form.

**Comment by LJWatson** [comment]
Thinking further, I think we can address @unor's concern more easily than I thought:
<When a header element’s nearest ancestor sectioning root element is the body element, and it is not a descendant of the main element or a sectioning content
element, then that header is scoped to the body element and represents mostly site-oriented content, or introductory content for the page as a whole.<
