### ISSUE TITLE
Suggestion: new element to display current date

### ISSUE THREAD

**Issue by wellingtonpgp** [w3c/html#983]
Create a tag that takes current date 📅

**Comment by LJWatson** [comment]
Can you describe what this element would actually do?

**Comment by wellingtonpgp** [comment]
Display the current date.

**Comment by SebastianZ** [comment]
@wellingtongeek You should have described your suggestion in a bit more detail.

If this is to be considered, I'd rather say to extend the [`<time>` element](https://rawgit.com/w3c/html/html5.1-2/single-page.html#the-time-element) to take a `now` keyword (and maybe others) as value for the `datetime` attribute and a new attribute like `format` that allows to specify an output format for the specified date. I.e. if the `format` attribute is present, the element's contents are generated from the `datetime` attribute.

`format` would take formatting options as it is the case in programming languages like e.g. [PHP's `date()` function](http://php.net/manual/en/function.date.php).

To keep the machine readable representation, [`HTMLTimeElement.dateTime`](https://rawgit.com/w3c/html/html5.1-2/single-page.html#dom-htmltimeelement-datetime) would return the current date and time as [valid global date and time string](https://rawgit.com/w3c/html/html5.1-2/single-page.html#valid-global-date-and-time-string).

Sebastian

**Comment by LJWatson** [comment]
What is the use case for this element (what problem does it solve)? Is there evidence that the web community needs a solution like this (existing polyfills/hacks/workarounds in wide use that achieve this behaviour)?

**Comment by SebastianZ** [comment]
It allows to represent a date in machine as well as in human readable format.

With the current definition of the `<time>` element those two formats can diverge. This feature would allow to connect both to avoid this discrepancy. Also, it would allow to display the date and time information in situations where server-side and client-side scripts are not available or not able to generate the desired output.

Having said that, I currently don't have a real personal use case or a strong opinion about this. So, I didn't check whether there are any polyfills, hacks, or workarounds for this. I just wanted to jump in, because @wellingtongeek didn't explain his idea and I think `<time>` could be reused and improved to cover more use cases.

Sebastian

**Comment by SebastianZ** [comment]
Btw., @wellingtongeek or @LJWatson, could you please adjust the summary to be more specific? Currently it is just meaningless.

Sebastian

**Comment by chaals** [comment]
I think there are a couple of problems with this proposal. The first is that "display the current date" isn't quite as simple as it seems because of time zones.

The second is that if you have taken into account the time zone issue, this is a trivial thing to do with a minimum amount of javascript, so there isn't obviously a lot to gain by having an element do this instead. In particular, the proposal doesn't explain, and I cannot easily imagine, where the need for this element is really pressing.

Introducing a new element is risky, because bad implementation can mean we do a lot of wasted work around the world and end up with something unusable, or that is often unsuitable. I would propose closing the issue, and if you think there is a need for this, proposing it and demonstrating enough support to justify implementation, e.g. in the [WICG incubator](https://discourse.wicg.io) before reopening.

**Comment by chaals** [comment]
Closing this in favour of incubation first.
