### ISSUE TITLE
Support elements in <option> elements

### ISSUE THREAD

**Issue by SebastianZ** [w3c/html#996]
For `<option>` elements it should be allowed to place other elements inside them. Especially `<img>` and `<picture>` elements are useful, but also other phrasing content elements like `<b>`, `<em>`, `<ruby>`, `<time>`, etc. should be supported.

Sebastian

**Comment by chaals** [comment]
This involves a significant change to a well-established piece of HTML, because it would mean change to all parsers as well as rendering engines. That means we are unlikely to adopt it without support from browsers.

I suggest incubating it first in e.g. the [W3C incubator group](https://discourse.wicg.io) and getting some browser buy-in.

**Comment by SebastianZ** [comment]
> I suggest incubating it first in e.g. the W3C incubator group and getting some browser buy-in.

Ok, asking at https://discourse.wicg.io/t/support-elements-in-option-elements/2293.

Sebastian

**Comment by chaals** [comment]
Closing here until it comes back incubated
