### ISSUE TITLE
define what it means for elements to be “referenced”

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/html#998]
See https://github.com/whatwg/html/pull/2841

**Comment by chaals** [comment]
E.g. you can make a link to an element, but you can also refer to it in prose such as "in diagram 7, we see..."

This is basically authoring advice.

Linking has the benefit that the reference is unambiguous - so long as the link doesn't break because then it just becomes confusing.

"Plain language" references in prose can equally come unstuck - if you say "above" and then move something to "below", or change your numbering/naming scheme...

**Comment by brucelawson** [comment]
Suggest we don't define this; it's an English word.
